### ISSUE TITLE
Unable to define an empty trait with indentation-based syntax

### ISSUE THREAD

**Issue by julienrf** [lampepfl/dotty#10080]
## Minimized code

```Scala
trait Foo:
end Foo
```

## Output

This code does not compile. The error message is:

~~~ text
end Foo
^^^
indented definitions expected
~~~

However, it is possible to create an empty trait with the brace-significant syntax:

~~~ scala
trait Foo {
}
~~~

## Expectation

The first definition of trait `Foo` should compile just like the last one.

**Comment by odersky** [comment]
In fact, you can define an empty class with an end marker:
```scala
trait Foo
end Foo
```
But it does not work anymore if you add a `:`.

**Comment by julienrf** [comment]
I think the following should be valid:

~~~ scala
trait Foo
~~~

~~~ scala
trait Foo:
// Equivalent to
trait Foo {}
~~~

~~~ scala
trait Foo:
end Foo
// Equivalent to
trait Foo {
}
~~~

But the following should be rejected:

~~~ scala
trait Foo
end Foo
// Equivalent to
trait Foo
}
~~~

**Comment by som-snytt** [comment]
I was about to contribute a reversion when I noticed the behavior was intentional.

This violates the principle that end marker is optional and can be removed without breaking compilation. End markers are not braces.

https://github.com/lampepfl/dotty/issues/12340#issuecomment-867802649

> end markers an optional addition to a program. The program needs to be syntactically correct even if they are missing.

https://github.com/lampepfl/dotty/issues/12918#issuecomment-867536610

Related judgment

> In my understanding the colon is actually the key difference between a class/trait/object with a body and without it. 

https://github.com/lampepfl/dotty/issues/12185

Notice that there are a couple of disappointed expectations in the previous comment https://github.com/lampepfl/dotty/issues/10080#issuecomment-717095952 

```
trait T:   // not ok without body

trait T
end T   // perfectly fine
```

The misapprehension at https://github.com/lampepfl/dotty/issues/12340 is that there is something wrong with
```
trait T {
}
end T
```
where I will contribute my diabolical suggestion
```
trait T:
  def t = ???
end T
// unindents to
trait T {
  def t = ???
} // end T
```
because if it needs an end marker, then it also needs an end comment.

Currently, `-rewrite -no-indent` does not modify
```
class C:
end C
```
