### ISSUE TITLE
Doc sources contain spaces at end of lines

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#10138]
We have a general policy of stripping all spaces at end of lines on save, since that keeps diffs small. Currently scala3doc sources violate this requirement.

**Comment by abgruszecki** [comment]
We should also make the indentation in doc sources uniform. Right now we have a good opportunity to do both: some PRs to the doctool were merged while we were working on repo migration and we will need to migrate those as well. Since this will anyway disrupt everyone's in-flight branches, we might as well fix the indentation everywhere and ensure we keep it consistent this time.
