### ISSUE TITLE
Doc: infinite loop in implicitly-added member lookup since upgrade from 0.27-RC1

### ISSUE THREAD

**Issue by abgruszecki** [lampepfl/dotty#10166]
Uncommenting the following lines causes an infinite loop when documenting S3D testcases: https://github.com/dotty-staging/dotty/commit/fd6a59345bddf2e446271735275aba9643de9ec7

This code worked previously on 0.27-RC1.

This seems to be caused by the following classes: https://github.com/dotty-staging/dotty/blob/demo%2Fdoctool-infinite-loop/scala3doc-testcases/src/example/Inheritance.scala#L11-L19.
Specifically, members of example.A.B.D include example.A.B and vice versa.

@nicolasstucki took a glance at our hack to list all members of a class (https://github.com/dotty-staging/dotty/blob/demo%2Fdoctool-infinite-loop/scala3doc/src/dotty/dokka/tasty/SyntheticSupport.scala#L65-L76) and he doesn't see any obvious problem with it.

**Comment by abgruszecki** [comment]
@pikinier20 since you dealt with this code previously, can you take a look at this issue?

**Comment by pikinier20** [comment]
Of course, I will look at it tomorrow.

**Comment by pikinier20** [comment]
Okey, I think I've figured out the reason:
I've printed out `inherited` variable and for 0.27-RC1 I've got:
```
[info] extracting members of: example.C
[info] List(given_Unit, extension_foo)
[info] extracting members of: example.A
[info] List()
```
So `getNonTrivialInheritedMemberTrees` for class C was returning only one given method and one extension method
but when I've done the same for new version, I've got:
```
extracting members of: example.C
List(I, extension_foo, B, X$, given_Unit)
```
So currently, the same method returns also classlikes and that's why we go into infinite loop.

I'm gonna fix this today
