### ISSUE TITLE
Move scala.internal.quoted to scala.quoted.internal?

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#10222]
If we could avoid adding even more stuff inside scala that would be great, and there's nothing else in scala.internal, wdyt @nicolasstucki ?

**Comment by smarter** [comment]
There's also a dotty.internal which only contains CompileTimeMacros, could that one be a private object where it's used instead?

**Comment by nicolasstucki** [comment]
Adding it an `internal` to `quoted` would mean that each time we import `scala.quoted` we would import `internal`. This would not be ideal.

**Comment by smarter** [comment]
But the compiler adds `import scala._` to all Scala files automatically, so we're already importing internal.

**Comment by smarter** [comment]
The alternative would be to keep the internal stuff as package private in scala.quoted

**Comment by nicolasstucki** [comment]
`Patterns` and `PickledQuote` could fit as package-private in `scala.quoted`. I'm not sure about `CompileTime`. 

`internal.quoted.{Expr,Type}` classes exist to allow `quoted.{Expr,Type}` to have `private[scala]` constructors. In theory, we could implement those in the compiler but we cannot do it because the compiler is not in the `scala` package. Maybe we should move the compiler root package `dotty` to `scala.tools.dotty` and follow the same naming scheme as in Scala 2 (`scala.tools.nsc`).
