### ISSUE TITLE
Dotty deviation: packages in `scala` shadow user-defined packages

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1041]
collection/ArrayBuffer.scala:
```
package collection

class ArrayBuffer[T] {
}
```

benchmark/Main.scala
```
package benchmark
import collection._


object Main {

    def array_create(): ArrayBuffer[Int] = ???
}
```
dotc benchmark/Main.scala collection/ArrayBuffer.scala
```
benchmark/Benchmark.scala:7: error: not found: type ArrayBuffer
    def array_create(): ArrayBuffer[Int] = ???
                        ^
one error found
```

compiles fine with scalac.

**Comment by DarkDimius** [comment]
If package is renamed to `collection1`, compilation succeeds.

**Comment by DarkDimius** [comment]
Same happens with classes, if `collection1` defines a `class List(head: Int, tail: List)`
```
import collection1._
new List(1, null)

benchmark/Benchmark.scala:51: error: too many arguments for constructor List: ()scala.collection.immutable.List[Int] 
```

**Comment by odersky** [comment]
Did you try to import _root_.collection?.

On Wed, Jan 20, 2016 at 11:23 AM, Dmitry Petrashko <notifications@github.com
> wrote:

> Same happens with classes, if collection1 defines a class List(head: Int,
> tail: List)
>
> import collection1._
> new List(1, null)
>
> benchmark/Benchmark.scala:51: error: too many arguments for constructor List: ()scala.collection.immutable.List[Int]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/issues/1041#issuecomment-173162318>.
>



-- 
Martin Odersky
EPFL

**Comment by DarkDimius** [comment]
@odersky using _root_.collection makes it compile.

**Comment by odersky** [comment]
I think it's a won't fix. The Scala spec says:
    ...
   Wildcard imports  have next highest precedence.
   Definitions made available by a package clause not in the
   compilation unit where the definition occurs have lowest precedence.

That's the case here. `collections` is made available by a package clause (i.e. package _root_)
and it's not in the compilation unit where the definition occurs. So it is shadowed by `scala.collections`.

I also think that's the right choice. You generally don't have control over what's in your root package; it could be arbitrary junk contributed by others. So if definitions in the root package would supersede
imports, then you could never trust an import. Writing

    import collections.immutable.List

would risk breaking code everytime someone dumps a root collections package into the classpath. In effect it would force everyone to use absolute package names only in order to avoid that scenario. But then why have relative package names in the first place?
