### ISSUE TITLE
Typing deviation in getOrElse

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1045]
```
import scala.collection._
object T {
  val newSymbolMap: mutable.HashMap[String, mutable.HashMap[Int, Double]] = mutable.HashMap.empty
  val map = newSymbolMap.getOrElse("a", mutable.HashMap.empty)
  map.put(1, 0.0)
  newSymbolMap.put("a", map)
}
```
Compiles fine with scalac. Fails in dotty:
```
reproduce.scala:5: error: type mismatch:
 found   : Int(1)
 required: T.map.A
  map.put(1, 0.0)
          ^
reproduce.scala:5: error: type mismatch:
 found   : Double(0.0)
 required: T.map.B
  map.put(1, 0.0)
             ^
reproduce.scala:6: error: type mismatch:
 found   : (scala.collection.mutable.HashMap[Int, Double] |
  scala.collection.mutable.HashMap[Nothing, Nothing]
)(T.map)
 required: collection.mutable.HashMap[Int, Double]
  newSymbolMap.put("a", map)
                        ^
three warnings found
three errors found
```

This code is part of #630 and it used to compile fine.

**Comment by DarkDimius** [comment]
Specifying the type of `map: mutable.HashMap[Int, Double]` is a workaround.

**Comment by smarter** [comment]
Quick analysis:
When we do type inference for `newSymbolMap.getOrElse` we start with:
```scala
B1 >: 
("a", mutable.HashMap.empty)` at some point we end up with

**Comment by smarter** [comment]
Quick analysis which might be wrong, I haven't checked it:
When we do type inference for `newSymbolMap.getOrElse` we start with:
```scala
B1 >: scala.collection.mutable.HashMap[Int, Double]
```
where `B1` corresponds to the type parameter of `getOrElse`, then since we apply it to `("a", mutable.HashMap.empty)`, we get:
```scala
B1 >: scala.collection.mutable.HashMap[Int, Double] | scala.collection.mutable.HashMap[A, B]
A unconstrained
B unconstrained
```
where `A` and `B` are the type parameters of `HashMap.empty`.

Afterwards, [we instantiate the tvars](https://github.com/lampepfl/dotty/blob/93dd1cf1fdbf56ca3c153aa5a25fb4c48782acf5/src/dotty/tools/dotc/typer/Inferencing.scala#L210):

1. `B1` is instantiated to `scala.collection.mutable.HashMap[Int, Double] | scala.collection.mutable.HashMap[A, B]` ([the union is not approximated because it contains uninstantiated tvars](https://github.com/lampepfl/dotty/blob/93dd1cf1fdbf56ca3c153aa5a25fb4c48782acf5/src/dotty/tools/dotc/core/Types.scala#L2638-L2642))
2. `A` and `B` are instantiated to  `Nothing` because they are unconstrained

I'm not sure how to fix this right now.

**Comment by smarter** [comment]
Actually, the issue seems to be in `approximateUnion` which we do call on `scala.collection.mutable.HashMap[Int, Double] | scala.collection.mutable.HashMap[A, B]`, it should return a non-union type but it calls `baseTypeWithArgs` which calls `|` (https://github.com/lampepfl/dotty/blob/93dd1cf1fdbf56ca3c153aa5a25fb4c48782acf5/src/dotty/tools/dotc/core/TypeApplications.scala#L610-L611) and we end up back with a union type. This is the case since https://github.com/lampepfl/dotty/commit/ee76fda79d446a2d6db51cb4af032a8e92936013 which changed the behavior of `|`.

This should be easy to fix: instead of calling `|` in `baseTypeWithArgs` we should call a method that does distribute unions inside refinement types because this is what we want in this particular case.
