### ISSUE TITLE
Missing setter of exported var while using qualified name instead of wildcard

### ISSUE THREAD

**Issue by BarkingBad** [lampepfl/dotty#10512]
## Minimized code

```scala
class A:
  var varInt: Int = 1

class B:
  val a = new A
  export a.varInt
  varInt = 2 // Illegal (compile will complain: Reassignment to val varInt)
```

## However

```scala
class A:
  var varInt: Int = 1

class B:
  val a = new A
  export a._
  varInt = 2 // completely fine
```

**Comment by bishabosha** [comment]
The problem with this is now if you define an overload of `varInt_=`, and want to also export `varInt_=` overloads, such as below, what should happen?:
```scala
class A:
  var varInt: Int = 1
  def varInt_= : Unit = println("ok")

class B:
  val a = new A
  export a.varInt // exports varInt, varInt_=(x$1: Int)
  export a.varInt_=  // exports varInt_=(x$1: Int), varInt_=, causing a double definition
  varInt = 2
```

**Comment by bishabosha** [comment]
I will move this to feature requests because the present behaviour is as specified.

deferring to section 4.2 of the Scala language specification, a `var` is equivalent to two definitions, a getter and a setter.
https://scala-lang.org/files/archive/spec/2.13/04-basic-declarations-and-definitions.html#variable-declarations-and-definitions

Additionally, as specified at http://dotty.epfl.ch/docs/reference/other-new-features/export.html a simple selector, such as in `export a.varInt` will only export eligable members _with the same name_, i.e. the getter for `varInt` in this case
