### ISSUE TITLE
Clean-up scala.runtime

### ISSUE THREAD

**Issue by anatoliykmetyuk** [lampepfl/dotty#10602]
As per the stdlib review discussion we had a few weeks ago, here's what needs to be done with scala.runtime package:

- [x] Rename Tuple.scala -> Tuples.scala
- [x] Move everything from dotty.runtime to.runtime – everything move
- [ ] LazyVals: don't rely on Unsafe in Java 9 – copypaste Scala 2 stdlib code & detect usages
- [x] Remove TupledFunction
- [x] Function$ classes – investigate

**Comment by bishabosha** [comment]
should `scala.quoted.runtime` become `scala.runtime.quoted`?

**Comment by smarter** [comment]
I think either is fine.

**Comment by smarter** [comment]
The only remaining item is the usage of sun.misc.Unsafe in LazyVals, but I had a look and trying to abtract over this to use VarHandle on Java 9+ instead looks very complicated and will involve some important changes to the lazy val implementation, this is likely to be a wasted effort since we're anyway going to completely change it post-3.0 with https://github.com/lampepfl/dotty/issues/7140, so I'll be closing this and we'll have to handle this at the same time we deal with #7140.
