### ISSUE TITLE
Do we need `MatchType` in reflection API?

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#10683]

**Comment by abgruszecki** [comment]
@nicolasstucki I think we need the _type_, no? What we may decide not to include is ways to construct it.

**Comment by abgruszecki** [comment]
In the doctool, we need to deconstruct match types to show them. This includes our own extractor for elements of match type cases: https://github.com/lampepfl/dotty/blob/master/scala3doc/src/dotty/dokka/tasty/SyntheticSupport.scala#L100.

**Comment by abgruszecki** [comment]
So for clarity, what prevents the current API for constructing match types from being useful is that one cannot construct match cases without access to the special MatchCase type constructor. You can see in the code snippet I linked where the constructor is placed. If we want to expose API for creating match types, we should also have dedicated API for creating match cases.

Otherwise, match types are an experimental feature, so being able to create them in staging is not really critical for the release.

**Comment by abgruszecki** [comment]
See #10690 for a possible adjustment in reflection API.

**Comment by nicolasstucki** [comment]
These cases are already supported as explained in #10690.
