### ISSUE TITLE
Community Build test should say which tests failed

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#10787]
The community build test runs a long time with a huge log, only to say at the end that it failed in a single line.

It should state instead which community project(s) failed.

**Comment by abgruszecki** [comment]
I agree, it's definitely painful ATM to inspect what is the exact problem that made the community build fail. It'd be useful to figure out if we can somehow hook into GH Actions and display every project build as an individual action, or do something similar so that it's easier to understand what went wrong. Perhaps we could generate a summary in a test report format, and then we could publish it with an action? For instance, this action looks like it could potentially work:  https://github.com/marketplace/actions/surefire-report
