### ISSUE TITLE
Add REPL Tests

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#1086]
It would be good to have a set of tests for the REPL to guard against regressions.

**Comment by smithjessk** [comment]
I am interested in tackling this. Could you explain, on a high level, what you would like to have covered?

**Comment by retronym** [comment]
Here are some tests I recently wrote for the Scala 2.11 REPL that cover tab completion: https://github.com/scala/scala/blob/2.12.x/test/junit/scala/tools/nsc/interpreter/CompletionTest.scala

The ideas here that you might want to borrow is to write tests the drive the REPL programatically, decoupled from JLine. This has an added benefit of helping to flesh out a nice API for others who want to use the REPL.

Before getting to code completion (which isn't yet implemented in dotty's REPL) some aspects of basic REPL functionality to test might be:

 - [ ] Defining methods, classes, type aliases, modules. Multiple definitions per line are allowed. Ensure defined names are available on subsequent lines, and shadow previous definitions of the same name.
 - [ ] Imports bring names into scope of subsequent lines. `> import A.B; > import A.B; >B` is *not* ambiguous. Imports bring implicits into scope as expected. Also test wildcard and renaming imports.
 - [ ] Erroneous code: are warnings and errors rendered appropriately (e.g. the `^` points to the right spot in the snippet of displayed code?
 - [ ] Code execution: is the context classloader set appropriately during execution of user code? Are exceptions caught and displayed
 - [ ] Are the `$iw` synthetic wrappers hidden in error messages and other output? (Ideally, we could design the REPL so that these aren't necessary)
 - [ ] Survey the REPL tests in scala/scala for bugs that have cropped up previously, test for these.

**Comment by odersky** [comment]
Thanks for offering to help Jess, and also thanks to Jason for giving these
starting points!

I only have one thing to add: Our current check in test suite is run from

   dotty/test/dotc/tests.scala

So that's where REPL tests should eventually be integrated when they are
ready.



On Thu, Feb 25, 2016 at 5:47 AM, Jason Zaugg <notifications@github.com>
wrote:

> Here are some tests I recently wrote for the Scala 2.11 REPL that cover
> tab completion:
> https://github.com/scala/scala/blob/2.12.x/test/junit/scala/tools/nsc/interpreter/CompletionTest.scala
>
> The ideas here that you might want to borrow is to write tests the drive
> the REPL programatically, decoupled from JLine. This has an added benefit
> of helping to flesh out a nice API for others who want to use the REPL.
>
> Before getting to code completion (which isn't yet implemented in dotty's
> REPL) some aspects of basic REPL functionality to test might be:
>
>    - Defining methods, classes, type aliases, modules. Multiple
>    definitions per line are allowed. Ensure defined names are available on
>    subsequent lines, and shadow previous definitions of the same name.
>    - Imports bring names into scope of subsequent lines. > import A.B; >
>    import A.B; >B is *not* ambiguous. Imports bring implicits into scope
>    as expected. Also test wildcard and renaming imports.
>    - Erroneous code: are warnings and errors rendered appropriately (e.g.
>    the ^ points to the right spot in the snippet of displayed code?
>    - Code execution: is the context classloader set appropriately during
>    execution of user code? Are exceptions caught and displayed
>    - Are the $iw synthetic wrappers hidden in error messages and other
>    output? (Ideally, we could design the REPL so that these aren't necessary)
>    - Survey the REPL tests in scala/scala for bugs that have cropped up
>    previously, test for these.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/issues/1086#issuecomment-188613790>.
>



-- 
Martin Odersky
EPFL

**Comment by smithjessk** [comment]
Awesome/ I'll fork Dotty and get started on these. I'll put in a PR when I have them done.
