### ISSUE TITLE
Mirror.Sum not synthesised for base class without companion

### ISSUE THREAD

**Issue by jtjeferreira** [lampepfl/dotty#10997]
## Minimized code

```Scala
class Test {
  sealed trait Role
  case object Admin extends Role
  case class Contributor(organization: String) extends Role
  
  println(summon[Mirror.Of[Role]])
}
```

## Output

```scala
// no implicit argument of type deriving.Mirror.Of[Test.this.Role] was found for parameter x of method summon in object Predef
```

## Expectation

It should be able to derive the mirror as if it was inside the companion object.

```scala
object Test {
  sealed trait Role
  case object Admin extends Role
  case class Contributor(organization: String) extends Role
  
  println(summon[Mirror.Of[Role]])
}
```

I found this while I was port play-json to dotty (https://github.com/playframework/play-json/pull/555/files).

**Comment by jtjeferreira** [comment]
If this is not considered a bug, at least would be nice to have a better error message explaining this is a nested class

**Comment by bishabosha** [comment]
I investigated by printing the internal reporting and the reason given for not generating a mirror is that `its child object Admin is not accessible within its owner class Test`.

This accessibility test is defined as the child being contained within the companion of `Role`.

So the example can be fixed by instead defining the child cases within a companion object, such as this:
```scala
class Test {
  sealed trait Role
  object Role {
    case object Admin extends Role
    case class Contributor(organization: String) extends Role
  }
  
  println(summon[deriving.Mirror.Of[Role]])
}
```
I will update with why changing `Test` to an object is also a fix

**Comment by bishabosha** [comment]
changing `Test` to an object is also a fix because the accessibility test also works if the sealed child is defined in an `object` and either that object contains the companion of `Role` or recursively check this against the owner of that object:

https://github.com/lampepfl/dotty/blob/2be0707cae91bc394338676cd6fdad48af148d31/compiler/src/dotty/tools/dotc/transform/SymUtils.scala#L105

Basically, I think it could be a bug that the case where `Test` is an object works because it is a fluke that the owner of the root package is the empty symbol and the the companion of `Role` is also the empty symbol, so the accessibility test will pass.

**Comment by bishabosha** [comment]
Essentially I believe that the design is meant to be that `deriving.Mirror.Sum` is only generated for cases that look like this:
```scala
sealed trait Foo
object Foo {
  case object Bar extends Foo
  case class Baz(i: Int) extends Foo
} 
```

and any deviation from that is a bug

**Comment by bishabosha** [comment]
Ok right yes that would make sense, so only defining the companion object is required:
```scala
class Test {
  sealed trait Role
  case object Admin extends Role
  case class Contributor(organization: String) extends Role
  object Role
  
  println(summon[deriving.Mirror.Of[Role]])
}
```

because `object Role` is now defined, its owner `class Test` is also the owner of `object Admin` and `class Contributor`

**Comment by jtjeferreira** [comment]
oh thats a very nice workaround. should we close this? or should this be fixed? maybe there is a way that the compiler could generate the companion object behind the scenes?

**Comment by bishabosha** [comment]
In my opinion, based on the test cases in #6531, it is a bug that `Mirror.Sum` can be summoned when the companion object does not exist

**Comment by bishabosha** [comment]
One reason this may have gone unnoticed for so long is that using a `derives` clause will cause a companion object to be generated if one does not exist. But certainly you may want to use a `Mirror` outside of derivation purposes

**Comment by bishabosha** [comment]
tests https://github.com/lampepfl/dotty/blob/master/tests/run/deriving.scala and https://github.com/lampepfl/dotty/blob/master/tests/run/deriving-constructor-order.scala

work on the assumption that a companion is not required, which makes the motivation for this accessible from companion test confusing

**Comment by bishabosha** [comment]
I have found this commit: https://github.com/lampepfl/dotty/commit/275a0a96bdb1f28300ca8e0f045226e1e99b3df1 i.e. the message is "Generate sum mirrors for sealed traits that do not have a companion"

so it would seem pretty clear that it is infact the original code example which is a bug:
```scala
class Test {
  sealed trait Role
  case object Admin extends Role
  case class Contributor(organization: String) extends Role
  
  println(summon[Mirror.Of[Role]]) // should be able to find the Mirror but can't
}
```
