### ISSUE TITLE
nested named irrefutable typetest pattern causes exhaustivity warning

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#10994]
## Minimized code

```Scala
def foo = true match
  case (b: Boolean): Boolean => ()
```

## Output

```scala
-- [E029] Pattern Match Exhaustivity Warning: sandbox/match/example.scala:1:10 -
1 |def foo = true match
  |          ^^^^
  |          match may not be exhaustive.
  |
  |          It would fail on pattern case: true, false

```

## Expectation

no warning.

the wildcard case produces no warning:
```scala
def foo = true match
  case (_: Boolean): Boolean => ()
```

**Comment by liufengyun** [comment]
It seems Scala 2 syntax does not support this and it's not in the Scala 3 language specification. Maybe we can disallow it in Scala 3 as well.

**Comment by bishabosha** [comment]
I have seen some code use this in the wild but I'm not sure what made it necessary

**Comment by abgruszecki** [comment]
I'd also be in favour of (at least temporarily) disallowing this in Scala3, since it apparently causes extra difficulties in the compiler. It's always possible to define a "fork" pattern which allows simultaneously matching one value against two patterns, so there's no real loss of functionality from forbidding this syntax.
