### ISSUE TITLE
Dotty site is down

### ISSUE THREAD

**Issue by hmf** [lampepfl/dotty#11134]
Hope I am not abusing this issue tracker but, the site:

https://dotty.epfl.ch

seems to be down.

**Comment by aumann** [comment]
Working for me, maybe just a short downtime?

**Comment by nicolasstucki** [comment]
Working for me too

**Comment by hmf** [comment]
Working now. Must have been on my side. Sorry.

**Comment by griggt** [comment]
dotty.epfl.ch seems to be down again

```
curl: (7) Failed to connect to dotty.epfl.ch port 443: Connection timed out
```

This is impacting builds that use `dottyLatestNightlyBuild` provided by `sbt-dotty`, as that attempts to fetch https://dotty.epfl.ch/versions/latest-nightly-base

I noticed this due to a CI failure: shapeless in the community build includes `dottyLatestNightlyBuild.get` in its `crossScalaVersions`

**Comment by Swoorup** [comment]
Here in my garage, it's down.
