### ISSUE TITLE
Wrong setup og "JLINE_TERMINAL*" in common / scalac shell scripts

### ISSUE THREAD

**Issue by flomebul** [lampepfl/dotty#11171]
When launching "scala" under cygwin, the output is
```
$ scala
Starting scala3 REPL...
←[?1h←=←[90m~←[0m
←[?2004h←[34mscala> ←[0m:quit
:quit
←[?1l←>←[?1000l←[?2004lLuc@Mulan ~
$
```

This is due to an incomplete setup of the "JLINE_TERMINAL"
The "jna-5.3.1.jar" library must be added to the "*jline-terminal-jna-3*" library

**Comment by michelou** [comment]
@flomebul You can find the JNA setup I use on MS Windows (Cygwin or Windows console) for over two years (since Dotty 0.9) in the batch file [`common.bat`](https://github.com/michelou/dotty-examples/blob/master/bin/3.0.0/common.bat) (lines 51-54).

The above file is called from the batch files [`scala.bat`](https://github.com/michelou/dotty-examples/tree/master/bin/3.0.0/scala.bat), [`scalac.bat`](https://github.com/michelou/dotty-examples/tree/master/bin/3.0.0/scalac.bat) and [`scalad.bat`](https://github.com/michelou/dotty-examples/tree/master/bin/3.0.0/scalad.bat) which are the commands to be run by a Scala 3 user.

**PS.** For more information see my GitHub project [`dotty-examples`](https://github.com/michelou/dotty-examples).

**Comment by flomebul** [comment]
@michelou I agree. I already have apply these update around "JNA" variable in my cygwin  environment.
If I can, I can propose a PR.
