### ISSUE TITLE
Should we forbid empty intersection types?

### ISSUE THREAD

**Issue by hepin1989** [lampepfl/dotty#11182]
## Minimized code

```Scala
scala> type IntAndString = Int & String
// defined alias type IntAndString = Int & String

scala> def add(param:IntAndString):IntAndString = param
def add(param: IntAndString): IntAndString
```

## Output

```scala
def add(param: IntAndString): IntAndString
```

## Expectation
should we forbid this?

**Comment by smarter** [comment]
No:
- In general, we cannot know if an intersection `A & B` is empty or not
- An empty type is not invalid, otherwise we couldn't write `Nothing`
- When doing type-level computations, especially with match types, one might end up generating empty types via intersections intentionally, forbidding that might make it harder to do these computations.
