### ISSUE TITLE
Incorrectly renderred signature for parameterless method in error message reporting unimplemented method

### ISSUE THREAD

**Issue by marcinzh** [lampepfl/dotty#11201]
## Compiler version

3.0.0-RC1-bin-20210117-65b17af-NIGHTLY

## Minimized code

```Scala
trait Foo:
  def foo: Int
  def foo2: Int // optionally one more, to trigger Dotty to propose stubs

class Bar extends Foo
```

## Output

<details>

```scala
class Bar extends Foo
      ^
      class Bar needs to be abstract, since:
      it has 2 unimplemented members.
      /** As seen from class Bar, the missing signatures are as follows.
       *  For convenience, these are usable as stub implementations.
       */
        def foo: => Int = ???
        def foo2: => Int = ???
```
</details>

## Expectation

The method signature printed in error message & proposed stub should be: 
```scala
foo: Int
```
instead of:
```scala
foo: => Int
```

**Comment by wg-romank** [comment]
Hi,

I'm quite new to this codebase but I would like to try helping with this one.
Would it be okay?

**Comment by wg-romank** [comment]
I checked a bit, and so far based on my understanding this could be fixed by handling additional case in `PlainPrinter.scala`.
Currently when calling `showDcl` for parameterless method we match onto this case
https://github.com/lampepfl/dotty/blob/b023ec85c7e44dd393394809df6f31e43f3fcf97/compiler/src/dotty/tools/dotc/printing/PlainPrinter.scala#L402
Since parameterless method has info of type `ExprType` instead of `MethodType` stubs signatures are not correct.

What I'm not sure about is whether the denotation process should handle parameterless methods differently (to assign them `MethodType` instead of `ExprType`) and if there are any other implications due to that.

Please kindly advice on the direction. Thank you.

**Comment by smarter** [comment]
> What I'm not sure about is whether the denotation process should handle parameterless methods differently (to assign them MethodType instead of ExprType) and if there are any other implications due to that.

No, using ExprType makes a difference, `def foo: Int` is an `ExprType` whose resultType is  a TypeRef of `Int` whereas `def foo(): Int`  is a `MethodType` whose parameter list is `Nil` and `resultType` is a TypeRef of `Int`.

Feel free to experiment with changes to the printer to improve the output here, but note that ExprType is also used for by-name parameters (for example in `def foo(x: => String): Int`, the type of `x` is an `ExprType`), so for those the `=> ` needs to be preserved in the printed output.

**Comment by smarter** [comment]
You can't really recover this information from Context, instead you need to avoid loosing it somehow, maybe by adding an `isTopLevel` boolean parameter to toTextRHS and making sure it's set to false when called from `paramsText`.

**Comment by wg-romank** [comment]
Hi @smarter could you please help me to re-open the PR? I've fixed test case failures (sorry it took long time). I tried to get in touch with Oliver but did not get any reply and it's been almost a month. Thanks!

**Comment by wg-romank** [comment]
Thanks, I've created a new PR (https://github.com/lampepfl/dotty/pull/12934) but seems I would need approval from maintainer to run workflows.
