### ISSUE TITLE
Seq is too specific for varargs

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#11281]
`scala.collection.immutable.Seq` is uncomfortably specific as the type of a vararg argument. 

 - it ties Scala runtime to a large Scala collection type. It would be better if the two were uncoupled.
 - It forces wrapping of arrays as sequences, which is inefficient
 - It means we need separate conventions for Java varargs, which are arrays, and Scala varargs, which are sequences.

I think it would be better to hide the actual representation of what a vararg is. This would give us the freedom to choose a more regular and efficient representation later, e.g. as an immutable array.

## Idea

Define a new type, `scala.VarArg` that represents the internal view of a vararg parameter. `VarArg` gets all operations from immutable Seq; it behaves essentially like an immutable array. To maintain backwards compatibility, there is an implicit conversion from `VarArg[T]` to `immutable.Seq[T]`, but that conversion is deprecated. The deprecation message says that one should use an explicit conversion like `_.toSeq` instead.

With opaque types we have the necessary machinery to express this. I.e.
```scala
package scala.collection.immutable

opaque type VarArg[+T] = Seq[T]
implicit class VarArgOps(x: VarArg[T]) extends AnyVal {
  ...
}
@deprecated("implicit conversion from `VarArg to `Seq` is deprecated, use explicit `.toSeq` instead.")
implicit def varArgToSeq[T](xs: VarArg[T]: Seq[T]) = xs
```
and
```scala
package scala
type VarArg[+T] = scala.collection.immutable.VarArg[T]
```

## Questions:

 - Is `VarArg` the best name? What are possible alternatives?
 - `VarArg` is defined in `scala.collection.immutable` with an alias in `scala`. Is that how it should be?

## Downsides

 - Some code will have to be adapted
 - Once we change the `VarArg` representation to `IArray`, the `varArgToSeq` conversion will create a (lightweight) wrapper object on each access to a `vararg`, which could negatively impact performance. I believe we should outlaw the implicit conversion `varArgToSeq` before we do that step, so that it's out in the open. Once developers have to write `toSeq` explicitly, they will hoist it out of inner loops.
 
## Timing

It affects the books -- every text book has to explain that varargs are `Seq`s and will consequently be wrong once we do the change. So I think it is best to try to do this now.

**Comment by sjrd** [comment]
Pinging
* @Ichoran for the performance concerns (I think I remember you were quite active on that topic for the 2.13 change in varargs)
* @bishabosha for the TASTy Reader concerns

---

The proposal does not address call sites, when we have an `s: Seq[T]` at hand and we do `s: _*` (or whatever's the syntax for call site expansion of a Seq into varargs).

---

This should have a Contributors thread.

**Comment by odersky** [comment]
Callsites stay as they are, for now. That is, we pass a Seq. 

In the future, we have basically two options:

 - Change to pass an `IArray` instead of a `Seq`. Then we have to change also the meaning of `xs*` so that it creates an `IArray` instead of a `Seq`.
 - Pass an `IArray` for explicit varargs and for `ia*` where `ia` is already an array. If `xs` is a `Seq`, pass `xs*` unchanged. Then `type VarArgs = IArray[A] | Seq[A]` and we have to sort out the difference in the operations on the `VarArgs` type.
 -

**Comment by smarter** [comment]
> I think it would be better to hide the actual representation of what a vararg is. This would give us the freedom to choose a more regular and efficient representation later, e.g. as an immutable array.

Setting aside how this is likely to immensely complicate Scala 2<->3 interop, even if `IArray` is an opaque type, we cannot change its representation in a later release without breaking binary compatibility, so this isn't something that could be done before Scala 3.T/4, at which point we can afford to change the public type anyway. The only alternative I can think of is to introduce new syntax for varargs (e.g., `T...` as was proposed on contributors at some point) which could have whatever semantics we want, while keeping "old-style varargs" as they currently are. In either case, this isn't something that would need to be tackled for Scala 3.0.

**Comment by odersky** [comment]
@smarter Yes, we probably can complete the changes to representation only when we change binary compatibility. I think that's OK, we keep using `Seq` in the meantime. 

By contrast a new syntax would take a lot longer (not to implement but to wait until we can put it in). Quite likely, there would never be a time where we can do it.

**Comment by sjrd** [comment]
> Callsites stay as they are, for now. That is, we pass a Seq.

When the representation changes, that will not be possible anymore. Do either you'll silently copy into the new representation (bad since it's a silent performance regression) or you warn that there is a copy and you tell the user to use something else. In that case, it's like the definition site: you have to deprecate earlier in order to nudge people to the right replacement.

Moreover, what *will* that replacement be? Currently, all collections can be converted into varargs in constant time, with a constant allocation cost. If the representation changes, this won't be the case anymore. All of these issues should be addressed now, or at least have a plan on how to address them, otherwise the change here will be for nothing.

**Comment by odersky** [comment]
@sjrd Suggestions are very welcome, and I have already outlined two alternatives, one of which would address your concern. But please, let's engage in technical debate instead of obstructionism. With an attitude like this we would never have been able to change varargs to `immutable.Seq`. Yet, it happened...

**Comment by odersky** [comment]
Yes, it's not clear we would be able to do better here. Current situation:

 - when passing to Java varargs: produce an array, or convert sequence to array
 - when passing to Scala varargs: produce a wrapped array, or leave sequence as is
 - access to T* from a Scala method is always a sequence operation

If we have a mixed representation:

 - when passing to Scala varargs: produce an array, or leave sequence as is
 - access to T* distinguishes between arrays and sequences with a type test

It's not clear which scheme is better overall. The mixed representation does one boxing less per application but
is probably slower for each access. 

So I think overall, it does not look like it's worthwhile to change.

**Comment by odersky** [comment]
The mixed representation would have one (maybe important?) benefit, though: Scala vararg methods could be called from Java.

**Comment by sjrd** [comment]
> The mixed representation would have one (maybe important?) benefit, though: Scala vararg methods could be called from Java.

Not as varargs, since the erased parameter type would be `Object` and not `Array[Something]` as required a Java varargs method. So we would still need `@varargs` to have a bridge that takes an `Array[Something]`.

It would be slightly "easier" to call with an explicit array initializer at call site, but at the cost of type safety (since we could also just pass whatever, the type being `Object`).

**Comment by odersky** [comment]
Yes, and in fact an erased representation of `Object` would be very slow anyway. So, it seems this won't work, and `Seq` is still the best representation. 

This means the only reason to "opaquify" `Seq` would be to disentangle language spec and collection library. But maybe the better approach would be to make the `Seq` type more lightweight by moving more stuff into extension methods. That would mean we'd keep `scala.Seq` in the language spec, but we compile a shortlist of methods that any conforming Scala implementation has to provide for it. Anyway, all this is definitely for later, probably for the next time we redesign the library.

**Comment by Ichoran** [comment]
As far as performance goes, silently allowing `Seq` vs `VarArg` wouldn't matter very much, because the big differences are in the operations, not in different allocations.

So it would be valuable for performance to be able to interpret `def foo(xs: IArray[Bar])` as varargs, because then you could provide a specialized high-speed implementation (and call it from Java, and skip an allocation on the way in when you were calling it directly rather than passing on the varargs from somewhere else).  But it would not be particularly valuable to be able to pass either an `IArray` or a `Seq` into `def foo(xs: Bar*)`.

**Comment by odersky** [comment]
Yes, but what about `def foo[T](xs: T*)`. That would take an Object and have to go through reflection. How much would that usecase matter?

**Comment by Ichoran** [comment]
> Yes, but what about `def foo[T](xs: T*)`. That would take an Object and have to go through reflection. How much would that usecase matter?

That would matter a lot, except that isn't even possible because you don't have any operations on `Array` (IIRC, `IArray` is just an opaquely typed `Array` anyway, right?  So no extra operations.)

So what it'd really have to be is (hardcoded) match to a collection/typeclass pair, and that wouldn't add very much time.

```scala
def foo(xs: Bar*) = {
  implicit val ops: VarArgOps[Bar, xs.type] = xs match {
    case _: Array[Bar] => VarArgArrayOps[Bar]
    case _                   => VarArgSeqOps[Bar]
  }
  // Actual code here
}
```

Something like that (Scala 2 notation).  Then dispatch on the Ops object would take care of it instead of reflection.
