### ISSUE TITLE
Should inline matches strip type ascription?

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#11291]
## Compiler version

3.0.0.M3

## Minimized example

```Scala
inline def meth =
  inline ("a": Any) match
    case _: String => "ok"

def test = meth
```

## Output

```scala
-- Error: Foo.scala:6:11 -------------------------------------------------------
6 |def test = meth
  |           ^^^^
  |           cannot reduce inline match with
  |            scrutinee:  "a":Any : Any
  |            patterns :  case _:String
  | This location contains code that was inlined from Foo.scala:3
```

## Expectation
Should this code compile? It looks like it should. Not sure if there are use-cases where we would want to avoid this.

**Comment by nicolasstucki** [comment]
@odersky @OlivierBlanvillain WDYT?

**Comment by abgruszecki** [comment]
I think at one point we discussed that inline matches should try to re-type their scrutinees as accurately as possible before matching. Stripping type ascriptions seems to be a part of that.

**Comment by nicolasstucki** [comment]
We do retype the scrutinee. But as the ascription is not removed/ignored the type will not get more precise.

**Comment by odersky** [comment]
Note sure. Is there a reason why one would need to add `: Any` to the scrutinee?

**Comment by abgruszecki** [comment]
A type ascription could prevent a `case` from matching, so that's one usage. At the same time, one should be able to use `.asInstanceOf` to accomplish the same. I'd say that the usefulness of stripping type ascriptions is more important than being able to prevent a `case` from matching. For instance, one may add a type ascription to the value returned by one `inline`, and I wouldn't expect that to alter how a different `inline` reduces.
