### ISSUE TITLE
Problem with terminal's command promt after execution of scala scripts

### ISSUE THREAD

**Issue by BarkingBad** [lampepfl/dotty#11536]
## Compiler version

Scala compiler version 3.0.0-RC2-bin-SNAPSHOT-git-c037293 -- Copyright 2002-2021, LAMP/EPFL

Execution of scripts like /bin/scalac or /bin/scaladoc breaks the terminal, command prompt is not in new line position and typing is invisible

Operating system:
Description:    Ubuntu 20.04.1 LTS
Release:        20.04

I am using default bash terminal.

@philwalk could you take a look, as it seems problem exists since your recent changes. Thanks in advance :D 

![obraz](https://user-images.githubusercontent.com/32793002/109142718-7d235c80-775f-11eb-9790-f0294d78376c.png)

**Comment by michelou** [comment]
I encountered the same issue (aka "typing is invisible") with the MinGW shell prompt (on MS Windows).

**Comment by philwalk** [comment]
I was able to reproduce the problem on Ubuntu release 18.04.1  ... looking into it.

**Comment by philwalk** [comment]
I have a probable fix, but I need to verify that it works with all environments.

**Comment by philwalk** [comment]
It turns out that manual REPL tests that have to be performed for 4 terminals over 4 windows shell environments:

Terminals:

- cmd
- mintty
- conemu
- windows terminal

Windows Shell environments:
- MINGW32_NT-10.0-19042 d5 3.1.7-340.x86_64 2020-11-08 12:32 UTC x86_64 Msys
- MINGW64_NT-10.0-19042 d5 3.1.7-340.x86_64 2020-11-08 12:32 UTC x86_64 Msys
- MSYS_NT-10.0-19042 d5 3.1.7-340.x86_64 2020-11-08 12:32 UTC x86_64 Msys
- CYGWIN_NT-10.0 d5 3.1.7(0.340/5/3) 2020-08-22 17:48 x86_64 Cygwin

In addition, I'm currently able to do manual REPL tests on these Linux Environments:
Linux d5 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Linux quadd 5.4.0-62-generic #70~18.04.1-Ubuntu SMP Tue Jan 12 17:18:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

We should also test OSX/Darwin as well (not currently able to do so myself).

That's a total of 19 environments.
There might also be a need to test X-windows ssh sessions.

I Will push a working fix soon, hopefully.

**Comment by michelou** [comment]
@philwalk Thanks for the detailed feedback.
