### ISSUE TITLE
Weird behaviour when attempting partial application with named argument method.

### ISSUE THREAD

**Issue by megri** [lampepfl/dotty#11561]
## Compiler version
3.0.0-RC1

## Minimized code

```Scala
case class State(text: String):
// val updateText = copy(text = _) // Missing parameter type: I could not infer the type of the parameter _$1
  val updateText = copy(text = (_: String))
```
scastie: https://scastie.scala-lang.org/a93h61tfRaeBBCqslsQgkg
## Output

```scala
[error] -- [E052] Type Error: /<redacted>/State.scala:4:29
[error] 4 |  val updateText = copy(text = (_: String))
[error]   |                        ^^^^^^^^^^^^^^^^^^
[error]   |                        Reassignment to val text
[error] one error found
[error] one error found
```

## Expectation
I'd expect this to work, but in case it is difficult to support partial application and named default arguments I'd like to see a more specific error message. In any case the parser should not see this as a reassignment in the context of a method call.

**Comment by som-snytt** [comment]
Scala 3 does already disallow "parenthetical assignment"
```
  var y = 42
  def f() = Future(y = 27)  // no
```
Scala 3 also allows
```
@deprecated(since="1.0") def f = 42
```
because it doesn't follow the Scala 2 spec for named/default args, where evaluation order is defined as actual args then defaults, rewritten to a block of vals. Instead, the application is rewritten "in place", which is the condition for expecting placeholder syntax to work, as well as for that deprecation to work without complaining.
```
def x() = ??? ; def y() = ???
def f(i: Int = x(), j: Int = 42) = i + j
f(j = y())  // y then x in scala 2, x then y in scala 3
```
For that case, should `f(j = _)` be `x$1 => f(x(), x$1)` or `x$1 => { val x$2 = x$1 ; val z$1 = x() ; f(z$1, x$2)`
or even `{ val z$1 = x() ; x$1 => f(z$1, x$1)` where the default is evaluated once.

Syntactically, the placeholder is bound to the named assignment Expr, `j = _`, so `f(x$1 => { j = x$1 })`.

**Comment by megri** [comment]
Well, there are no intentional assignments in my expression at least. So, where I get confused is in the syntactic department: The fact that `copy(_)` expands to `x$1 => copy(x$1)`, while `copy(text = _)` expands to `copy(x$1 => { test = x$1})`, is really surprising to me.

I could probably find the reason for this if I read the language spec and sorted out parsing priorities and such, but as I am entering my expression I am first told that I need to specify the type of x$1, and then that I can't reassign the `text` value.

If the parsing rules are unambiguous and working as expected I think it would be clearer with an error message like
```
method `copy(text: String = this.text)` expected an expression of String but got `x$1 => { test = x$1}`
here: copy(x$1 => { test = x$1})
           ^^^^^^^^^^^^^^^^^^^^
```

**Comment by som-snytt** [comment]
My previous comment in the middle of the night wasn't clear that I don't disagree with the intuition that it should just work.

I saw (because I had to look) that the spec isn't clear about the syntax here. (There is no special production for named arg.)

Probably it could be made to work. The confusion around assignment syntax is just "for historical reasons."

**Comment by odersky** [comment]
> 
```
method `copy(text: String = this.text)` expected an expression of String but got `x$1 => { test = x$1}`
here: copy(x$1 => { test = x$1})
           ^^^^^^^^^^^^^^^^^^^^
```
It can't possibly say that.

 1. It does not in fact expect an expression of String. 
 2. It cannot figure out that the expansion is not a string, since the expansion fails to typecheck.

**Comment by odersky** [comment]
The most effective rule to follow is: when surprised by an error message affecting an expression with `_`, try to expand as a lambda and try again.
