### ISSUE TITLE
Two structural methods with same signature are merged to one

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#11566]
## Compiler version

3.0.0-RC1

## Minimized code

```Scala
import reflect.Selectable.reflectiveSelectable

trait Box[A]

object Foo {
  val foo: (Box[Seq[Double]] { def append(as: Seq[Seq[Double]]): Unit }) { def append(as: Seq[Double]): Unit } = ???
  foo.append(Seq.empty[Double])
  foo.append(Seq.empty[Seq[Double]])
}
```

## Output

```scala
-- [E007] Type Mismatch Error: tests/pos-tmp/i9050.scala:8:22 ------------------
8 |  foo.append(Seq.empty[Seq[Double]])
  |             ^^^^^^^^^^^^^^^^^^^^^^
  |             Found:    Seq[Seq[Double]]
  |             Required: Seq[Double]
1 error found
```

## Expectation

an error about ambiguous overloads

**Comment by odersky** [comment]
It's not an overload since both refinements have the same erasure. I think these are quite untypical corner cases The morale should be: don't use overloaded refinements; they won't work and will give you a range of errors. I also don't see  a good way to improve the implementation. So I am closing this. If someone has an idea how to do better and is willing to work on it, please reopen.
