### ISSUE TITLE
Redundant end markers

### ISSUE THREAD

**Issue by sake92** [lampepfl/dotty#11581]
## Compiler version
3.0.0-RC1

## Minimized code

```Scala
class Abc {
}
end Abc
end Abc
```

## Output

Compiles.

## Expectation
Does not compile.  
First `end Abc` is redundant since definition of `Abc` is closed with braces.  
Then I added another `end Abc` and it compiles too...

**Comment by nicolasstucki** [comment]
This should also not be allowed
```scala
class Abc {
}
end Abc
```

**Comment by som-snytt** [comment]
Docs say: "Braces are not much better since a brace by itself also contains no information about what region is closed."

An end marker is not redundant with right brace, even where the brace is a template body and not a block.

```
def f = {
  42
}
end f
```
Here it's clear that the end marker is not redundant because "we opted for optional braces".
```
def debug = println {
  42
}
end debug
```
I suggest moving the doc for end marker out of "optional braces" and into "optional line comment saying where something ends". Because really the feature replaces:
```
def f = {
   // long body
} // end f
```
Real-world example `} // end checkAllOverrides`.

FSR I loathe the comment but love the end marker. (Perhaps because the comment means: I know this method is too big, so good luck trying to refactor it. End marker means: this method is bigger than a simple expression, thanks for reading my code.)

Someone should start a thread on contributors forum as to whether there is a use case for redundant `end`.
```
end checkAllOverrides // should be over by now, adding this to make sure because a merge conflict broke my change
```
Easy use case for checking end marker is that more than one symbol may be in play.
```
scala> def f =
     |   def f =
     |     println("inner")
     |     42
     |   println("outer")
     |   f
     | end f
def f: Int
```

**Comment by Kordyjan** [comment]
I've created PR solving the issue with multiple consecutive end markers. It is not touching anything related to the question if an end marker should be allowed after a right brace. Personally, I would love to be able to write something like this:
```scala
class A {
    def a = ???
} end A
```
It is much better than comment, as it is checked by the compiler. Nevertheless, it is probably much too late for a change like this.
