### ISSUE TITLE
Wildcard type constructor parameter not inferred correctly

### ISSUE THREAD

**Issue by alexfoxgill** [lampepfl/dotty#11663]
## Compiler version

3.0.0.RC-1

## Minimized code

```Scala
def test[F[_]] ={
  def useF[T](arg: F[T]): Unit = ???
  def getF(): F[_] = ???
  def bork = {
    val f = getF()
    useF(f)
  }
}
```

## Output

Compiler error:

```scala
Found:    (f : F[?])
Required: F[T]

where:    F is a type in method test with bounds <: [_$1] =>> Any
          T is a type variable
```

## Expectation
The code should compile (as it does in 2.13)

**Comment by odersky** [comment]
It's unfortunately unclear whether this is fixable. The example works if I replace the `F` parameter by a concrete class.
```scala
class F[T]

def test = {
  def useF[T](arg: F[T]): Unit = ???
  def getF(): F[_] = ???
  def bork = {
    val f = getF()
    useF(f)
  }
}
```
That gives the following expansion after typer:
```scala
package <empty> {
  class F[T >: Nothing <: Any]() extends Object() {
    T
  }
  final lazy module val test$package: test$package$ = new test$package$()
  final module class test$package$() extends Object() { 
    this: test$package.type =>
    def test[G[_$1 >: Nothing <: Any] >: Nothing <: Any]: Unit = 
      {
        def useF[T >: Nothing <: Any](arg: F[T]): Unit = ???
        def getF(): F[? >: Nothing <: Any] = ???
        def bork: Unit = 
          {
            val f: F[?] = getF()
            useF[f.T](f)
          }
        ()
      }
  }
}
```
Note the last code line: `useF[f.T](f)`. The parameter passed to `useF` is `f.T`! That type cannot be written in source, but the compiler can nevertheless model it since type parameters of classes have a dual view as members of classes. So it can pretend that this is a dependent type. But if `F` is a type parameter no such trick is possible.

In Scala 2, this idiom was modelled using existential types, but these have gone away in Scala 3. 

As a mitigation, you should try to avoid wildcard types like this if you need to recover the type parameter later. Try to thread through the actual type parameter. somehow.
