### ISSUE TITLE
Weird macro recursive inline limit infinite loop bug/crash

### ISSUE THREAD

**Issue by Swoorup** [lampepfl/dotty#11730]
Maximal number of successive inlines exceeds when using Scala 3 Macros across various dependent files.

## Compiler version

3.0.0-RC1

## Minimized code

Please see attached sample zipped project. This issue only appears to surface when having definitions across multiple files. I currently found 3 workaround so far, but the underlying issue remains.
1. If you either omit `Transactions.scala` and remove its reference, property in `Chain.scala`, 
2. Change Transaction to use derive instead, like 
	```scala
	case class Transaction( sender: Address, 
	                        recipient: Address, 
	                        value: Long) derives Codec.AsObject
	```
3. Group all the definitions in a single file as in [here](https://scastie.scala-lang.org/LBAbOJMVT1260OKUnBXuzw), it works too.

[MacroBug.zip](https://github.com/lampepfl/dotty/files/6135917/MacroBug.zip)

To Reproduce: 

1. Unzip the file.
2. Run `sbt run` in the directory.

## Output

<details>
<summary>Without default flags</summary>

```scala
[error] -- Error: /Users/swoorup.joshi/IdeaProjects/temp/LBAbOJMVT1260OKUnBXuzw/src/main/scala/blockchain/Chain.scala:25:27
[error] 25 |given Encoder[ChainLink] = deriveEncoder[ChainLink]
[error]    |                           ^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |                     Maximal number of successive inlines (32) exceeded,
[error]    |                     Maybe this is caused by a recursive inline method?
[error]    |                     You can use -Xmax-inlines to change the limit.
[error]    | This location contains code that was inlined from Chain.scala:25
[error]    | This location contains code that was inlined from Derivation.scala:47
[error]    | This location contains code that was inlined from Derivation.scala:16
[error]    | This location contains code that was inlined from Derivation.scala:38
[error]    | This location contains code that was inlined from Derivation.scala:12
[error]    | This location contains code that was inlined from Derivation.scala:50
[error]    | This location contains code that was inlined from Derivation.scala:16
[error]    | This location contains code that was inlined from Derivation.scala:38
[error]    | This location contains code that was inlined from Derivation.scala:38
[error]    | This location contains code that was inlined from Derivation.scala:12
[error]    | This location contains code that was inlined from Derivation.scala:50
[error]    | This location contains code that was inlined from Derivation.scala:16
[error]    | This location contains code that was inlined from Derivation.scala:38
[error]    | This location contains code that was inlined from Derivation.scala:12
[error]    | This location contains code that was inlined from Derivation.scala:50
[error]    | This location contains code that was inlined from Derivation.scala:16
[error]    | This location contains code that was inlined from Derivation.scala:38
[error]    | This location contains code that was inlined from Derivation.scala:38
[error]    | This location contains code that was inlined from Derivation.scala:12
[error]    | This location contains code that was inlined from Derivation.scala:50
[error]    | This location contains code that was inlined from Derivation.scala:16
[error]    | This location contains code that was inlined from Derivation.scala:38
[error]    | This location contains code that was inlined from Derivation.scala:12
[error]    | This location contains code that was inlined from Derivation.scala:50
[error]    | This location contains code that was inlined from Derivation.scala:16
[error]    | This location contains code that was inlined from Derivation.scala:38
[error]    | This location contains code that was inlined from Derivation.scala:38
[error]    | This location contains code that was inlined from Derivation.scala:38
[error]    | This location contains code that was inlined from Derivation.scala:38
[error]    | This location contains code that was inlined from Derivation.scala:12
[error]    | This location contains code that was inlined from Derivation.scala:50
[error]    | This location contains code that was inlined from semiauto.scala:27
[error] one error found
[error] one error found
```

</details>

Using max inlines `-Xmax-inlines 10000000` flag does not do any justice either, it runs into stack overflow.

<details>
<summary>With max inlines</summary>

```scala
java.lang.StackOverflowError while compiling /Users/swoorup.joshi/IdeaProjects/temp/LBAbOJMVT1260OKUnBXuzw/src/main/scala/blockchain/Chain.scala, /Users/swoorup.joshi/IdeaProjects/temp/LBAbOJMVT1260OKUnBX
uzw/src/main/scala/blockchain/Transaction.scala, /Users/swoorup.joshi/IdeaProjects/temp/LBAbOJMVT1260OKUnBXuzw/src/main/scala/main.scala
[error] ## Exception when compiling 3 sources to /Users/swoorup.joshi/IdeaProjects/temp/LBAbOJMVT1260OKUnBXuzw/target/scala-3.0.0-RC1/classes
[error] java.lang.StackOverflowError
[error] dotty.tools.dotc.ast.Positioned.sourcePos(Positioned.scala:52)
[error] dotty.tools.dotc.report$.recur$1(report.scala:119)
[error] dotty.tools.dotc.report$.recur$1(report.scala:119)
[error] dotty.tools.dotc.report$.recur$1(report.scala:119)
[error] dotty.tools.dotc.report$.recur$1(report.scala:119)
```

</details>

## Expectation

```
[info] running Main
{
  "index" : 1,
  "proof" : 2,
  "previousHash" : "",
  "values" : [
  ],
  "timestamp" : 1615684763839
}
```

The same example in scastie works however, when everything is lumped together in a single file.
https://scastie.scala-lang.org/LBAbOJMVT1260OKUnBXuzw

**Comment by heksesang** [comment]
The zipped example works fine when:
- You put each given in their respective companion object.
- You declare `given Encoder[Transaction] = blockchain.given_Encoder_Transaction` in Chain.scala.
- You replace the `List[Transaction]` with just `Transaction`.

Also, the Scastie breaks if you use two different packages to separate the definitions:
https://scastie.scala-lang.org/heksesang/Vr8kHxhURgWxQBmGcxB9ww/6

Based on the observations above, I think the problem is most likely the same as https://github.com/lampepfl/dotty/issues/11538 and thus fixed in RC2.

The thing that breaks the derivation is the fact that there is a `List[Transaction]` coupled with the bug mentioned above. The implicit circe uses for `Encoder[List[A]]` requires an implicit `Encoder[A]`. When it looks for a `Encoder[List[Transaction]]`, it uses this implicit, but because of it does not find an implicit `Encoder[Transaction]`, the `summonFrom` defaults to trying to derive an `Encoder[List[Transaction]]`, and that causes some infinite recursion.

If you create `case class A(val i: Int)`, do not derive an `Encoder[A]`, but try to call `deriveEncoder[List[A]]` you will see the same problem.

If my deductions are correct, this is not a dotty bug, but a circe bug.

**Comment by nicolasstucki** [comment]
There isn't any macro in that code.

**Comment by nicolasstucki** [comment]
Is this a bug with the implementation of a macro in `io.circe`?

**Comment by nicolasstucki** [comment]
Can this be reproduced in a self contained example?

**Comment by heksesang** [comment]
The macro code in question is in circe.

I have made the issue https://github.com/circe/circe/issues/1695 with circe, which is about the useless error message their macro code generates in a given scenario – it's an implementation detail in the circe macro code that causes an infinite recursive inline when you try to derive an `Encoder[List[A]]` when there exists no `Encoder[A]`, instead of explaining to the user that there is no `Encoder[A]` or trying to derive the `Encoder[A]`.

The reason why this scenario occurs in the example code is because RC1 has a bug causing the scope for implicit search to be incomplete when the circe macro tries to `summonFrom` an instance (refer to https://github.com/lampepfl/dotty/issues/11538), and this again causes the issue in the circe macro code mentioned above to kick in. This bug should be fixed by the PR that closed https://github.com/lampepfl/dotty/issues/11538 along with a few others.

**Comment by smarter** [comment]
Sounds like we can close this then, thanks!
