### ISSUE TITLE
Incorrect inline doc?

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#11779]
In the inlining doc, [the inline `power` function](https://dotty.epfl.ch/docs/reference/metaprogramming/inline.html#recursive-inline-methods) contains this example:

```scala
inline def power(x: Double, n: Int): Double =
   if n == 0 then 1.0
   else if n == 1 then x
   else
      val y = power(x, n / 2)
      if n % 2 == 0 then y * y else y * y * x

power(expr, 10)
// translates to
//
//    val x = expr
//    val y1 = x * x   // ^2
//    val y2 = y1 * y1 // ^4
//    val y3 = y2 * x  // ^5
//    y3 * y3          // ^10
```

but that translation seems to be at odds with the rest of the doc.

* Shouldn't it be an `inline if` for the if-condition to be evaluated at compile-time?
* If an `inline if` is required, does that mean `n: Int` must be `inline n: Int`?

**Comment by nicolasstucki** [comment]
The example is correct.

* `inline if` enforces that the condition is evaluated at compile-time, normal if will also evaluate them at compile time in the same way (as an optimization) but they will not complain if it does not yield a constant.
* `inline n: Int` enforces that the values are inlined. `n: Int` will not enforce it but might do it as an optimization, namely literal constants for `Int`s are always optimized.
We should check that the docs are clear/clearer on these properties.

**Comment by nicolasstucki** [comment]
To me, it looks like the documentation contains all that information, but I might be biased. I suggest someone else to have a look and see if that is the case.

@japgolly after reading my last comment would you say that the docs do state these facts accurately? Did you learn about these concepts a long time ago from the docs? I ask because the semantics of some have changed. The current semantics follow what we described in [Semantics-preserving inlining for metaprogramming](https://dl.acm.org/doi/10.1145/3426426.3428486).
