### ISSUE TITLE
Compiler error using object method infix

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#11836]
## Compiler version

3.0.0-RC1

## Minimized code

```Scala
object X {
  def x[A](i: Int) = ()
}

object Y {
  X x[Int] 3
}
```

## Output

```
-- [E018] Syntax Error: x.scala:6:5 --------------------------------------------
6 |  X x[Int] 3
  |     ^
  |     expression expected but '[' found
```

## Expectation

It should compile (at least with `-source:3.0-migration` as this compiles with Scala 2.x).

**Comment by som-snytt** [comment]
Introduced at the end of the paulp regime by https://github.com/scala/scala/pull/3283

Arguably, Dotty should be least obliged to honor "Dotless type application for infix operators."

As we know, it's called Dotty not because of the calculus but because it is opinionated about dots.

**Comment by odersky** [comment]
I do not think that change was discussed or approved. I note that the official Scala 2.13 syntax does not support it.

https://scala-lang.org/files/archive/spec/2.11/13-syntax-summary.html

Given that 

 - it's easy to fix, and the fix poses no cross-compilation problems
 - nobody else had this problem so far, so it does not look like a common idiom
 - it would be messy to fix and also fruitless since we will not support this in the long run

I think it's easiest to demand that people reformat their code now.
