### ISSUE TITLE
Missing warning on certain top-level `final` defns

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#11855]
## Compiler version

3.0.0-RC1

## Minimized code

```Scala
package example

final type A = Int
final opaque type B = Int
final def x = 1
final val y = 1
final var z = 1
```

## Output

None.

## Expectation

I don't think `final` makes sense on these kind of top/package -level declarations. I think we're missing a compiler warning similar to what you get with `final object`.

**Comment by odersky** [comment]
I am actually not sure this is a good idea. `final object` clearly makes no sense, ever. But a toplevel definition could be `final` because somebody quickly copy-pasted some code from a class to test it out. A warning would be very annoying in that case. And I do not see it solves anything important.
