### ISSUE TITLE
Type member selection on argument of type Nothing fails

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#11864]
## Compiler version

3.0.0-RC1 with `-Ykind-projector -Yerased-terms`

## Minimized code

```Scala
final class CallbackTo[+A] {
  inline def map[B](f: A => B)(using erased ev: CallbackTo.MapGuard[B]): CallbackTo[ev.Out] = ???
}

object CallbackTo {

  type MapGuard[A] = { type Out = A }
  erased given MapGuard[A]: MapGuard[A] = ???

  def traverse[A, B](ta: List[A]): CallbackTo[List[B]] =
    val x: CallbackTo[List[A] => List[B]] = ???
    x.map(_(ta))
}
```

## Output

```
12 |    x.map(_(ta))
   |    ^^^^^^^^^^^^
   |Out cannot be accessed as a member of (ev$proxy1 : Nothing) from module class CallbackTo$.
   | This location contains code that was inlined from x.scala:2
1 error found
```

## Expectation

It should compile.

The problem occurs due to the combination of `inline` and `erased` because either of the following work as workarounds:
* Removing `inline` from `.map`
* Changing `MapGuard` to not be erased

**Comment by nicolasstucki** [comment]
Minimized 

```scala
type Ev = { type Out }
inline def foo(ev: Ev): Option[ev.Out] = ???
def test: Unit = foo(???)
```

The issue is that when we inline an `???` argument the inliner takes it as if it was of type `Nothing` and forgets the type of the parameter. Then any member selection fails. Maybe the binder should have type `Nothing & Ev` where the precise type of the argument is `Nothing` and the type of the parameter is `Ev`. If we can keep this type without collapsing it to `Nothing` then we could have the info we need for the member selection.

This issue appeared with the erased given because we optimize it away early to `???`.

**Comment by nicolasstucki** [comment]
This issue is the type selection version of issue #8612

**Comment by nicolasstucki** [comment]
`Null` has the same issue

**Comment by nicolasstucki** [comment]
An alternative might be to use the type of the parameter instead of a bottom type.

**Comment by liufengyun** [comment]
It seems to me your original [proposal](https://github.com/lampepfl/dotty/issues/8612#issuecomment-604422863) to use type ascriptions is a good and principled solution.

**Comment by odersky** [comment]
I agree, we should try to type ascribe in this case
