### ISSUE TITLE
Dotty emits unnecessary forwarders for trait methods

### ISSUE THREAD

**Issue by lrytz** [lampepfl/dotty#1206]
While working on https://github.com/scala/scala-dev/issues/98 to eliminate unnecessary forwarders for inherited trait methods I basically followed dotty's approach (https://github.com/lampepfl/dotty/blob/master/src/dotty/tools/dotc/transform/MixinOps.scala#L45).

I realized that dotty still emits unnecesary forwarders:

```
trait T1 { def f = 1 }
trait T2 extends T1 { override def f = 2 }
trait T3 { self: T1 => override def f = 2 }
class C1 extends T1 with T2 // no forwarder needed
class C2 extends T1 with T3 // forwarder needed
```

Dotty emits an unnecessary forwarder in `C1`.

See https://github.com/scala/scala/pull/5085 for my patch to scala/scala.

**Comment by DarkDimius** [comment]
@lrytz, Are you sure that in C1 no forwarder is needed?

>

Otherwise, if any superinterface of C declares a method with the name and descriptor specified by the method reference that has neither its ACC_PRIVATE flag nor its ACC_STATIC flag set, one of these is arbitrarily chosen and method lookup succeeds.


Afaik, the spec says that you need it here. Am I missing something?

**Comment by lrytz** [comment]
it's covered by the point above, IUC.

If the maximally-specific superinterface methods of C for the name and descriptor specified by the method reference include exactly one method that does not have its ACC_ABSTRACT flag set, then this method is chosen and method lookup succeeds.

see jvms-5.4.3.3, "maximally-specific method"

**Comment by smarter** [comment]
I believe this is now moot since scalac ended up having `-Xmixin-force-forwarders` default to `true` for performance reasons (and dotty should imitate this behavior and emit more forwarders, not less), feel free to reopen if I'm missing something.
