### ISSUE TITLE
We need windows batch-scripts

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1207]

**Comment by acdenhartog** [comment]
Unfortunately I do not know how to write batch scripts.

But for now the easiest way to compile with dotty on Windows is either [use IntelliJ](https://github.com/lampepfl/dotty/wiki/Using-Dotty-with-IntelliJ-IDEA) or
```
git clone https://github.com/lampepfl/dotty.git
cd dotty
sbt run <compiler arguments>
```

(maybe add that to [the wiki](../wiki/Getting-Started))

I have not been able to use it as per [dotty-example-project](https://github.com/smarter/dotty-example-project) because `sbt dotty-interfaces/compile:doc` is causing errors, and `dotty-interfaces/publishLocal` depends on that...

**Comment by smarter** [comment]
> I have not been able to use it as per dotty-example-project because sbt dotty-interfaces/compile:doc is causing errors, and dotty-interfaces/publishLocal depends on that...

Should be fixed by https://github.com/lampepfl/dotty/pull/1278

**Comment by liufengyun** [comment]
We already got rid of those scripts long ago.
