### ISSUE TITLE
Literal singleton type accepting wrong value

### ISSUE THREAD

**Issue by kavedaa** [lampepfl/dotty#12208]
## Compiler version

3.0.0-RC3

## Minimized code

```Scala
scala> val pi: 3.14 = 3
val pi: 3.14 = 3.0

scala> pi
val res0: Double = 3.14
```

## Expectation

2.13.4

```Scala
scala> val pi: 3.14 = 3
                      ^
       error: type mismatch;
        found   : Double(3.0)
        required: 3.14
```

**Comment by som-snytt** [comment]
Worth adding this was a good one. Earlier I checked `List[3.14](3.14, 3)`. I also checked in the example that `3.0` is stored in the field, but I didn't check what REPL is reporting when it prints the RHS. I also wondered whether it matters what is stored in the field.

No one would complain about
```
scala> var x: 3.14 = null.asInstanceOf[3.14]
var x: 3.14 = 0.0
```
oh wait
```
scala> x                                                                                                            
val res1: Double = 0.0
```
which I guess is due to unstable `x` but still surprises me. `x` has to be `3.14` even if I lied in initializing it.

Scala 2 throws in the `isInstanceOf` case. I don't know why without consulting code or spec.
```
scala> trait T { inline val pi = 3.14 }
// defined trait T

scala> (null: T).pi
val res0: Double = 3.14

scala> null.asInstanceOf[T].pi
1 |null.asInstanceOf[T].pi
  |^^^^^^^^^^^^^^^^^^^^^^^
  |getter pi is declared as erased, but is in fact used
```
