### ISSUE TITLE
Wildcard type conversion changed since Scala2

### ISSUE THREAD

**Issue by scf37** [lampepfl/dotty#12283]
## Compiler version

3.0.0-RC3

## Minimized code

```Scala
trait I[F[_], A]

def foo1[F[_]](f: F[_]): F[_] = f // error, ok in scala2
def foo2[F[_]](f: F[Any]): F[_] = f // error, ok in scala2
def foo3[F[_]](f: I[F, _]): I[F, _] = f // ok in scala2 and scala3

```

## Output

```scala
unreducible application of higher-kinded type F to wildcard arguments
```

## Expectation

All 3 should compile, like in Scala2?

**Comment by smarter** [comment]
This is an intentional change (these applications are equivalent to existential types which we have decide to not support), in parameter position one can instead write:
```scala
def foo1[F[_], A](f: F[A]): F[A] = f 
```
More generally one can wrap a type in a class to emulate wildcard application, cf https://scalacenter.github.io/scala-3-migration-guide/docs/incompatibilities/other-changed-features.html#wildcard-type-argument
