### ISSUE TITLE
Type deduction with literal types and type functions

### ISSUE THREAD

**Issue by Adam-Vandervorst** [lampepfl/dotty#12468]
## Compiler version
3.0.0-RC3
## Minimized code

```Scala
import compiletime.ops.int._

type Mul[N <: Int, T] =
  N match {
    case 1 => Tuple1[T]
    case S[prev] => Tuple.Concat[Tuple1[T], Mul[prev, T]]
  }

val alphabet = "abcdefghijklmnopqrstuvw"

def bind[L <: Int](n: L) = Tuple.fromArray((0 until n).map(i =>
  alphabet.charAt(i).toString).toArray
).asInstanceOf[Mul[L, String]]

@main
def test =
  val (a, b, c) = bind(3)
  println(a ++ b)
```

## Output

```scala
[error] 18 |  println(a ++ b)
[error]    |          ^^^^
[error]    |          value ++ is not a member of Any
```

## Expectation
Print "ab".

## Workaround
Write `n.type` instead of `L`

**Comment by smarter** [comment]
Type inference intentionally widens an inferred singleton type to a non-singleton upper-bound (because keeping the more precise singleton can have surprising consequences like breaking implicit search), you can force type inference to keep the singleton by adding a `Singleton` upper-bound: `def bind[L <: Int & Singleton](n: L) = ...`
