### ISSUE TITLE
Scala 3 Binaries on windows 7 64x not working

### ISSUE THREAD

**Issue by gruber123** [lampepfl/dotty#12551]
After changing all files in bin folder to extension .exe
else it run other scala version

This version of C:\scala3\bin\scala.exe is not compatible with the version of Windows you're running. Check your computer's system information
t) version of the program, and then contact the software publisher.

And there is no msi package as for scala 2

**Comment by michelou** [comment]
@gruber123 There are no Windows binaries.
Currently you have two options on Windows : 
1) develop your Scala 3 projects in a Unix-like environment such as [WSL](https://en.m.wikipedia.org/wiki/Windows_Subsystem_for_Linux), [MingW](https://sourceforge.net/projects/mingw/), etc.
2) install the batch files available from my GitHub project [`dotty-examples`](https://github.com/michelou/dotty-examples); in particular read the section [`batch/bash commands`](https://github.com/michelou/dotty-examples#batchbash-commands).

Since you are working on Windows 7 option 2 should be your choice (option 1 requires Windows 10).

**PS.** In 2018 I submitted the above batch files as part of [PR #5444](https://github.com/lampepfl/dotty/pull/5444); I finally closed it due to the lack of interest from the Dotty community.

**Comment by liufengyun** [comment]
> In 2018 I submitted the above batch files as part of [PR #5444](https://github.com/lampepfl/dotty/pull/5444); I finally closed it due to the lack of interest from the Dotty community.

@michelou That must be a miscommunication. Whenever you open a PR, I will make a priority to get it in. BTW, we have a dedicated Windows machine for testing now.

**Comment by liufengyun** [comment]
Let's re-open this issue for a PR to support Windows.

**Comment by bjornregnell** [comment]
Related to https://github.com/lampepfl/dotty/issues/12502
