### ISSUE TITLE
Incorrect erasure for intersection type in Java method

### ISSUE THREAD

**Issue by tpolecat** [lampepfl/dotty#12586]
## Compiler version

3.0.0

## Minimized code

Add dependency `"org.testcontainers" % "testcontainers" % "1.15.2"` and then try the following:

```Scala
scala> new org.testcontainers.images.builder.ImageFromDockerfile().withFileFromClasspath("foo", "bar")                                                                                                                   
java.lang.NoSuchMethodError: 'org.testcontainers.images.builder.traits.BuildContextBuilderTrait org.testcontainers.images.builder.ImageFromDockerfile.withFileFromClasspath(java.lang.String, java.lang.String)'
  ... 38 elided
```

The method in question is defined [here](https://github.com/testcontainers/testcontainers-java/blob/8965712f239ae3c449cec579264af5e79265f314/core/src/main/java/org/testcontainers/images/builder/traits/ClasspathTrait.java#L13).

Scala 2.13 generates the following instruction:

```
      16: invokeinterface #45,  3           // InterfaceMethod org/testcontainers/images/builder/traits/ClasspathTrait.withFileFromClasspath:(Ljava/lang/String;Ljava/lang/String;)Lorg/testcontainers/images/builder/traits/ClasspathTrait;
```

Scala 3.0 generates the following, which differs in the return type.

```
      18: invokeinterface #34,  3           // InterfaceMethod org/testcontainers/images/builder/traits/ClasspathTrait.withFileFromClasspath:(Ljava/lang/String;Ljava/lang/String;)Lorg/testcontainers/images/builder/traits/BuildContextBuilderTrait;
```

**Comment by smarter** [comment]
Huh, looks like I misread https://docs.oracle.com/javase/specs/jls/se8/html/jls-4.html#jls-4.4, somehow I was convinced the first operand of a Java intersection had to be a class and could not be an interface, and therefore designed our intersection erasure algorithm around this (https://github.com/lampepfl/dotty/pull/11808). Turns out that's completely false and now that 3.0 is out it's too late to change how we do intersection erasure, so we'll have to add a special case for Java intersection erasure (but I guess that was inevitable since we can't at the same time have commutativity and match the Java erasure semantics, oh well).

**Comment by smarter** [comment]
Oh man, looking at https://github.com/testcontainers/testcontainers-scala/pull/177 it looks like the problem was known before 3.0.0 was out, so if only we had known about it then, we could have potentially redesigned our erasure algorithm in time, whereas now we're stuck with it until Scala 4. Sadness.

**Comment by tpolecat** [comment]
Yep, sorry. Nobody looked at it closely until an hour ago. :-(
