### ISSUE TITLE
Failure to summon an implicit in a tuple polyfunctional map expression

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#12601]
I'm not completely sure this is a bug, but I don't understand why this should fail.

## Compiler version

v3.0.0

## Minimized code

```Scala
import compiletime.*

sealed trait Foo
object Foo:
  trait TC[T]:
    type Type <: Foo
    def apply(t: T): Type

  transparent inline given ofFoo[T <: Foo]: TC[T] =
    new TC[T]:
      type Type = T
      def apply(t: T): Type = t
  final case class Bar()

import Foo.TC
import Foo.{Bar}
val x = (Bar(), Bar())

transparent inline def foo[Tpl <: Tuple](tpl: Tpl): Any =
  tpl.map[[X] =>> TC[X]]([T] => (t: T) => summonInline[TC[T]])

val y = foo(x) //error
```

## Output

```scala
error overriding type Type in trait TC with bounds <: DFiant.core.Foo;
  type Type, which equals T has incompatible type
      type Type = T
```

## Expectation
Should compile.

**Comment by smarter** [comment]
I just tried it and the error message doesn't match what you wrote:
```scala
-- Error: try/i12601.scala:22:11 ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
22 |val y = foo(x) //error
   |        ^^^^^^
   |        no implicit argument of type Foo.TC[T] was found.
   |        I found:
   |
   |            Foo.ofFoo[Foo]
   |
   |        But given instance ofFoo in object Foo does not match type Foo.TC[T].
   | This location contains code that was inlined from i12601.scala:20
```

It'd be helpful if you explained what you were trying to do. The error message makes sense: you're looking for a `TC[T]` where `T` is unbounded (since you wrote `[T] => ...`), but the given ofFoo requires a type parameter which is known to be upper-bounded by `<: Foo`, so it's not applicable. And you can't write `[T <: Foo]  => ...` because the resulting polymorphic function is not a subtype of `[T] => ...` and so cannot be passed to the generic `map`.

**Comment by soronpo** [comment]
@smarter 
Regarding the error message, you can checkout this scastie:
https://scastie.scala-lang.org/jPRJ2o3BQruR08lRZbT9tQ

I'll reply with what I'm trying to do later.

**Comment by smarter** [comment]
Yes, please test things on master before opening an issue if possible. Also please use a support channel for help with doing things rather than issues.

**Comment by smarter** [comment]
(well testing on master is a bit inconvenient so testing with the latest nightly instead is fine)
