### ISSUE TITLE
Link between Seq (with no import) and ArraySeq lost in 3.0.0

### ISSUE THREAD

**Issue by jphmrst** [lampepfl/dotty#12642]
## Compiler version

`print scalaVersion` from sbt gives `3.0.0`

## Minimized code

```Scala
import scala.collection.mutable.ArraySeq
object X {
  def m[A](s: Seq[A]): Unit = ???
  def n[A](s: ArraySeq[A]): Unit = m[A](s)
}
```

(no import for `Seq`)

## Output

```scala
[info] compiling 1 Scala source to /home/jm/tmp/test/target/scala-3.0.0/classes ...
[error] -- [E007] Type Mismatch Error: /home/jm/tmp/test/src/main/scala/Main.scala:6:40 
[error] 6 |  def n[A](s: ArraySeq[A]): Unit = m[A](s)
[error]   |                                        ^
[error]   |                           Found:    (s : collection.mutable.ArraySeq[A])
[error]   |                           Required: Seq[A]
[error] one error found
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 3 s, completed May 28, 2021, 2:43:17 PM
```

## Expectation

Compiles without warning under Scala 2.

**Comment by smarter** [comment]
> Compiles without warning under Scala 2.

Under 2.12 maybe but not under 2.13 which produces the same error, because in 2.13 `scala.Seq` became an alias of `scala.collection.immutable.Seq` instead of `scala.collection.Seq`, this is intended behavior and unrelated to Scala 3: https://docs.scala-lang.org/overviews/core/collections-migration-213.html
