### ISSUE TITLE
`Quotes.reflectModule#Symbol.tree` does not match `Quotes.reflectModule#TypeDef`

### ISSUE THREAD

**Issue by giiita** [lampepfl/dotty#12658]
## Compiler version

scalaVersion
	3.0.0

## Minimized code

```Scala
final class Foo()

inline def test[T]: String = ${Macro.test[T]

test[Foo]
```

```scala
object Macro {
  def test[T: Type](using q: Quotes): Expr[String] = {
    println(
      q.reflect.TypeTree.of[T].symbol.tree match {
        case TypeDef(_, _) =>
          println("Match q.reflect.TypeDef")
        case dotty.tools.dotc.ast.Trees.TypeDef(_, _) =>
          println("Match dotty.tools.dotc.ast.Trees.TypeDef")
        case _ =>
          println("no match")
      }
    )
    '{ ??? }
  }
}
```

## Output

```
Match dotty.tools.dotc.ast.Trees.TypeDef
```

## Quotes
```scala
    trait TypeDefModule { this: TypeDef.type =>
      def apply(symbol: Symbol): TypeDef
      def copy(original: Tree)(name: String, rhs: Tree): TypeDef
      def unapply(tdef: TypeDef): (String, Tree)
    }
```

## QuotesImpl
```scala
type TypeDef = tpd.TypeDef
```

TypeDef should match q.reflect.TypeDef, since it is the same one via alias.
This means that to work with Trees extracted from TypeDef, we need to match dotty.tools.dotc.ast.Trees.TypeDef and then cast it.

```scala
           x.tree match {
             case dotty.tools.dotc.ast.Trees.TypeDef(_, _) =>
               println(s"$TypeDef ${q.reflect.TypeDef.unapply(x.tree.asInstanceOf[TypeDef])}")
               ...
           }
```

**Comment by smarter** [comment]
This is intentional, classes are matched by the ClassDef extractor, not by TypeDef, see the TypeTest instances: https://github.com/lampepfl/dotty/blob/master/compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala#L223-L227 vs https://github.com/lampepfl/dotty/blob/master/compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala#L319-L323. See https://dotty.epfl.ch/docs/reference/other-new-features/type-test.html for more information on TypeTest.
