### ISSUE TITLE
Method call fails for overloaded methods with default parameters

### ISSUE THREAD

**Issue by danicheg** [lampepfl/dotty#12679]
## Compiler version

3.0.0

## Minimized code

```scala
object Foo extends App {
  def foo[F[_]](qux: String, quux: String = ""): F[Unit] = ???

  def foo[F[_]](qux: Boolean): F[Unit] = ???

  def example[F[_]](maybeQux: Option[String], bool: Boolean) =
    maybeQux.fold(foo[F](bool))(foo[F](_))
}
```
https://scastie.scala-lang.org/LnY1kBvlQs2zclBzaeA0Vg

## Output

```scala
7 |    maybeQux.fold(foo[F](bool))(foo[F](_))
  |                                ^^^
  |None of the overloaded alternatives of method foo in object Foo with types
  | [F[_$2]](qux: Boolean): F[Unit]
  | [F[_$1]](qux: String, quux: String): F[Unit]
  |match type arguments [F] and arguments ((_$4 : String))
```

## Expectation
That works in Scala 2 (both [2.12.13](https://scastie.scala-lang.org/xRyA0BabToGvwcYgeOGcKA) and [2.13.6](https://scastie.scala-lang.org/BroTV3dFRHWqPNI4zeeNOQ)).

**Comment by danicheg** [comment]
The same example without higher kinded type works well:
```scala
object Foo extends App {
  def foo(qux: String, quux: String = ""): Unit = ()

  def foo(qux: Boolean): Unit = ()

  def example(maybeQux: Option[String], bool: Boolean) =
    maybeQux.fold(foo(bool))(foo(_))
}
```
https://scastie.scala-lang.org/b9jmQKk4STKND80gRy6cbQ

**Comment by bishabosha** [comment]
I have updated your example to remove the dependency on cats - it still fails with the same error

**Comment by danicheg** [comment]
It's also reproduce on `3.0.1-RC1`: https://scastie.scala-lang.org/b03p2cqfQiirhjQKLsdKFw

**Comment by odersky** [comment]
I tried some things, but have to give up fow now. The combination of overloading and default parameters is so complex that any change is extremely difficult. I think the right move is to go back to the drawing board and change the design of default parameters. Instead of the super-fragile default getter name encoding we should attach an inline expression directly to the parameter. That would improve and expressiveness, performance and decrease complexity. But it's an incompatible language change since default arguments could not be overridden anymore.

So, unless someone else feels more courageous than myself, don't hold your breath for a fix. It's better to avoid the combination of overloading and default parameters, except if the default parameter appears in the first parameter clause of the method.
