### ISSUE TITLE
summonFrom fails on covariant types with incorrect type in error message

### ISSUE THREAD

**Issue by bplommer** [lampepfl/dotty#12688]
## Compiler version

3.0.0, 3.0.1-RC1

## Minimized code

```Scala
case class Boxed[+A](a: A)
object Boxed:
  inline given derive[A]: Boxed[A] = scala.compiletime.summonFrom { 
    case a: A => Boxed(a)
  }

given Int = 1

val a: Boxed[Int] = Boxed.derive        // ok
val b: Boxed[Int] = summon[Boxed[Int]]  // compiler error
```

## Output

```scala
[error] -- Error: demo.scala:10:38 
[error] 10 |val b: Boxed[Int] = summon[Boxed[Int]]  // compiler error
[error]    |                                      ^
[error]    |                                   cannot reduce summonFrom with
[error]    |                                    patterns :  case given a @ _:Nothing
[error]    | This location contains code that was inlined from demo.scala:3
```

## Expectation
It should compile.

This works fine if `Boxed` is invariant in `A`.

**Comment by nicolasstucki** [comment]
Minimized to 

```scala
case class Boxed[+A](a: A)
object Boxed:
  given derive[A]: Boxed[A] = ???

val a: Boxed[Int] = Boxed.derive        // elaborates to: Boxed.derive[Int]
val b: Boxed[Int] = summon[Boxed[Int]]  // elaborates to: Boxed.derive[Nothing]
```
The implicit search constraints are probably `A >: Nothing <: Int` and because the type is covariant we choose the most precise type in that range (`Nothing`).

**Comment by odersky** [comment]
@nicolasstucki Your minimization compiles without error in master.

The original example also compiles if `inline` is replaced with `transparent inline`. What happens here is that the typer will produce the type-checked call
```scala
summon[Boxed[Int]](derive[A]): Boxed[A]
```
with the constraint
```
A <: Int
```
Then it finds it can interpolate `A` to its lower bound in the result, i.e. `A := Nothing` since it occurs covariantly and all other occurrences have already been typechecked. And that means that `derive` will fail, but only after typer.

I don't think there's anything that can be done here. Except an indication in the docs that `transparent inline` givens sometimes help if the result is covariant. But I don't see a good place in the docs to put it. PRs invited if somebody has an idea.
