### ISSUE TITLE
Multiple -d in scaladoc

### ISSUE THREAD

**Issue by BarkingBad** [lampepfl/dotty#12968]
Passing `-d` flag makes scaladoc throw warning about `-d` set multiple times. Probably comes from default values passed from `sbt`

**Comment by SethTisue** [comment]
It isn't clear to me this qualifies as a bug. sbt doesn't expect the user to pass `-d` directly; rather, it expects the user to customize `Compile / doc / target`.

(Also, wondering: is this any different than the Scala 2 behavior?)

**Comment by vincenzobaz** [comment]
Hi @SethTisue, @BarkingBad is helping me with a scaladoc tutorial and example setup and I complained about this warning.
I used the `-d` flag instead of `Compile / doc / target` because it is shown in the documentation, [here](https://dotty.epfl.ch/docs/usage/scaladoc/settings.html).

So probably this is a documentation bug rather than an implementation one :)

**Comment by BarkingBad** [comment]
Thanks Seth, you pointed me to the root of the problem I think. 
This is the [line](https://github.com/sbt/sbt/blob/develop/main/src/main/scala/sbt/Defaults.scala#L2158) where is aggregated `target` value and `scalacOptions` value

The question is, if one wants to put the docs in the separate directory different than `target/api` and pass the `-d` option to the `scalacOptions` should we hide the warning for that option, or leave it as a reminder that one is overriding the `target` default one

**Comment by dwijnand** [comment]
The point is that if one wants that they should redefine `Compile / doc / target`, not pass the `-d` option.  So I think there's no behavioural change to do here - but perhaps that doc page can make that clearer.

**Comment by BarkingBad** [comment]
Yeah, I will update the docs then
