### ISSUE TITLE
fewerBraces allows empty indentation region

### ISSUE THREAD

**Issue by som-snytt** [lampepfl/dotty#13097]
As originally noted by Scala book author @cayhorstmann on gitter, the fewer braces variant is circulating in the population.

## Compiler version

3.0.3-RC1

## Minimized code

```Scala
➜  ~/projects/dotty/bin/scala -language:experimental.fewerBraces
scala> List(42).foreach:
val res0: (Int => Any) => Unit = Lambda$1372/0x00000008010e8000@17ec5e2a

scala> import util.control.Breaks.*

scala> breakable:
val res1: (=> Unit) => Unit = Lambda$1413/0x00000008010fd208@5a4b8e25

scala> class C:
     | end C
// defined class C
```

## Output

It's not so much the output as the input. I hope REPL would wait for more.

The compiler allows empty indentation:
```Scala
def f = List(42).foreach:
end f

// package may not be empty, class template may be empty
package p:
  class C:
  end C
end p
```

## Expectation

The `def f` with empty indentation requires either `end f` or `eof`. Expect it to require a block expr and not happily eta-expand.

In REPL, it should work like `class C:`.

Spec requires a touch-up for the ArgExpr, but feature is still behind a flag.

**Comment by dos65** [comment]
The reason why it's parsed correctly is that `COLONEOL` is silently consumed by `argumentStart()` at this line: https://github.com/lampepfl/dotty/blob/eb8773ecbedd32b7f7f6822696f3c3df3cde6930/compiler/src/dotty/tools/dotc/parsing/Parsers.scala#L2298-L2300 and other branches won't match because the next token is `EOF`.

It seems that it having `COLONEOL` and `EOF` in `simpleExprRest` should lead to parsing error.  
Raising it using `syntaxErrorOrIncomplete` will also fix the issue with REPL.

So expectation is:
```scala
val x = List(42).foreach: // error 
```

**Comment by SethTisue** [comment]
to add a REPL test that uses a custom compiler flag, it seems we could either:

* add the test to `ReplCompilerTests.scala` (the `ReplTest` class allows passing compiler flags)
* build on top of https://github.com/lampepfl/dotty/pull/13982 and use the new `:settings` command to set `-language:experimental.fewerBraces` in a transcript in the `compiler/test-resources/repl` directory

the latter approach seems a bit nicer

**Comment by SethTisue** [comment]
We looked at this in the spree today. (We = me, @griggt, @gagandeepkalra, @jirid) but only got partway into it. @gagandeepkalra has a wip branch with some tests and a stab at a patch, but it's still very wippy.
