### ISSUE TITLE
Stack overflow error when nesting a case class and its companion object inside a method

### ISSUE THREAD

**Issue by JuggleHacker** [lampepfl/dotty#13162]
## Compiler version

I have just raised this issue for scala 2.12 and 2.13 (https://github.com/scala/bug/issues/12435) but it seems to also apply to scala 3.

## Minimized code

```Scala
def method(): Unit = {
  final case class Person(name: String)
  object Person {
    val me = Person("Cameron")
  }
  val _ = Person.me
}
method()
```

## Output

```scala
java.lang.StackOverflowError
```

## Expectation
Expected output is Unit. This happens if I change the val to a lazy val or def. I also get the expected output if I use the "new" keyword to construct the instance of my case class

**Comment by nicolasstucki** [comment]
Minimized to 
```scala
object Person {
  def apply(): Unit = ???
  val me = Person.apply()
}
@main def app = Person.me
```

**Comment by nicolasstucki** [comment]
The stack overflow seems correct as to initialize `Person` we need to initialize `me` and then to initialize `me` we need to initialize `Person`.

It is also clearly stated in the stack trace
```
...
        at Foo$package$.Foo$package$$$_$Person$1(Foo.scala:3)
        at Foo$package$Person$1$.<init>(Foo.scala:5)
        at Foo$package$.Person$lzyINIT1$1(Foo.scala:3)
        at Foo$package$.Foo$package$$$_$Person$1(Foo.scala:3)
        at Foo$package$Person$1$.<init>(Foo.scala:5)
        at Foo$package$.Person$lzyINIT1$1(Foo.scala:3)
        at Foo$package$.Foo$package$$$_$Person$1(Foo.scala:3)
        at Foo$package$Person$1$.<init>(Foo.scala:5)
        at Foo$package$.Person$lzyINIT1$1(Foo.scala:3)
        at Foo$package$.Foo$package$$$_$Person$1(Foo.scala:3)
...
```

**Comment by JuggleHacker** [comment]
But if I take my initial code out of the method it works fine - why should you only get an overflow if it is inside a method? I also don't understand why this would only happen for case classes when you don't use the "new" key word as well?

**Comment by dwijnand** [comment]
> Minimized to

I think minimising away from being a case class apply changes the case.

**Comment by Jasper-M** [comment]
>But if I take my initial code out of the method it works fine - why should you only get an overflow if it is inside a method? I also don't understand why this would only happen for case classes when you don't use the "new" key word as well?

I think case class apply is a special case because (in some cases) it gets rewritten to `new` by the compiler. Which possibly only makes this more confusing.

**Comment by bishabosha** [comment]
Here is a workaround,

what is happening is that a local object is rewritten to a lazy val, and all references to an object by its name calls the initialiser of the object, instead you can call a method of the objects during initialisation from `this`:
```scala
def method(): Unit = {
  final case class Person(name: String)
  object Person { self =>
    val me = self.apply("Cameron")
  }
  val _ = Person.me
}
method()
```

**Comment by LPTK** [comment]
@bishabosha sounds like when the compiler rewrites the object into a lazy val, it should also rewrite all its internal references to itself to self-object references, otherwise the rewriting is not semantics-preserving?

OTOH, it would be pretty hard to fix these things in general. Mutually-referential objects would require a more elaborate scheme.

When moved into a class or method, the example below also causes problems, whereas it works fine at the top-level:


```scala
object Person {
  def apply(): Unit = Person2.apply()
}
object Person2 {
  def apply(): Unit = ()
  val me = Person.apply()
}
def test = Person2.me
```

**Comment by som-snytt** [comment]
There is some speculation on the scala 2 issue. I think a good compromise for common use cases may suffice.

**Comment by odersky** [comment]
> @bishabosha sounds like when the compiler rewrites the object into a lazy val, it should also rewrite all its internal references to itself to self-object references, otherwise the rewriting is not semantics-preserving?

No, `object`s are defined as lazy vals/class combos. So it's by definition semantics preserving.

**Comment by LPTK** [comment]
@odersky moving an object definition into a method body doesn't seem to be a semantics-preserving transformation, because the transformed code may cause a stack overflow when the original did not.

It may be that the semantics diverges because the implementation of local lazy vals is different than the implementation of lazy val fields, but that sounds like an implementation detail. IMO the details of how objects are desugared internally by the compiler ideally should not influence their initialization behavior.
