### ISSUE TITLE
Type check mismatch

### ISSUE THREAD

**Issue by Adam-Vandervorst** [lampepfl/dotty#13164]
## Compiler version
3.0.0
## Minimized code

```Scala
case class G[A, X[_]](x: X[A])

enum Boxes[A]:
  case IntBox(a: Int)
  case StringBox(a: String)
import Boxes._

def f(i: Int): G[Int, Boxes] =
  val box = IntBox(i)
  return G(box)
```

## Output

```scala
Found:    (box : Boxes[Nothing])
Required: Boxes[Int]
  return G(box)
```

## Expectation
Behave the same as the in-line version (which does work)
```scala
...
def g(i: Int): G[Int, Boxes] =
  return G(IntBox(i))
```

**Comment by Kordyjan** [comment]
There is nothing wrong with what the compiler is doing here. You haven't specified the generic parameter `A` for your enum cases. So `IntBox` can be assigned to value with type `Boxes` parametrized with any type. For example 
```scala 
val a: Boxes[String] = IntBox(5)
val b: Boxes[List[List[String]] = IntBox(7)
```
is compiling. This is why the in-line version is passing, but it would also compile if you replaced the instance of `IntBox` with `StringBox` without changing the return type. The first example is failing because there is no explicit type specified for `val box` and the compiler is inferring `Boxes[Nothing]`, which is not compatible with the constructor of `G` as `Boxes` is invariant.

To achieve what, I assume that you wanted, you need something like:
```scala
enum Boxes[A]:
  case IntBox(a: Int) extends Boxes[Int]
  case StringBox(a: String) extends Boxes[String]
 ```

**Comment by Kordyjan** [comment]
From the typer's point of view 
```scala
def f(i: Int): G[Int, Boxes] =
  val box = IntBox(i)
  return G(box)
```
is not equivalent to
```scala
def f(i: Int): G[Int, Boxes] =
  return G(IntBox(i))
```
What would be much closer to equivalence is
```scala
def f(i: Int): G[Int, Boxes] =
  val box: Boxes[Int] = IntBox(i)
  return G(box)
```
which is compiling just fine. 
The typer is working with information it has during type inference. It is not taking into account potential future uses of the value.

**Comment by dwijnand** [comment]
This is, as I understand it, fundamentally down to the fact that the type system has subtyping.

**Comment by Adam-Vandervorst** [comment]
> The typer is working with information it has during type inference. It is not taking into account potential future uses of the value.

Maybe taking into account future uses is something useful to do, especially in trivial cases like this.
Going along that, the error messaging could be improved here:
`Found:    (box : Boxes[Nothing])` implies this type was given by the user.
In more difficult cases where the "taking into account future uses" fails, a clearer error message could read: 
```
Could not find a type for
  val box = IntBox(i)
that satisfies required type(s): 
Boxes[Int]
  return G(box)
```
This may significantly improve the comfort, while avoiding breaking the equivalence stated above as much as possible.
