### ISSUE TITLE
Inconsistent `export` of case classes' synthetic methods

### ISSUE THREAD

**Issue by tabdulradi** [lampepfl/dotty#13228]
## Compiler version

3.0.1

## Minimized code

```Scala
case class User(name: String)

case class RegisteredUser(id: String, data: User) {
  export data.*
}

@main def app() = 
  println(RegisteredUser("Id", User("Name"))) // RegisteredUser(Name)
  println(RegisteredUser("Id", User("Name")).canEqual(User("Name"))) // True
  // The rest works as expected
  println(RegisteredUser("Id", User("Name")) == User("Name")) // False
  println(RegisteredUser("Id", User("Name")).hashCode == User("Name").hashCode) // False
```

## Output

```scala
RegisteredUser(Name)
true
false
false
```

## Expectation

```scala
RegisteredUser(Id, User(Name))
false
false
false
```

According to @bishabosha 

> So what's happening here is that `productArity` and `productElement` are delegated to `data` field, (those methods are called from toString) but equals, hashCode, toString are not exported. (problematic that `canEqual` is also exported)

and
@kubukoz 
> Yeah, strange. toString defers to productPrefix I think, that should probably have been exported as well...

[1] https://twitter.com/bishabosha/status/1421803014722052098
[2] https://twitter.com/kubukoz/status/1421810894967906304

**Comment by odersky** [comment]
This looks according to do spec to me. `canEqual ` gets a forwarder since it is defined in `User`. Since it has a forwarder it won't be defined again in `RegisteredUser`. `toString` and `hashCode` and `equals` are different since they already exist as members of `RegisteredUser`.

Summary: When dealing with case classes, stay away from wildcard exports. The results might be unintuitive. As usual, explicit is better.

**Comment by tabdulradi** [comment]
Can we at least issue a compiler warning for wildcard exports of case classes? Seems it might be a source of many confusions.

**Comment by odersky** [comment]
I think that would be a job for a linter.

**Comment by smarter** [comment]
I think we do have a problem here because the result is not consistent under separate compilation, if I split the example into a file containing just:
```scala
case class User(name: String)
```
which I then compile, followed by compiling the rest of the example I get:
```scala
RegisteredUser(Id,User(Name))
false
false
false
```
because the PostTyper phase added synthetic definitions for canEqual/productXXX and wildcard exports filters synthetic definitions out: https://github.com/lampepfl/dotty/blob/9e8d5c55153fdbe0d3f78d661cb3b51113403128/compiler/src/dotty/tools/dotc/typer/Namer.scala#L1159

**Comment by odersky** [comment]
@smarter Fair point :-)
