### ISSUE TITLE
companion extension method not found for opaque type

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#13470]
## Compiler version

v3.1.0-RC1

## Minimized code

```Scala
opaque type Foo[T] = Int
object Foo:
  extension [T](f: Foo[T]) def foo: Int = 1

def bar[T](f: Foo[T]): Unit =
  val x = f.foo
```

## Output

```scala
value foo is not a member of Foo[T], but could be made available as an extension method.
```

## Expectation
No error.

**Comment by odersky** [comment]
It's because after inserting implicit top-level objects the code looks like this
```scala
object package$test:
  opaque type Foo[T] = Int

object Foo:
  extension [T](f: Foo[T]) def foo: Int = 1

def bar[T](f: Foo[T]): Unit =
  val x = f.foo
```
So, `Foo` is not a companion object of the opaque type here. That might be surprising, but follows from the spec how top-level definitions are expanded. I think we should rather not paper over this with a special case.

**Comment by smarter** [comment]
> So, Foo is not a companion object of the opaque type here. 

Are you sure? There's a special-case in top-level desugaring which ensures that the companion gets moved inside the package object: https://github.com/lampepfl/dotty/blob/a82a1a64694d97dbe38eb357e8c8d9ac1c04fed5/compiler/src/dotty/tools/dotc/ast/Desugar.scala#L1315
This is also what -Xprint:typer shows:
```scala
  final module opaque class i13470$package() extends Object() { this: i13470$package.type =>
    opaque type Foo[T >: Nothing <: Any] = Int
    final lazy module val Foo: Foo = new Foo()
    final module class Foo() extends Object() { this: Foo.type =>
      extension [T >: Nothing <: Any](f: Foo[T]) def foo: Int = 1
    }
    def bar[T >: Nothing <: Any](f: Foo[T]): Unit =
```

**Comment by odersky** [comment]
Good point. Not sure what goes on here then, yet.

**Comment by odersky** [comment]
Bit it works if I put the whole thing in an object. So there's still something wrong with the toplevel scope here.
```scala
object O:
  opaque type Foo[T] = Int
  object Foo:
    extension [T](f: Foo[T]) def foo: Int = 1

import O.*
def bar[T](f: Foo[T]): Unit =
  val x = f.foo
```

**Comment by odersky** [comment]
I found the reason: It's because we are in the scope of the opaque alias. Companions of type aliases do not form part of the implicit scope, only companions of abstract types do. Inside its scope an opaque type counts as a regular alias type. 

I looked at whether we can change it, but seems quite messay and dangerous to do so. Changing the implicit scope can have unexpected consequences. So I prefer to keep the simpler status quo, even if it is less intuitive.

Essentially the current algorithm to determine comanions is as follows:

 1. dealias
 2. if result is an anchor (i.e. a class, or an opaque type) include its companion object
 3. otherwise search the components of the type

For open opaque aliases we'd still have to look at the right hand side for companions, but now we would need to also include the companion object. So it's in a sense the union of (2) and (3), whereas (1) is blocked.

**Comment by soronpo** [comment]
@odersky Since this is now closed and won't be "fixed", then this behavior is now part of the spec, and therefore should be documented. Where should I add this for it to make sense?

**Comment by odersky** [comment]
I think it's in implicit-resulion.md. There we have:

> **Definition:** A reference is an _anchor_ if it refers to an object, a class, a trait, an abstract type, an opaque type alias, or a match type alias. References to packages and package objects are anchors only under `-source:3.0-migration`. 

We need to add:

> Opaque type aliases count as anchors only outside the scope where their alias is visible.

This makes the following text unambiguous. Previously, the first two clauses introduced non-determinism since a type could be both an alias and an anchor.

**Definition:** The _anchors_ of a type _T_ is a set of references defined as follows:

  1. If _T_ is a reference to an anchor, _T_ itself plus, if _T_ is of the form _P#A_, the anchors of _P_.
  1. If _T_ is an alias of _U_, the anchors of _U_.
  1. If _T_ is a reference to a type parameter, the union of the anchors of both of its bounds.
  1. If _T_ is a singleton reference, the anchors of its underlying type, plus,
    if _T_ is of the form _(P#x).type_, the anchors of _P_.
  1. If _T_ is the this-type _o.this_ of a static object _o_, the anchors of a term reference _o.type_ to that object.
  1. If _T_ is some other type, the union of the anchors of each constituent type of _T_.

**Comment by soronpo** [comment]
OK, I'll submit a PR for the docs.
