### ISSUE TITLE
Scala 2 code is red: implicit conversion applied before implicit operator application

### ISSUE THREAD

**Issue by SimY4** [lampepfl/dotty#13539]
## Compiler version
Scala 3.0.2 and Scala 3.1.0-RC1

## Minimized code

```Scala
import scala.language.implicitConversions

trait Empty[A]:
  def empty: A

object Empty:
  given Empty[String] with
    def empty: String = ""

extension (b: Boolean)
  def ?[A](ifTrue: => A)(using E: Empty[A]): A = if b then ifTrue else E.empty

def main: Unit = 
  val string = "string"

  implicit def stringToInt(s: String): Int = s.toInt

  val res: Int = true ? string
```

## Output

```scala
no implicit argument of type Playground.Empty[Int] was found for parameter E of method ? in object Playground
```

## Expectation
The boolean extension will use Empty instance for string first, then the result of that will be converted using implicit conversion method.

This code worked in Scala 2.

**Comment by smarter** [comment]
This is due to the improved type inference in Scala 3 and there is no good way for us to replicate the behavior of Scala 2 unfortunately, see https://github.com/lampepfl/dotty/issues/8803 for details. This is one of the reason we'd like to limit/remove implicit conversions from the language: https://contributors.scala-lang.org/t/can-we-wean-scala-off-implicit-conversions/4388
