### ISSUE TITLE
Anonymous functions defined in anonymous classes are emitted on containing object instead of being emitted on anonymous class

### ISSUE THREAD

**Issue by mpilquist** [lampepfl/dotty#13568]
This may be expected behavior / an optimization but I wanted to open an issue to determine if it's intended or not. This behavior resulted in a bug in FS2: https://github.com/typelevel/fs2/issues/2623

## Compiler version

3.0.2

## Minimized code

```Scala
trait Foo {
  def foo(x: Option[Int]): Option[Int]
}

object Bar {
  def mk = new Foo {
    def foo(x: Option[Int]) = x.map(_ + 1)
  }
}
```

## Output

```scala
➜  javap -c -cp . Bar\$
Compiled from "foo.scala"
public final class Bar$ implements java.io.Serializable {
  public static final Bar$ MODULE$;

  public static {};
    Code:
       0: new           #2                  // class Bar$
       3: dup
       4: invokespecial #18                 // Method "<init>":()V
       7: putstatic     #20                 // Field MODULE$:LBar$;
      10: return

  public Foo mk();
    Code:
       0: new           #9                  // class Bar$$anon$1
       3: dup
       4: invokespecial #30                 // Method Bar$$anon$1."<init>":()V
       7: areturn

  public static final int Bar$$anon$1$$_$foo$$anonfun$1(int);
    Code:
       0: iload_0
       1: iconst_1
       2: iadd
       3: ireturn
}
```

Note the final member: `public static final int Bar$$anon$1$$_$foo$$anonfun$1(int);`

## Expectation

```scala
javap -c -cp . Bar\$
Compiled from "foo.scala"
public final class Bar$ {
  public static final Bar$ MODULE$;

  public static {};
    Code:
       0: new           #2                  // class Bar$
       3: dup
       4: invokespecial #14                 // Method "<init>":()V
       7: putstatic     #16                 // Field MODULE$:LBar$;
      10: return

  public Foo mk();
    Code:
       0: new           #7                  // class Bar$$anon$1
       3: dup
       4: invokespecial #19                 // Method Bar$$anon$1."<init>":()V
       7: areturn
}
```

**Comment by smarter** [comment]
I think this is just an implementation detail and one shouldn't rely on it working one way or another, if a class or method might not be present, only access it indirectly via a MethodHandle (like in https://github.com/scala/scala/blob/7d7daa6be0f84364111fc217fddc161e2984ff48/src/library/scala/runtime/Statics.java#L151-L162) to make sure it doesn't appear in any method signature generated by the compiler.

**Comment by smarter** [comment]
(https://openjdk.java.net/jeps/238 would be another option, but I don't think sbt supports that natively at all).

**Comment by djspiewak** [comment]
I'm not sure if this is an implementation detail or actually an important property. Class loading on the JVM is lazy and hierarchical, and most users of JVM languages who think about it have the intuition that this hierarchy matches the nesting of their source code. That was certainly the case in Scala 2, but this element of Scala 3 breaks that intuition. IMO the fact that it's observably different between named and anonymous classes is a pretty fair reason to want to fix it.

I'm definitely not claiming that this is a common scenario, but the initialization semantics of JVM class loading are very much things that people rely on in cases like this.

**Comment by smarter** [comment]
> IMO the fact that it's observably different between named and anonymous classes is a pretty fair reason to want to fix it.

I don't think it is, the same thing happens with a local named class:
```scala
  def mk = {
    class Baz extends Foo {
      def foo(x: Option[Int]) = x.map(_ + 1)
    }
    new Baz
  }
```
In both cases the line responsible for the lifting is:
https://github.com/lampepfl/dotty/blob/3a6a9499f0bd1821351f052631a0a1d3842f05c1/compiler/src/dotty/tools/dotc/transform/LambdaLift.scala#L102-L103

I'm relunctant to touch this logic since getting it wrong can lead to deadlock in static initializers of objects, etc.

**Comment by smarter** [comment]
Some documentation here, just to confirm that "lift things as high as possible" is a fundamental design decision in our LambdaLift implementation, and not a by-product of something else:
https://github.com/lampepfl/dotty/blob/3a6a9499f0bd1821351f052631a0a1d3842f05c1/compiler/src/dotty/tools/dotc/transform/Dependencies.scala#L43-L50

**Comment by odersky** [comment]
Yes, the lifting is intended since it avoids a redundant outer reference, which could be the source of a memory leak. Scala 3 does better than Scala 2 in this respect.

**Comment by vasilmkd** [comment]
For what it's worth, Java encodes lambda methods more or less identically to Scala 2, with the body of the methods being compiled on the same class.

I do sympathize with the desire to remove outer references, but IMO that's a separate concern from compiling the lambda body. In Java, the need for an outer reference is determined statically, by having `static class` for inner classes that don't need an outer reference and plain `class` for inner classes that capture an outer reference. As far as I can tell, Scala 2 did not try to analyze things to fully avoid an outer reference in all cases where that is possible, but Scala 3 does this, and it works well in practice.

However, that still doesn't completely excuse this change in Scala 3. Java is an example of removing outer references _and_ compiling lambda bodies in the innermost class.

As a motivating example, I will give you the IntelliJ IDEA Scala debugger, which I currently work on. In the debugger, there is an expression evaluator, that allows the user to evaluate arbitrary Scala expressions. When working on a Scala 2 project, expressions containing lambdas (anonymous functions) are compiled by the corresponding compiler, the class files are loaded into the IntelliJ debugger and the code is then invoked through the debugger interface (which is more or less reflection, but that is irrelevant). The important part is that this works, because all of the necessary code, including the lambda bodies are contained within the one class file, which can furthermore be made unique to each execution.

However, the debugger is broken for Scala 3, and precisely because of this change. When the arbitrary expression containing an anonymous function given by the user is compiled, the lambda body is compiled on the outermost class, which can be an arbitrary Scala class, including library dependencies. When these classes are augmented with the new lambda bodies, they cannot be loaded into the debugger, because classes cannot be replaced at runtime, at least not in the same class loader. I tried designing a custom ClassLoader which favors the newly compiled classes, and I managed to somehow get the new classes loaded, but then the runtime objects that the debugger works with are actually instances of the original, unmodified classes, and therefore cannot be cast to the newly loaded class and used as such.

I would appreciate any ideas for what could be done here. I've thought about manually rewriting the class files and adding back the lambda bodies, but that requires changing the method handles as well, which is not very easy in practice.

In any case, even if something were to be done about this ABI change, Scala 3.0, 3.1 and 3.2 would need to be supported in any case, in their current state.

Thanks for reading if you made it all the way here.

**Comment by smarter** [comment]
I don't have any specific idea of what to do here but:

> Scala 3.0, 3.1 and 3.2 would need to be supported

I think it's better to dedicate resources towards improved support for future compiler versions rather than trying to support obsolete versions at all cost. We're releasing new minor releases at a rapid pace and doing everything we can to make it easy for people to upgrade. This should be good news for tooling authors since they can fix things in the compiler (as might need to be done here?) and have these fixes delivered to users quickly rather than maintaining workarounds forever.

> However, the debugger is broken for Scala 3, and precisely because of this change.

Metals is also working on having a debugger that supports expression evaluation with Scala 3, this sounds like an area where you could collaborate.

**Comment by vasilmkd** [comment]
Thanks for the input @smarter.
