### ISSUE TITLE
Type erased for `by-name` parameters

### ISSUE THREAD

**Issue by jlprat** [lampepfl/dotty#13638]
When a method has `by-name` parameters its type it's erased in the generated bytecode.

## Compiler version
`3.0.2` and `3.1.0-RC2`

## Minimized code
```Scala
object ByNameParam {
  def byNameParam(str: => String): Unit = {}
}
```
You can find a reproducer project [here](https://github.com/jlprat/by-name-param-type-erased) where one can compile with Scala 2.13.6, 3.0.2 and 3.1.0-RC2 and see the difference in bytecode between versions.

## Output
`$> javap ByNameParam.class`
```text
Compiled from "ByNameParam.scala"
public final class ByNameParam {
  public static void byNameParam(scala.Function0);
}
```

## Expectation
This is the output of the same class when compiling against Scala 2.13.6.
`$> javap ByNameParam.class`
```text
Compiled from "ByNameParam.scala"
public final class ByNameParam {
  public static void byNameParam(scala.Function0<java.lang.String>);
}
```
Please note the missing type parameter `String` on `Function0`.

## Impact
Java interoperability will be affected by this bug as the String type is completely lost.

**Comment by smarter** [comment]
Java generic signatures are generated by https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala, and by-names are represented as ExprType, presumably the issue is that we don't generate a generic signature at all here and we just need to a case ExprType that returns true to https://github.com/lampepfl/dotty/blob/44d907f19a193707920fd0729d1627f472e3bf1d/compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala#L455
