### ISSUE TITLE
Doctool: no index.html in root of jar

### ISSUE THREAD

**Issue by NthPortal** [lampepfl/dotty#13661]
## Compiler version

3.0.2

## Expectation

I expected the jar to contain an `index.html` file in its root. Because it only has an `index.html` within the `api` directory, some tools that handle javadocs or scaladocs from Scala 2 are unable to handle the docs (e.g. javadoc.io).

**Comment by BarkingBad** [comment]
The issue should be gone with 3.1.0, but I will double-check that one. Nonetheless, could you try one of the RC versions of 3.1.0 (best would be 3.1.0-RC3) with your current project, and if the issue still persists we will backport fixes. Unfortunately, we cannot fix it for 3.0.2 as it has been already released, but version 3.1.0 is around the corner and will be release in 2-3 weeks.

**Comment by NthPortal** [comment]
it seems like this might be a duplicate of #11412, but from a different angle?

**Comment by BarkingBad** [comment]
I observed that under certain configurations you could not have top-level index.html. I am working on fixing that as well as on adding some integration tests proving that we always have index.html as the top file. Nonetheless default configuration of scaladoc should work fine. 

As it comes to #11412 the main problem was that new scaladoc was putting always things under `api` directory, which was resulting in double nesting of `api/api` while compiled from the sbt. Now, the #13130 should have fixed it. The second question was about providing `index.html` for inner packages, which I am not sure if is the problem, because you can already enter through the top-level index and then navigate using the UI.
