### ISSUE TITLE
Match quoted tuple prepend

### ISSUE THREAD

**Issue by Adam-Vandervorst** [lampepfl/dotty#13956]
## Compiler version

3.1.2-RC1-bin-20211025-968dd1b-NIGHTLY

## Minimized code

```Scala
import scala.quoted.*

def printallImpl[T <: NonEmptyTuple](xs: Expr[T])(using Quotes): Expr[Unit] =
  xs match
    case '{ $head *: (${tail}: Tuple) } =>
      '{ print($head); print(" *: "); println($tail) }
    case '{ ($fst, $snd) } =>
      '{ print($fst); print(", "); println($snd) }

inline def printall[T <: NonEmptyTuple](inline xs: T) = ${ printallImpl('{xs}) }
```

```scala
@main def example = printall((1, 2))
```

## Output

```scala
1, 2
```

## Expectation
```scala
1 *: Tuple(2)
```

I expect `'{ $head *: (${tail}: Tuple) }` to catch something matching `'{ ($fst, $snd) }`, but I'm new to this area.

**Comment by nicolasstucki** [comment]
The natural assumption you probably made is that `(1, 2)` is equivalent to `1 *: 2 *: EmptyTuple`. This is unfortunately not the case on the term level. Thought on types it is true `(1, 2)` is of type `Int *: Int *: EmptyTuple`.

The reason behind this is that to keep compatibility with Scala 2 we need to keep the old `TupleN` (from 1 to 22) types and constructors. This implies that `(1, 2)` is actually `Tuple2(1, 2)`. To make old tuples work with the new tuples we make `Tuple2[T1, T2]` a subtype of `T1 *: T2 *: EmptyTuple`. We also have to add the operations of Tuple using inline definitions which makes things a bit more complex.

At some point in the future, when we drop Scala 2 backward compatibility we will be able to simplify this.

An alternative to match against the type instead of the constructor.
```scala
    case '{ $tuple : Int *: Tuple } =>
```
or
```scala
    case '{ type tail <: Tuple; $tuple : fst *: `tail` } =>
```
Though then you cannot extract the elements and would need to call `head` to get them at runtime.

As long as we have `TupleN` we will need to match offer its constructors and aliases. See https://github.com/lampepfl/dotty/blob/master/library/src/scala/quoted/FromExpr.scala#L174-L181

**Comment by nicolasstucki** [comment]
I will convert this to a discussion because even if it is not an the current and future discussions can help other users to understand what to do in these situations.
