### ISSUE TITLE
Cannot select shared member from union of structural types

### ISSUE THREAD

**Issue by prolativ** [lampepfl/dotty#13978]
## Compiler version

3.1.2-RC1-bin-20211118-2b37257-NIGHTLY

## Minimized code

```scala
trait S extends Selectable:
  def selectDynamic(s: String): String = s

type Sab = S { def a: String; def b: String }
type Sbc = S { def b: String; def c: String }

type Sb = Sab | Sbc

val sb1: Sb = (new S {}).asInstanceOf[Sb]
val b1 = sb1.b

val ev = summon[Sb <:< S { def b: String }]

val sb2: S { def b: String } = sb1
val b2 = sb2.b
```

## Output

```scala
[error] value b is not a member of Sb
[error] val b1 = sb1.b
[error]          ^^^^^       
```

## Expectation

As the compiler is able to prove that `Sb` is a subtype of `S { def b: String }`, which has `b` as a member, it should be possible to select `b` from an instance of `Sb`

**Comment by odersky** [comment]
Yes, that's a known and intentional restriction. If you think "why does the compiler not simply join all refinements to determine common members", consider what will happen if some of these members are recursive. Scala's implementation of `lub` does something that and it not something we want to copy. If you wonder why, have a look at the code.
