### ISSUE TITLE
Ambiguous extension methods not reported in presence of overrides

### ISSUE THREAD

**Issue by mpilquist** [lampepfl/dotty#13995]
## Compiler version

3.1.1-RC1 and 3.1.0

## Minimized code

```scala
trait Functor[F[_]]:
  extension [A](fa: F[A]) def map[B](f: A => B): F[B]
trait Monad[F[_]] extends Functor[F]:
  extension [A](fa: F[A])
    override def map[B](f: A => B): F[B] = ???
trait Traverse[F[_]] extends Functor[F]

def useMap[F[_]: Monad: Traverse, A](fa: F[A]) = fa.map(identity)
```

## Expectation

The above compiles successfully instead of complaining that `Monad` and `Traverse` both provide a `map` extension method. If the override of `map` in `Monad` is commented out, you get the expected ambiguity error. As much as I'd love type class coherence, I don't think this is intended. :)

**Comment by som-snytt** [comment]
Isn't this just overload resolution at work? It picks the most specific `map`. However, the reference language isn't clear on this point: "If there is more than one way of rewriting" sounds like it means "any productions" or "any eligible objects", rather than rewritings after picking a most-specific `given` with the required `extension`. The language that this happens along with implicit conversions suggests the same overloading resolution happens as in related Scala 2 constructs.

But I don't really know.

**Comment by odersky** [comment]
According to the rules the `Monad` instance is more specific than the `Functor` instance. That's how the ambiguity is avoided.
