### ISSUE TITLE
Inlining private method breaks compilation

### ISSUE THREAD

**Issue by scf37** [lampepfl/dotty#14042]
## Compiler version

3.1.0

## Minimized code

```Scala
trait T {
  inline def foo(handler: Int): Unit =
    bar(handler)

  private inline def bar(handler: Int): Unit = ()
}

new T {
  foo(42)
}
```

## Output

```scala
undefined: T_this.bar # -1: TermRef(TermRef(NoPrefix,val T_this),bar) at inlining
```

## Expectation

Successful compilation

**Comment by odersky** [comment]
It's because we do not generate inline accessors for inline methods. See `needsAccessor` in `PrepareInlineable`. 

I see two possible ways to fix this. Ideally, we do create an inline accessor which is itself defined
`inline` (and transparent, if the accessed method is transparent). I tried that, but it does not work currently, since the inline accessor does not get inlined. 

If that does not work, we could also issue a static error if an inline method calls a private inline method.

**Comment by odersky** [comment]
It turns out the static error route would invalidate several existing tests and the compiler itself.

**Comment by nicolasstucki** [comment]
To fix this we first need to fix #14048 as we would probably hit it on the way.

**Comment by nicolasstucki** [comment]
We should be evaluating this branch but the symbol is `NoSymbol`.
https://github.com/lampepfl/dotty/blob/main/compiler/src/dotty/tools/dotc/typer/Inliner.scala#L1584

**Comment by nicolasstucki** [comment]
The issue comes from transforming `new T { foo(42) }` into `new T { bar(42) }`. As `bar` is private in `T` it cannot be selected from the anonymous `new T`. 

@odersky is there a way to compute this symbol?

**Comment by odersky** [comment]
@nicolasstucki Not if it is private.
