### ISSUE TITLE
java.lang.ClassCastException when parsing scala2 Enumeration Type

### ISSUE THREAD

**Issue by rssh** [lampepfl/dotty#14065]
## Compiler version

3.1.0,  3.1.1-RC1

## Minimized code

File M.scala

```Scala
package x

import scala.quoted._

object Macro:

   inline def scala2EnumerationTest[T]: Boolean = ${
       scala2EnumerationTestImpl[T]
   }

   def scala2EnumerationTestImpl[T:Type](using Quotes): Expr[Boolean] = {
       import quotes.reflect.*
       val tpe = TypeRepr.of[T]
       tpe match
         case TypeRef(ct, name) =>
           ct match
             case Singleton(obj) =>
                println("obj="+obj)
                Expr(true)
             case _ =>
                println("Singleton expected, we have $ct")
                ???
         case _ =>
           println(s"Enumeration.Value was expected, we have $tpe")
           ???
   }

```

File X.scala
```Scala
package x

object TestEnumeration extends Enumeration {
  type ValueType = Value
  val One, Two, Three = Value
}

object Main:

   def main(args: Array[String]):Unit =
     println(Macro.scala2EnumerationTest[TestEnumeration.ValueType])
```

## Output (click arrow to expand)
<details>

```scala
[warn] -- Unchecked Warning: /Users/rssh/tests/dotty/test-new/src/main/scala/x/M.scala:17:18 
[warn] 17 |             case Singleton(obj) =>
[warn]    |                  ^
[warn]    |    the type test for x$1.reflect.Singleton cannot be checked at runtime
[warn] one warning found
[error] -- Error: /Users/rssh/tests/dotty/test-new/src/main/scala/x/X.scala:11:40 ------
[error] 11 |     println(Macro.scala2EnumerationTest[TestEnumeration.ValueType])
[error]    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |Exception occurred while executing macro expansion.
[error]    |java.lang.ClassCastException: class dotty.tools.dotc.core.Types$CachedTermRef cannot be cast to class dotty.tools.dotc.ast.Trees$SingletonTypeTree (dotty.tools.dotc.core.Types$CachedTermRef and dotty.tools.dotc.ast.Trees$SingletonTypeTree are in unnamed module of loader sbt.internal.classpath.ClassLoaderCache$Key$CachedClassLoader @712c2a0c)
[error]    |	at scala.quoted.runtime.impl.QuotesImpl$reflect$Singleton$.unapply(QuotesImpl.scala:1154)
[error]    |	at x.Macro$.scala2EnumerationTestImpl(M.scala:17)
[error]    |
[error]    | This location contains code that was inlined from X.scala:11
[warn] one warning found
[error] one error found
[warn] one warning found
[error] one error found

```
</details>

**Comment by nicolasstucki** [comment]
The crash was caused by the unchecked type test for `Singleton`. This is the expected behavior just like with any other unchecked type in a pattern match. It is equivalent to something like

```scala
def f[T](xs: List[T]) = xs match
  case xs: List[String] => xs.head.substring(2)
  case _ =>
f(List(1, 2, 3))
```

Note that `ct` is of type `TypeRepr` (`TermRef` in this example) and `Singleton` is a `Tree`. The unapply of `Singleton` expects a `Tree` which cannot be checked at runtime because those types are erased and there is no `TypeTest` for those situations.

**Comment by dwijnand** [comment]
Erased to Object?

**Comment by rssh** [comment]
Hmm,  but is this not a TypeTree, then the match statement should return None by contract.

**Comment by dwijnand** [comment]
I think to do that we would need a TypeTest between trees and types, but I think then you wouldn't get an unchecked warning that you're doing it wrong, it would compile and then always return None, silently.  In the current situation we get a chance to notice these things at runtime.

Actually, maybe we could still write a type test and have it statically return `None.type` (not `false`, because it's defined to return Option I think), then we could still do something at compile time, whether that's emitting a warning or an error.  WDYT, @nicolasstucki?  Would that be a handy improvement, do you think?

**Comment by bishabosha** [comment]
> Hmm, but is this not a TypeTree, then the match statement should return None by contract.

if you take a look at `Quotes`, we see that `SingletonTypeTest` is a `TypeTest[Tree, Singleton]`
so statically the type test will only be used when matching on a `Tree`, so that's why you get the warning

**Comment by rssh** [comment]
Thanks, understood.  
// from an ergonomic point of view,  expected preferences are:  
- 1) compile-time error.  
- 2) warning + run-time None  
- 3) warning + exception inside compiler core as now.  (which will be interpreted by some application programmers as an error in the compiler, regardless of this is expected or not).)
