### ISSUE TITLE
Extension method with default argument fails to construct

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#14278]
## Compiler version

v3.1.1-RC2

## Minimized code

https://scastie.scala-lang.org/MiSpvFT0SKygDNEJdezOzQ
```Scala
class Foo

extension (foo : Foo)
  def patch(arg : List[Int], arg2 : Int = 0) : Unit = {}
  def patch(arg : Int) : Unit = patch(List(arg))
```

## Output

```scala
value patch is not a member of Playground.Foo.
An extension method was tried, but could not be fully constructed:

    Playground.patch()
```

## Expectation
No error.

**Comment by odersky** [comment]
The problem comes from a combination of overloading, currying, and default arguments. It has nothing to do with extension methods. For instance:
```scala
class Foo

object Test {
  def patch2(foo: Foo)(arg : List[Int], arg2 : Int = 0) : Unit = {}
  def patch2(foo: Foo)(arg : Int) : Unit = patch2(foo)(List(arg))
}
```
fails with 
```
-- [E134] Type Error: i14278a.scala:5:43 ---------------------------------------
5 |  def patch2(foo: Foo)(arg : Int) : Unit = patch2(foo)(List(arg))
  |                                           ^^^^^^
  |None of the overloaded alternatives of method patch2 in object Test with types
  | (foo: Foo)(arg: Int): Unit
  | (foo: Foo)(arg: List[Int], arg2: Int): Unit
  |match arguments ((foo : Foo))
1 error found
```
Scala 2.13 also fails here:
```
14278a.scala:5: error: ambiguous reference to overloaded definition,
both method patch2 in object Test of type (foo: Foo)(arg: Int): Unit
and  method patch2 in object Test of type (foo: Foo)(arg: List[Int], arg2: Int): Unit
match argument types (Foo)
  def patch2(foo: Foo)(arg : Int) : Unit = patch2(foo)(List(arg))
                                           ^
1 error
```
Maybe the advice (requirement?) should be that overloaded curried methods (which includes extension methods) cannot have default arguments.

**Comment by soronpo** [comment]
Or the advice could be to use implicit classes, since we don't have the problem there. It's incorrect to compare Scala 2.13 according to how extension methods are desugared. Scala 2.13 has implicit classes and that is what extension methods are meant to replace. From user perspective I do not care about the desugaring. I care about expressiveness.

**Comment by som-snytt** [comment]
I will make an effort to understand this issue today, but I just realized I lost an hour of sleep due to "daylight saving."

I don't think default args should break this case. If one alternative is applicable, then it is selected; if more than one is applicable, then alternatives requiring default args are discarded. That is my understanding of the spec; I don't understand the dotty code yet.

I sympathize with soronpo's view that it's the user's use case that matters. But I think extension methods should fit the bill. "It's just a method." Also, "overloading is evil" but "it's just overloading."
