### ISSUE TITLE
extractAPI fails with unsafeNulls and Yexplicit-nulls

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#14319]
## Compiler version

3.1.0

## Minimized code

```Scala
// -Yforce-sbt-phases -Yexplicit-nulls
import java.nio.file.FileSystems

def directorySeparator: String = {
  import scala.language.unsafeNulls
  FileSystems.getDefault().getSeparator()
}
```

## Output

```scala
-- Error: foo.scala:5:39 -------------------------------------------------------
5 |  FileSystems.getDefault().getSeparator()
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |undefined: java.nio.file.FileSystems.getDefault().getSeparator # -1: TermRef(OrType(TypeRef(ThisType(TypeRef(NoPrefix,module class file)),class FileSystem),TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Null)),getSeparator) at sbt-api
1 error found
```

## Expectation

extractAPI maybe ignores this?

**Comment by noti0na1** [comment]
I think this issue is similar to #13976: the imported language feature is not avaiable after typer.

When we transform `FileSystems.getDefault().getSeparator` in PostTyper, the type of `FileSystems.getDefault()` is nullable. We will get wrong type at `.getSeparator` because `unsafeNulls` is not visible at this phase.

We can always add a special attachment to the tree in typer if needed. I'm wondering if there is a better and general solution.

**Comment by olhotak** [comment]
See #14346 for a sketch of a general solution.
