### ISSUE TITLE
Unable to use existentials as arguments to unapply

### ISSUE THREAD

**Issue by julienrf** [lampepfl/dotty#1449]
Using an existential as argument to `unapply` results in the following runtime error: Method $init$ in class Main$Foo has illegal modifiers: 0x1.

See http://scastie.org/21730

(Note that I wasn’t able to setup dotty on my machine as per https://github.com/smarter/dotty-example-project. I hope the error I’m reporting is not a problem that comes from scastie.org…)

See also the corresponding Scala ticket: https://issues.scala-lang.org/browse/SI-9247

**Comment by cswinter** [comment]
Thanks for reporting this. It looks like the issue is with scastie.org using an old dotty build or something.

The dotty example project doesn't work for me either, I've opened [#1451](https://github.com/lampepfl/dotty/issues/1451) to track that issue. Note that you can just use the dotty compiler directly as described [here](https://github.com/lampepfl/dotty/wiki/Getting-Started#to-get-started) (there is even a working REPL).

**Comment by julienrf** [comment]
Indeed, I was finally able to run the dotty compiler and the code works fine.
