### ISSUE TITLE
Missed match on Array(1L) in Scala 3.1.1

### ISSUE THREAD

**Issue by devlaam** [lampepfl/dotty#14693]
## Observation

Consider the following code:
```scala
object MatchTest { 
  val a: Array[Long] = Array(1L)

  def test(x: Any) = x match { 
    case Array(i: Long) => println("Success!")
    case _              => println("Failure!") }

  def main(args: Array[String]): Unit = test(a) }
```
When run under [Scala 2.13.8](https://scastie.scala-lang.org/tEFTcPyhQ4CZCqo9nr183w) this produces `Success` whereas under [Scala 3.1.1](https://scastie.scala-lang.org/lBxvAXaEROmHNElxbaeBSQ) it produces `Failure`. For the latter [it does not matter](https://scastie.scala-lang.org/GBpXr4AKRe6uNyKhybXqIQ) if the compiler option `-source:3.0-migration` is used. 

## Expectation
Same behaviour under both versions or (at least) a warning that the match will fail. Current situation significantly changes runtime behaviour after migrating projects from Scala 2 to Scala 3.

**Comment by som-snytt** [comment]
```
Welcome to Scala 3.1.3-RC1-bin-SNAPSHOT-git-5fcfeec (17.0.2, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> (Array(42L): Any) match { case Array(x: Long) => x }
scala.MatchError: [J@75add13c (of class [J)
  ... 33 elided

scala> Array(42L) match { case Array(x: Long) => x }
val res1: Long = 42
```

**Comment by devlaam** [comment]
Thank you for taking this on. Maybe you can, while you are at it, also have a look at the situation were `IArray` is used instead of `Array`. 
```scala
object MatchTest { 
  val a: IArray[Long] = IArray(1L)

  def test(x: Matchable) = x match { 
    case IArray(i: Long) => println("Success!")
    case _               => println("Failure!") }

  def main(args: Array[String]): Unit = test(a) }
```
This[ already produces](https://scastie.scala-lang.org/vuO7eND9QP2bWoKaSKojlA) the desired result `Success` under Scala 3.1.1, but there are some warnings:
```
[warn] -- [E165] Type Warning: src/main/scala/Main.scala:5:19 
[warn] 5 |    case IArray(i: Long) => println("Success!")
[warn]   |                   ^^^^
[warn]   |        pattern selector should be an instance of Matchable,,
[warn]   |        but it has unmatchable type Array.UnapplySeqWrapper[?]#T instead
```
```
[warn] -- [E165] Type Warning: src/main/scala/Main.scala:30:45 
[warn] 8 |  def main(args: Array[String]): Unit = test(a) }
[warn]   |                                             ^
[warn]   |                        value should be an instance of Matchable,,
[warn]   |                        but it has unmatchable type IArray[Long] instead
```

These warnings may be understandable, given [The Matchable Trait](https://docs.scala-lang.org/scala3/reference/other-new-features/matchable.html) definition, but the question is, is this what we expect? The match seems safe enough to me, and certainly does not suffer from the loophole discussed therein. Or put differently, if this is not possible when "warnings are errors", what should you do? 
```
[warn] -- Unchecked Warning: /Volumes/DATA/Sense2Act/Software/ws-scala/scala3/src/main/scala/Main.scala:27:9 
[warn] 5 |    case IArray(i: Long) => println("Success!")
[warn]   |         ^
[warn]   |         the type test for IArray[Any] cannot be checked at runtime
```
This warning puzzels me. Is this not exactly what just happend?

**Comment by smarter** [comment]
The IArray thing seems unrelated to me and it's best not to conflate issues to avoid confusion, especially here when one of these issues is a clear regression and the other is related to a new feature, so please consider opening a separate issue to discuss this.

**Comment by devlaam** [comment]
Understandable, shall we delete the posts then, just to keep this clean?

**Comment by smarter** [comment]
I'll hide as "Off-Topic" :).

**Comment by smarter** [comment]
I think the problem is with the definition of Array.unapplySeq, if I tweak it like this:
```diff
diff --git src/library/scala/Array.scala src/library/scala/Array.scala
index 14cdabd385..a64ae3cb8c 100644
--- src/library/scala/Array.scala
+++ src/library/scala/Array.scala
@@ -574,9 +574,9 @@ object Array {
    *  @param x the selector value
    *  @return  sequence wrapped in a [[scala.Some]], if `x` is an Array, otherwise `None`
    */
-  def unapplySeq[T](x: Array[T]): UnapplySeqWrapper[T] = new UnapplySeqWrapper(x)
+  def unapplySeq[T](x: Array[? <: T]): UnapplySeqWrapper[T] = new UnapplySeqWrapper(x)

-  final class UnapplySeqWrapper[T](private val a: Array[T]) extends AnyVal {
+  final class UnapplySeqWrapper[T](private val a: Array[? <: T]) extends AnyVal {
     def isEmpty: false = false
     def get: UnapplySeqWrapper[T] = this
     def lengthCompare(len: Int): Int = a.lengthCompare(len)
```
Then the pattern match succeeds. Otherwise, depending on how unapplySeq is instantiated, we'll end up matching either all arrays or only arrays of objects, because `Array[Any]` erases to `Object[]`. Note that the behavior of Scala 2 here seems to be a straight-up bug: if I look at the generated tree it tries to do an `isInstanceOf` check on `Array[T]` but there is no `T` in scope (as pointed out by `-Ycheck:pat`), but luckily for Scala 2, it happens to erase this malformed type to `Object` so the check succeeds.

I believe this would be a binary-compatible change, so there's a chance we could just apply this diff in the Scala 2 standard library.

**Comment by smarter** [comment]
https://github.com/scala/scala/pull/9977

**Comment by smarter** [comment]
I've just now realized that the way we type Array.unapplySeq pattern is specific to the fact that it's define in a Scala 2 class, if I define my own extractor, then the match succeeds:
```scala
object UnapSeq {
  def unapplySeq[T](x: Array[T]): Array.UnapplySeqWrapper[T] = new Array.UnapplySeqWrapper[T](x)
}

object Test {
  val a: Array[Long] = Array(1L)

  def test(x: Any) = x match { 
    case UnapSeq(i: Long) => println("Success!")
    case _                => println("Failure!") }

  def main(args: Array[String]): Unit = test(a)
}
```
The culprit is the use of fromScala2x in https://github.com/lampepfl/dotty/blob/fb7f900667ea57e78a098e4831be36e0a7da6cba/compiler/src/dotty/tools/dotc/typer/Applications.scala#L1346
If I replace it by `false`, then the Array.unapplySeq argument is inferred to be a fresh pattern bound type variable `T$1` instead of `Any` and `Array[T$1]` erases to `Object` as expected. So ironically, a flag that is supposed to improve Scala 2 compatibility ends up changing semantics to not match what either of Scala 2 and 3 do by default.
There's no documentation for the behavior of fromScala2x currently, but historically it seems like it was needed to deal with `::` in the Scala <= 2.12 standard library: https://github.com/lampepfl/dotty/commit/9ea9ef413e6590c33321ccd9325fde00ba376def#diff-8893c00063ce469a750bdbdbca40265550e0901a39a8a45e2f83aa6d51230aa0L932

@odersky do you think we could get rid of fromScala2x in typedUnapply or at least tweak it to fix this?
