### ISSUE TITLE
Name shadowing in extension methods

### ISSUE THREAD

**Issue by oscar-broman** [lampepfl/dotty#14777]
## Compiler version

Two extension methods sharing the same name can't be imported into scope. 

## Minimized code

```Scala

case class Foo(value: Double)
object FooExtensions {
  extension (b: Foo) {
    def map(op: Double => Double) = op(b.value)
  }
}

case class Bar(value: Double)
object BarExtensions {
  extension (b: Bar) {
    def map(op: Double => Double) = op(b.value)
  }
}

val f = Foo(1)
val b = Bar(1)
import FooExtensions.*
import BarExtensions.*
f.map(_ + 5)
b.map(_ + 5)
```

## Output

```
[error]    |  f.map(_ + 5)
[error]    |  ^^^^^
[error]    | value map is not a member of Foo.
[error]    | An extension method was tried, but could not be fully constructed:
[error]    |
[error]    |     BarExtensions.map(f)    failed with
[error]    |
[error]    |         Reference to map is ambiguous,
[error]    |         it is both imported by import FooExtensions._
[error]    |         and imported subsequently by import BarExtensions._
```

## Expectation
No error

**Comment by prolativ** [comment]
I'm no sure if there's a non-hacky way to make this work like this as by design extension methods can be also used as ordinary methods, e.g.
```scala
val f = Foo(1)
val b = Bar(1)
import FooExtensions.*
import BarExtensions.*
map(f)(_ + 5)
map(b)(_ + 5)
```
 so importing directly 2 extension methods with the same name and attempting to call them causes the same ambiguity as in case of ordinary methods.
The easiest workaround is to define extension methods inside given instances like this https://github.com/lampepfl/dotty/issues/13613
Then they can be used as extensions without polluting the namespace if you bring the given instances into scope instead of importing the extension methods, e.g.
```scala
case class Foo(value: Double)
given FooExtensions: {} with {
  extension (b: Foo) {
    def map(op: Double => Double) = op(b.value)
  }
}

case class Bar(value: Double)
given BarExtensions: {} with {
  extension (b: Bar) {
    def map(op: Double => Double) = op(b.value)
  }
}

val f = Foo(1)
val b = Bar(1)
f.map(_ + 5)
b.map(_ + 5)
```
In this particular example you don't even have to import anything because `FooExtensions` and `BarExtensions` are already in scope

**Comment by odersky** [comment]
That's as specced, I am afraid. Extension methods are represented as normal methods, so this is inevitable.

**Comment by som-snytt** [comment]
I'd like to add a few words to the docs on "avoid the import tax", which is more of a tariff in Scala 3, but I'm not yet sure where.

The [book](https://docs.scala-lang.org/scala3/book/ca-extension-methods.html) says use imports and also says the compiler will suggest an import.

Scala 2 has a [FAQ](https://docs.scala-lang.org/tutorials/FAQ/index.html#where-does-scala-look-for-implicits) on implicit scope that delegates to SO.

The Scala 3 item would be: "How can I make sure my extension method is applicable at the point of reference?" and would offer a summary of the reference.

I would also document the wonky refinement syntax. There is something about empty braces that makes you feel smarter, like listening to Mozart.

**Comment by oscar-broman** [comment]
So after finally no longer suffering implicit name shadowing, we now have to endure this! Unfortunate. The spec should be changed.
