### ISSUE TITLE
Regression: cannot unify wildcard types

### ISSUE THREAD

**Issue by Atry** [lampepfl/dotty#14790]
## Compiler version

3.1.1
## Minimized code

```Scala
trait Monad[F[_]] {
  def bind[A, B](fa: F[A])(f: A => F[B]): F[B]
  
  def wildcardBind[A, B](fa: F[_ <: A])(f: A => F[B]): F[B] = {
    bind(fa)(f)
  }
}
```

## Output

```scala
Found:    (fa : F[? <: A])
Required: F[A²]

where:    A  is a type in method wildcardBind
          A² is a type variable
          F  is a type in trait Monad with bounds <: [_] =>> Any
```

https://scastie.scala-lang.org/GJZT8xnZSNeVlD3xCriWVA

## Expectation

It should compile because the same code compiles in Scala 2.13.8

https://scastie.scala-lang.org/Ss2Rs5fjS0OWIOxhFff7sA

**Comment by smarter** [comment]
Scala 3 does not support wildcards as arguments to abstract type constructors (because they're equivalent to supporting existential types which we chose to leave out of the language), even if your expression typechecked, the next compiler would emit an error "unreducible application of higher-kinded type F to wildcard arguments". When a wildcard only appears in argument position you can normally replaces it with an extra type parameter:
```scala
trait Monad[F[_]] {
  def bind[A, B](fa: F[A])(f: A => F[B]): F[B]
  
  def wildcardBind[A, B, X <: A](fa: F[X])(f: A => F[B]): F[B] = {
    bind(fa)(f)
  }
}
```

**Comment by smarter** [comment]
But also, this method shouldn't be necessary at all in Scala 3: type inference works across parameter lists so you should be able to just use `bind`.

**Comment by Atry** [comment]
Thank you!
