### ISSUE TITLE
Spurious "Unreachable case" warning in a match on an ADT

### ISSUE THREAD

**Issue by cb372** [lampepfl/dotty#14807]
## Compiler version

3.1.1

## Minimized code

```Scala
enum Foo:
  case One(value: String)
  case Two(value: Long, month: java.time.Month)

object Issue:

  def doSomething(foo: Foo): String = foo match {
    case Foo.One(x)    => s"1 $x"
    case Foo.Two(x, y) => s"2 $x $y"
  }
```

## Output

```scala
[warn] ./patmatbug.scala:9:10: Unreachable case
[warn]     case Foo.Two(x, y) => s"2 $x $y"
[warn]          ^^^^^^^^^^^^^
```

## Expectation

Compiles without warnings, like Scala 2.13.

## Notes

Surprisingly, if I switch the lines around to make `case Foo.Two(x, y)` the very first case in the match, the warning goes away.

**Comment by anatoliykmetyuk** [comment]
Minimized to:

```scala
case class Two(month: java.time.Month)

def doSomething(foo: Any) = foo match
  case Two(x) =>
  case _ =>
```

Intermediate cause:

https://github.com/lampepfl/dotty/blob/4a96ce7374cdb258c22facd18925583a5e09adaa/compiler/src/dotty/tools/dotc/transform/patmat/Space.scala#L629

The pattern matcher tries to see if the space of all values covered by `Month` is empty. If it is, then the case is declared unreachable. One of the rules of such an inference for Java enums is to see if the list of their cases is empty. If it is, the space of the entire enum is assumed empty.

In this case, on the line above, the decomposition algorithm thinks that the `Month` enum is empty since `tp.classSymbol.children` is an empty list – although it shouldn't be.

The question is why is it empty?

**Comment by odersky** [comment]
The children in the original enum case are not empty, though. I see: `List(class One, class Two)`.

**Comment by odersky** [comment]
> Surprisingly, if I switch the lines around to make case Foo.Two(x, y) the very first case in the match, the warning goes away.

I could not reproduce that either. For me, the warning appears no matter what the case ordering is.

**Comment by dwijnand** [comment]
Yeah, I changed the way warnings are emitted so those reorderings don't affect the behaviour, but I'm guessing that fix isn't released or wasn't the version Chris was running.

I'll look into why Month has no children, which I agree with @anatoliykmetyuk seems like is the root cause.  On the side, I think the behaviour of considering the case unreachable if it contains an uninhabited type seems reasonable to me: like a sealed trait with no children should cause the outer case to be unreachable.

**Comment by odersky** [comment]
`Month` has no children since it is a java class. We record children only for sealed classes. For other classes we cannot possibly do that, since children might be in separate compilation units that we have not seen.

**Comment by anatoliykmetyuk** [comment]
> Month has no children since it is a java class. We record children only for sealed classes. For other classes we cannot possibly do that, since children might be in separate compilation units that we have not seen.

This means the following code is wrong by definition:

https://github.com/lampepfl/dotty/blob/4a96ce7374cdb258c22facd18925583a5e09adaa/compiler/src/dotty/tools/dotc/transform/patmat/Space.scala#L628-L629

It will always have empty children.

**Comment by odersky** [comment]
Ah, I guess Java enums should have children. Not sure whether that's the case in general.

**Comment by kitlangton** [comment]
Also running into this issue, though with a different ADT.
