### ISSUE TITLE
inline match cannot destructure a list

### ISSUE THREAD

**Issue by strelec** [lampepfl/dotty#14917]
## Compiler version

3.1.1

## Minimized code

```Scala
inline def create(inline list: List[String]): Unit =
  inline list match {
    case Nil =>
    case s :: rest =>
      println(s)
      create(rest)
  }

create(List("a", "b"))
```

## Output

```
cannot reduce inline match with
 scrutinee:  List.apply[String](["a","b" : String]*) : List[String]
 patterns :  case Nil
             case ::.unapply[String](s @ _, rest @ _):::[String]
```

## Expectation

Same as if you remove all `inline` keywords, two printed strings.

**Comment by bishabosha** [comment]
I don't think this is an issue because inline match can only work on the static type of a value. `List("a", "b")` has the type `List[String]` which can not be further inspected. Additionally, if we expanded inline match to look at the expression of the passed argument, then `List.apply("a", "b")` is not the same as `"a" :: "b" :: Nil`, so your match would need to use a `case List(x, xs*)` pattern.
