### ISSUE TITLE
Regression: scala fails to extend a Java class

### ISSUE THREAD

**Issue by rcano** [lampepfl/dotty#15199]
## Compiler version

3.1.+ all the way to  3.1.3RC

## Minimized code

```Scala
class MyTabbedPaneUI extends javax.swing.plaf.metal.MetalTabbedPaneUI {}
```

## Output

```scala
bridge generated for member object TabbedPaneLayoutMetalTabbedPaneUI.this.TabbedPaneLayout in class MetalTabbedPaneUI
which overrides object TabbedPaneLayoutBasicTabbedPaneUI.this.TabbedPaneLayout in class BasicTabbedPaneUI
clashes with definition of the member itself; both have erased type MetalTabbedPaneUI.this.TabbedPaneLayout."
```

## Expectation

It should compile.

**Comment by sjrd** [comment]
This already fails in 3.0.0 and 3.0.2. It's a regression wrt. Scala 2.x. 2.13.8 successfully compiles this snippet.

The `TabbedPaneLayout` it complains about is an inner class of two superclasses: `MetalTabbedPaneUI#TabbedPaneLayout`, but also `BasicTabbedPaneUI#TabbedPaneLayout`. Hence the clash. But no bridge should be generated for those things in the first place, since they're Java inner classes, not terms.

**Comment by rcano** [comment]
> This already fails in 3.0.0 and 3.0.2. It's a regression wrt. Scala 2.x. 2.13.8 successfully compiles this snippet.
> 
> The `TabbedPaneLayout` it complains about is an inner class of two superclasses: `MetalTabbedPaneUI#TabbedPaneLayout`, but also `BasicTabbedPaneUI#TabbedPaneLayout`. Hence the clash. But no bridge should be generated for those things in the first place, since they're Java inner classes, not terms.

Interesting, it did compile on 3.0.0-RC1, I had a project at that version and found the issue when updating.
