### ISSUE TITLE
Invalid generic signature for type params bounded by primitive

### ISSUE THREAD

**Issue by scf37** [lampepfl/dotty#15385]
## Compiler version

3.1.6

## Minimized code

```Scala
def foo[A <: Int]: A = ???
```

## Output

```java
public <A> A foo() {
    throw Predef$.MODULE$.$qmark$qmark$qmark();
}
```

## Expectation
```java
public int foo() {
    throw Predef$.MODULE$.$qmark$qmark$qmark();
}
```

It is important for performance of code dealing with types carrying meta-information like
```scala
type Validated[A] = A
opaque type Max[A, max] <: A with Validated[A] = A
```

**Comment by nicolasstucki** [comment]
That example seems to compile using the primitive type. Though a slightly different example does not.
```scala
class Foo:
  def foo[A <: Int]: A = ???
  def bar[A <: Int](a: A): A = ???
```

```java
public class Foo {
  public Foo();
  public int foo();
  public <A> A bar(A);
}
```

**Comment by smarter** [comment]
Both of the methods here have`A` erased to `Int` (see the `descriptor` in the output of `javap`), the problem is that the generic java signature we generate for `bar` is incorrect (this is what `javap` uses to display the method signature but it's not the actual bytecode signature, it's only used by javac), A shouldn't be preserved in `Signature` when its upper-bound is a primitive type:
```scala
% javap -p -v Foo.class
[...]
  public int foo();
    descriptor: ()I
[...]
  public <A extends java.lang.Object> A bar(A);
    descriptor: (I)I
[...]
    Signature: #28                          // <A:Ljava/lang/Object;>(TA;)TA;
[...}
```
The same bug exists in Scala 2: https://github.com/scala/bug/issues/9846
