### ISSUE TITLE
The scala document not match the right @main method define

### ISSUE THREAD

**Issue by cnmade** [lampepfl/dotty#15586]
## Compiler version
```
scala 3.1.3
$ scalac --version
Scala compiler version 3.1.3 -- Copyright 2002-2022, LAMP/EPFL
$ sbt --version
sbt version in this project: 1.6.2
sbt script version: 1.6.2
```
## Minimized code
https://docs.scala-lang.org/scala3/book/taste-hello-world.html
The document show not right code, which not equals the java public static void main 

which will cause sbt assembly can not know the entry method.

The current document:

```Scala
@main def hello() = println("Hello, world!")

```

What the really equals code [as for java]

```Scala
object main:
  def main(args: Array[String]): Unit  =
    println("hello world")
```

## Output

```scala
#java -jar target/scala-3.1.3/myapp-assembly-0.1.0-SNAPSHOT.jar
Error: Main method not found in class com.example.main, please define the main method as:
   public static void main(String[] args)
or a JavaFX application class must extend javafx.application.Application
```

## Expectation

```scala
 $ java -jar target/scala-3.1.3/myapp-assembly-0.1.0-SNAPSHOT.jar
 hello world
```

`@main` works without inside `object class`;
so my request is: why `@main`  can not working the same , with or without the  `object main`

The document told us: 
    A [@main](https://scala-lang.org/api/3.x/scala/main.html) annotated method can be written either at the top-level or in a statically accessible object.
https://docs.scala-lang.org/scala3/reference/changed-features/main-functions.html

No , it is not right, it only can work at top level, if put `@main` inside a statically accessible object, it won't compile right 
 

```scala
object main:
  @main def hello(): Unit  =
```

The generate class file

```java
$ javap -c main.class
Compiled from "main.scala"
public final class info.bsmi.sc3.main {

  public static void hello();
    Code:
       0: getstatic     #13                 // Field info/bsmi/sc3/main$.MODULE$:Linfo/bsmi/sc3/main$;
       3: invokevirtual #19                 // Method info/bsmi/sc3/main$.hello:()V
       6: return
```

**Comment by cnmade** [comment]
I used javap to view the compiled class file 
```java
 $ javap -c info.bsmi.sc3.main
Compiled from "main.scala"
public final class info.bsmi.sc3.main {
  public static info.bsmi.sc3.EmailService emailService();
    Code:
       0: getstatic     #13                 // Field info/bsmi/sc3/main$.MODULE$:Linfo/bsmi/sc3/main$;
       3: invokevirtual #15                 // Method info/bsmi/sc3/main$.emailService:()Linfo/bsmi/sc3/EmailService;
       6: areturn

  public static java.lang.String htrName();
    Code:
       0: getstatic     #13                 // Field info/bsmi/sc3/main$.MODULE$:Linfo/bsmi/sc3/main$;
       3: invokevirtual #19                 // Method info/bsmi/sc3/main$.htrName:()Ljava/lang/String;
       6: areturn

  public static void main(java.lang.String[]);
    Code:
       0: getstatic     #13                 // Field info/bsmi/sc3/main$.MODULE$:Linfo/bsmi/sc3/main$;
       3: aload_0
       4: invokevirtual #23                 // Method info/bsmi/sc3/main$.main:([Ljava/lang/String;)V
       7: return

  public static java.lang.String msg();
    Code:
       0: getstatic     #13                 // Field info/bsmi/sc3/main$.MODULE$:Linfo/bsmi/sc3/main$;
       3: invokevirtual #26                 // Method info/bsmi/sc3/main$.msg:()Ljava/lang/String;
       6: areturn
}
```

it show the equals to java code
```
public static void main(java.lang.String[]);
```

**Comment by rochala** [comment]
Thanks for reporting. I looked into the issue and it looks like `@main` annotation inside object generate new top level class with name taken from `@main` method. The tree for this snippet:
```scala
object Test:
  @main def hello(): Unit = ???
```

Transforms into:
```scala
package <empty> {
  final lazy module val Test: Test = new Test()
  final module class Test() extends Object() { this: Test.type =>
    @main def hello(): Unit = ???
  }
  final class hello() extends Object() {
    <static> def main(args: Array[String]): Unit =
      try Test.hello() catch
        {
          case error @ _:scala.util.CommandLineParser.ParseError =>
            scala.util.CommandLineParser.showError(error)
        }
  }
}
```
This error appeared because you explicitly provided `mainClass` option with parent object of `@main` method.
If you have set it to `com.example.hello` everything would work correctly.

The question is: Was it intended to be that way ? According to documentation it is intended to do that: 
```The Scala compiler generates a program from a [@main](https://scala-lang.org/api/3.x/scala/main.html) method f as follows:

    It creates a class named f in the package where the [@main](https://scala-lang.org/api/3.x/scala/main.html) method was found
    The class has a static method main with the usual signature. It takes an Array[String] as argument and returns [Unit](https://scala-lang.org/api/3.x/scala/Unit.html).
    The generated main method calls method f with arguments converted using methods in the [scala.util.CommandLineParser](https://scala-lang.org/api/3.x/scala/util/CommandLineParser$.html) object.
```

Maybe there are some improvements to be made as this is counter intuitive that defined @main method is not generated as main inside it's parent object. @anatoliykmetyuk

**Comment by cnmade** [comment]
@rochala for short, you means we can not have a `Object main`? 

That's not good ...

**Comment by rochala** [comment]
@cnmade No, maybe I wasn't clear enough. It is possible but current design explicitly states that it creates new class in package where it was declared. Lets wait for Anatolii response what should be done with that but in my opinion `@main` annotations should be contained inside their parents to match source code.

**Comment by som-snytt** [comment]
The current design is simple and predictable.

If a `def main` is generated in the enclosing object, what if it already has a method called `main`? The current design offers good hygiene by not answering that question.

The entry point required by JVM is arbitrary. There is no inherent expectation that it corresponds to an object in Scala.

The weird thing is that writing `object Main` with a `main` method winds up with a static forwarder on a class named `Main` and that works as an entry point.

The doc is pretty clear: "The name of the program is in each case the name of the method, without any object prefixes."

https://dotty.epfl.ch/docs/reference/changed-features/main-functions.html

The generated class "quarantines" the JVM boilerplate rather than mucking with the enclosing object. There are probably considerations for other platforms, too. I haven't followed the latest designs for `@main`, so I don't know if that thread has more to say about this question.

Probably the doc just needs a clear example for the use case.

**Comment by anatoliykmetyuk** [comment]
@nicolasstucki do you know what was the reason for the decision to generate the `@main` method boilerplate in a separate class as opposed to the enclosing class where `@main`-annotated method was defined?

**Comment by odersky** [comment]
We want to have several main methods. The decision to name the class after the method is really the core of the design.

**Comment by michelou** [comment]
See also section "A.12.4 The Oberon Environment" in document [Oberon Language Definition](https://link.springer.com/content/pdf/bbm%253A978-3-642-97479-3%252F1.pdf) for people (much) younger than Martin and myself :wink:
