### ISSUE TITLE
No `Enum` flag in the enum value type when mixing with some trait

### ISSUE THREAD

**Issue by plokhotnyuk** [lampepfl/dotty#16008]
Having definition:
```scala
trait MyMarker

enum MyEnum(val value: String):
  case Marked extends MyEnum("marked") with MyMarker
```
I got `Flags.EmptyFlags` instead of `Flags.Enum` in the following call for:

`TypeRepr.of[Marked].typeSymbol.flags`

**Comment by nicolasstucki** [comment]
`Marked` is becomes a `val` case in the `enum` desugaring. This means that `TypeRepr.of[Marked]` or probably `TypeRepr.of[Marked.type]` is a  `TermRef`. Therefore to get its symbol we need to use `termSymbol` instead of `typeSymbol`. The term symbol of `Marked` does contain the `Enum` flag.


Note that `typeSymbol` works in the simple cases because the `val` has a single class as a type and we can resolve the symbol. In this case we cannot resolve the type symbol because we have both `MyEnum & MyMarker`.

**Comment by plokhotnyuk** [comment]
@nicolasstucki Thanks for the clear explanation!

Closing as not a bug.
