### ISSUE TITLE
Match type widens the resulting type

### ISSUE THREAD

**Issue by peter-jerry-ye** [lampepfl/dotty#16038]
## Compiler version

3.2.0

## Minimized code

```Scala
enum A {
  case AA
  case AB
}
enum B {
  case BA
  case BB
  case BC
}
type P[X <: A] = X match {
  case A.AA.type => B.BA.type | B.BB.type
  case A.AB.type => B.BC.type
}
def p[X <: A](x: X): P[X] = x match {
  case x: A.AA.type => B.BA
  case x: A.AB.type => B.BC
}
p[A.AA.type](A.AA) // widened, BA: B
p[A.AB.type](A.AB) // widened, BC: B

sealed trait C
object CA extends C
object CB extends C
object CC extends C
type P2[X <: A] = X match {
  case A.AA.type => CA.type | CB.type
  case A.AB.type => CC.type
}
def p2[X <: A](x: X): P2[X] = x match {
  case x: A.AA.type => CA
  case x: A.AB.type => CC
}
p2[A.AA.type](A.AA) // widened, CA: C
p2[A.AB.type](A.AB) // not widened, CC: CC
```

## Expectation
I expect them not to be widened.

**Comment by SethTisue** [comment]
Is this truly minimized? Sometimes it's good to have not-strictly-minimal code in a report because the longer version shows programmer intent. But we also want to have the aggressively minimized version.

As I attempted to minimize this further, I found myself doubting that this report has anything to do with match types. Maybe I'm missing something, but it seems to me like you may simply be reporting this behavior:

```
scala> enum B { case BC }
// defined class B

scala> def foo = (??? : B.BC.type)
def foo: B
```

which has nothing to do with match types at all — it's simply the compiler's unwillingness to infer singleton types.

How is it that you're determining that unwanted widening is happening? Your test case has comments like `widened, CA: C`, but how did you determine that occurred?

**Comment by SethTisue** [comment]
> it's simply the compiler's unwillingness to infer singleton types

Like, is the idea here that it _should_ be willing to infer one if the singleton type came from out of a match type? Something like that? If so, that seems like a design change rather than a bugfix per se.

**Comment by peter-jerry-ye** [comment]
After some further testing, I think you have a point. So I further minimized the code, I get:
```scala
enum A {
  case AA
  case AB
  case AC
}

def f: A.AA.type | A.AB.type = A.AA
f // AA: A
def g: Int | String = 1
g // 1: scala.Int | scala.Predef.String
```
So it's not related to the match type. Even without match type, the union type gets widened.

So is that behavior a design choice?

-------
By the way, in your example, you had:
```scala
scala> def foo = B.BC: B.BC.type
def foo: B
```
But if we move the type signature:
```scala
scala> def foo : B.BC.type = B.BC
def foo: B.BC.type
```
which also seems curious for me.

**Comment by dwijnand** [comment]
> ```scala
> def f: A.AA.type | A.AB.type = A.AA
> f // AA: A
> def g: Int | String = 1
> g // 1: scala.Int | scala.Predef.String
> ```
>   
> So it's not related to the match type. Even without match type, the union type gets widened.
> So is that behavior a design choice?

It's not the union that gets widened, it's the individual types that do.  Basically singleton types, except for those on actual objects, get widened to their underlying type.  so what happens on line 2 ("f") is that `AA.type | AB.type` becomes `A | A` which simplifies to `A`.  Non-object singletons widening is desired behaviour, always has been.  For instance literals, which is one type of singleton, we want "foo" to be String and 1 to be Int, not the singleton types `"foo"` and `1`.  What's new is that enum cases aren't modules, their just values, so they widen as such.

> By the way, in your example, you had:
> 
> ```scala
> scala> def foo = B.BC: B.BC.type
> def foo: B
> ```
> 
> But if we move the type signature:
> 
> ```scala
> scala> def foo : B.BC.type = B.BC
> def foo: B.BC.type
> ```
> 
> which also seems curious for me.

That's right, if you have a type annotation, it's precisely typed.  But take one more step that requires inference and it's gone, if there's no annotation:

```scala
scala> def foo: B.BC.type = B.BC
def foo: B.BC.type

scala> def bar = foo
def bar: B
```

---

Seth and I discussed it and I made that argument that if I have a `def p` that defines it's result using a match type that precisely defines a singleton type then the type the method usage should infer.  But now I'm not so sure if that moves the needle in any significant way because, again, one more step and the preciseness is gone...  Unless we never reduce the match type and just keep the value typed as `P[A.AA.type]`, but no one wants that either.

I don't think there's a bug or change we want here.

**Comment by peter-jerry-ye** [comment]
I honor your decision, but personally I think that if one wants to be able to do some dependently typed programming with Scala, precision type should be guarded, or be enabled with some kind of compiler parameter if possible. In my humble opinion, one important scenario of match type is dependent typing.

**Comment by som-snytt** [comment]
There are many tickets about enums, unions, widening, and inference as an intersection of features.

It would be nice if there were a FAQ page summarizing the common questions. That page could also clarify what is "established behavior" and what might be "avenues of research". In particular, it could list the use cases and the idioms.

The other new bit is that enums are preferentially widened, as mentioned in the docs.

(I started listing things that could go in the FAQ, after reading some tickets, but that is tedious and dreary to write and to read.)

On this ticket, the "further minimization" seems uninteresting, so I can't tell if the OP is about the speculative tickets on "more precise types".

But I sympathize with the need for a summary view.

**Comment by dwijnand** [comment]
> I honor your decision, but personally I think that if one wants to be able to do some dependently typed programming with Scala, precision type should be guarded, or be enabled with some kind of compiler parameter if possible. In my humble opinion, one important scenario of match type is dependent typing.

I can believe that, for sure.  @mbovel has been working on things in the general area of preserving precise types.

**Comment by dwijnand** [comment]
> Basically singleton types, except for those on actual objects, get widened to their underlying type.

Tried to find where I'd seen this (while thinking about #16107) and it took me too long.  So, for future reference:

https://github.com/lampepfl/dotty/blob/e587a813d45a237a46dcee56c94ffd93cd4adf77/compiler/src/dotty/tools/dotc/core/ConstraintHandling.scala#L674-L675
