### ISSUE TITLE
Inconsistency in eta-expansion with overloaded methods

### ISSUE THREAD

**Issue by Sporarum** [lampepfl/dotty#16077]
## Compiler version

scalaVersion =  3.2.0 / 3.2.1-RC1

## Minimized code / Output

```Scala
given Int = 5

def f = ???
def f(using Int) = ???

val v = f         // works

def foo(x: Int) = ???
def foo(x: Int)(using Int) = ???

val voo1 = foo    // error: Ambiguous Overload
val voo2 = foo(5) // error: Ambiguous Overload
```

## Expectation

Either `v`, `voo1`, `voo2` all compile, or all fail to compile 

My opinion is that `v` should not compile, which shows the users the second `f` is being shadowed by the first

It also has an impact on (hopefully incoming) polymorphic eta-expansion, as we would like to expand into functions even when no expected type is present. 

The present criteria is "there is at least one explicit term clause"

If there is more than one method that fulfills this criteria, it is much simpler to report an error than to try to select the most specific one, given there is no expected type

**Comment by som-snytt** [comment]
I think the title should say "Consistency"?

The spec drops default args as a consideration in overloading, and similarly for implicit args. The only test is applicability.

```
def f = 42
def f(i: Int) = i+1
```
Since `f` is not an application, I expect it to chose `f` because you can't apply `Int` to it, so `f(Int)` is not as specific.

However, I've forgotten why
```
def f: Int => Int = _ + 1
def f(i: Int) = i + 1
```
is not ambiguous. That is, `f` is not ambiguous, but `f(42)` is ambiguous.

**Comment by Sporarum** [comment]
After discussion with @odersky, I understand some amount of inconsistency like the above is inevitable

This also turns out to not affect polymorphic eta-expansion, as there will always be a term parameter
