### ISSUE TITLE
Lose `experimental` scope while `macro` implementation has  `private`/`protected` modifier

### ISSUE THREAD

**Issue by jilen** [lampepfl/dotty#16091]
## Compiler version

3.2.0
## Minimized code

```Scala
import scala.quoted._
import scala.annotation.experimental

trait Foo {}

object Macro {
 @experimental
  inline def foo() = ${ fooImpl }

  @experimental
  private def fooImpl(using Quotes) = {
    import quotes.reflect._
    val name: String = "TestFoo"
    val parents = List(TypeTree.of[Object])
    val cls = Symbol.newClass(
      Symbol.spliceOwner,
      name,
      parents = parents.map(_.tpe),
      _ => Nil,
      selfType = None
    )
    '{
      new Foo {}
    }
  }
}

```

## Output
Report error 
```
method fooImpl is marked @experimental and therefore may only be used in an experimental scope.
```

## Expectation
```scala
private def fooImpl(using Quotes) = ...
```
Without `private` modifier, this example compiles (even without `@experimental` at call site.).
Should be same with `private` modifier.

**Comment by jchyb** [comment]
I managed to minimize the code further:
```scala
import scala.annotation.experimental

object Macro {
  @experimental
  inline def foo() = fooImpl

  @experimental
  private def fooImpl = ()
}
```
It seems that the mix of `inline` + `private` is the root of this. When reproducing on the dotty main branch it's worth to remember to enable the `-Yno-experimental` option, otherwise everything is in experimental scope and the error does not show (probably obvious to most, but I managed to make the mistake)

**Comment by odersky** [comment]
Nice minimization! 

Inlined `private` methods get inline accessors. I believe that's the source of the problem.
