### ISSUE TITLE
Wrong match case selected

### ISSUE THREAD

**Issue by Bersier** [lampepfl/dotty#16252]
## Compiler version

3.2.0

## Minimized code

```Scala
class Baz:
  inline def foo: Int = bar(zero)
  inline def bar(inline i: Int): Int = inline i match
    case 0 => 0
    case _ => 1
  private inline def zero = 0

println(Baz().foo)
```

## Output

```scala
1
```

## Expectation

```scala
0
```

See also #15893

**Comment by prolativ** [comment]
This used to work in 3.1.3.
This doesn't work in 3.2.2-RC1-bin-20221025-292e56f-NIGHTLY

**Comment by prolativ** [comment]
The problem disappears if we replace `inline def zero` with `inline val zero` or `inline i match` with `i match`

**Comment by KacperFKorban** [comment]
Minimization without running

```scala
class Baz:
  inline def foo: Int = bar(zero)
  inline def bar(inline i: Int): Int = inline i match
    case 0 => 0
    case _ => scala.compiletime.error("XD")
  private inline def zero = 0

@main
def main =
  println(Baz().foo)
```

**Comment by prolativ** [comment]
The regressing commit is 86bb97222a349eefc916339c781b53035c6acfab

**Comment by odersky** [comment]
How important is it? It was @nicolasstucki's commit, and I don't feel confident to propose an alternative. Do we need to revert #15075, reopening the other issue? Or can it wait? It's a difficult tradeoff.

**Comment by odersky** [comment]
In fact, this should never have worked. Or rather, it does only work if the functions are declared `transparent inline`. The reason is that 
```scala
inline def zero = 0
```
reduces to `0: Int`, not `0`. And an `Int` scrutinee cannot distinguish between 0 and not 0. 

Otherwise put, if `zero`  could have selected the right match case, then changing the definition of `zero` to `1` would change the typing if the program. But that's precisely a condition for normal inline functions that they cannot do that.

**Comment by dwijnand** [comment]
It's a little confusing to me that "disjointness" is a factor in match type reduction but not in inline matches.  Makes it more work to remember the different semantics.

**Comment by odersky** [comment]
> It's a little confusing to me that "disjointness" is a factor in match type reduction but not in inline matches. 

I agree. That's something we should discuss.

**Comment by Bersier** [comment]
Could someone explain the resolution? Is this behavior as expected? Why does `private` change the behavior?

**Comment by odersky** [comment]
It probably should not work with public methods either. There's a grey zone where the inline happens to reduce something because of some optimization or other. We might want to track these down and avoid them at some point, but it's tedious work for not much benefit. But in any case, if the method is not transparent, you can rely only on the result type, which is `Int` not `0`.

**Comment by Bersier** [comment]
@odersky thank you for clarifying.

A few more observations:

1. This behavior (and how it differs from match type reduction) [doesn't currently seem to be fully documented](https://docs.scala-lang.org/scala3/guides/macros/inline.html#inline-matches).

2. One would naively assume the inline match to be equivalent to `inline if i == 0 then 0 else 1` (but the latter leads to a compile-time error).

3. In both cases, it also seems at odds with the part of the documentation that says `It guarantees that inlining actually happens instead of being best-effort`. According to that statement, one would naively assume code to reduce somewhat as follows:

```Scala
class Baz:
  inline def foo: Int = bar(zero)
  inline def bar(inline i: Int): Int = inline if i == 0 then 0 else 1
  private inline def zero = 0

println(Baz().foo)
```
`-->` (because `zero` has to be inlined)
```Scala
class Baz:
  inline def foo: Int = bar(0)
  inline def bar(inline i: Int): Int = inline if i == 0 then 0 else 1

println(Baz().foo)
```
`-->` (because `bar` has to be inlined)
```Scala
class Baz:
  inline def foo: Int = inline if 0 == 0 then 0 else 1

println(Baz().foo)
```
`-->` (`inline if` reduction)
```Scala
class Baz:
  inline def foo: Int = 0

println(Baz().foo)
```
`-->` (because `foo` has to be inlined)
```Scala
println(0)
```
