### ISSUE TITLE
Transparent inline given cannot be summoned by type refinements

### ISSUE THREAD

**Issue by johnhungerford** [lampepfl/dotty#16584]
## Compiler version

3.2.1 (JVM)

## Minimized code

```Scala
import scala.compiletime.erasedValue

trait TypeClass[A] { type B }

object TypeClass:
    type Aux[A, Baux] = TypeClass[A] { type B = Baux }

    private type IsTuple[T <: Tuple] = T

    transparent inline given tupleInstance[A]: TypeClass[A] = inline erasedValue[A] match
        case _ : EmptyTuple  => new TypeClass[A] { type B = EmptyTuple }
        case _ : (head *: tail) =>
            type Tail = tail
            inline tupleInstance[Tail] match
                case _ : Aux[_, IsTuple[tailT]] => new TypeClass[A] { type B = Option[head] *: tailT }
    
object Test:
    val summonedInstance1 = summon[TypeClass[(Int, String)]]
    // This compiles
    summon[summonedInstance1.type <:< TypeClass.Aux[(Int, String), (Option[Int], Option[String])]]

    // These two do not compile
    summon[TypeClass.Aux[(Int, String), (Option[Int], Option[String])]]
    summon[TypeClass[(Int, String)] { type B = (Option[Int], Option[String]) }]

```

## Output

```scala
[error] ./TransparentInlineDerive.scala:20:72: No given instance of type TypeClass.Aux[(Int, String), (Option[Int], Option[String])] was found for parameter x of method summon in object Predef
[error]     summon[TypeClass.Aux[(Int, String), (Option[Int], Option[String])]]
[error]                                                                        ^
[error] ./TransparentInlineDerive.scala:21:80: No given instance of type TypeClass[(Int, String)]{B = (Option[Int], Option[String])} was found for parameter x of method summon in object Predef
[error]     summon[TypeClass[(Int, String)] { type B = (Option[Int], Option[String]) }]
[error]
```

## Expectation

I would expect the above to compile.

**Comment by jchyb** [comment]
Hi @johnhungerford, I am afraid this is a correct behavior. The reason why the shown givens are not being found is the fact that `TypeClass[(Int, String)] {type B = (Option[Int], Option[String])}` is not a subtype of `TypeClass[(Int, String)]` (or `TypeClass[A]` parametrized) - when matching givens only the type annotation is being taken into account (which is why you cannot create a given without one), even for transparent inline methods. Only after being chosen could transparent inline methods be executed, and only after that would the compiler know that the returned type is indeed a correct subtype after all.

In the `summon[summonedInstance1.type <:< TypeClass.Aux[(Int, String), (Option[Int], Option[String])]]` example we already know the exact (refined) type from previous execution of the transparent inline method, so compared types are the exact same (`summonedInstance1.type =:= TypeClass[(Int, String)] { type B = (Option[Int], Option[String]) }`)

**Comment by johnhungerford** [comment]
@jchyb understood. Thanks for your explanation! That clarifies a lot.
