### ISSUE TITLE
Unable to call auxiliary constructor on case class

### ISSUE THREAD

**Issue by joeseibel** [lampepfl/dotty#16692]
When trying to construct a case class using an auxiliary constructor, scalac ignores the auxiliary constructor and complains that the supplied arguments do not match the required parameters of the primary constructor.

## Compiler version

3.2.1

## Minimized code

```Scala
case class Foo(a: Int, b: Int):
  def this(a: Int) = this(a, a)

@main def main: Unit =
  val auxiliaryConstructorCall = Foo(3)
  println(auxiliaryConstructorCall)
```

## Compiler Output

```
-- Error: Main.scala:5:36 ------------------------------------------------------
5 |  val auxiliaryConstructorCall = Foo(3)
  |                                 ^^^^^^
  |missing argument for parameter b of method apply in object Foo: (a: Int, b: Int): Foo
1 error found
```

## Workaround

One possible workaround is to explicitly use the `new` keyword. If `Foo(3)` is replaced with `new Foo(3)`, then the example code compiles and runs.

## Expectation

The compiler should be able to find and call the single parameter auxiliary constructor without using the `new` keyword.

**Comment by som-snytt** [comment]
Constructor proxies are generated only if there is not already an `apply` method on the companion.

Since case classes already have a companion `apply`, they never receive constructor proxies.

However, it is allowed to overload the companion `apply`:

```
case class Foo(a: Int, b: Int):
  def this(a: Int) = this(a, a)
object Foo:
  def apply(a: Int) = new Foo(a, a)
```

I don't know if they are willing to relax the rule in order to create a constructor proxy that overloads the existing "real" apply.

https://dotty.epfl.ch/docs/reference/other-new-features/creator-applications.html

**Comment by odersky** [comment]
Yes, I think this is out of scope for a fix.
