### ISSUE TITLE
Unit implicit conversion discrepancy between Scala2 and Scala3

### ISSUE THREAD

**Issue by scf37** [lampepfl/dotty#16711]
## Compiler version

3.2.0

## Minimized code

```Scala
trait A

implicit def stringToA(s: String): A = new A{override def toString = s}
implicit def unitToA(u: Unit): A = new A{override def toString = "Unit"}

val a: A = if (System.nanoTime() != 4) "hello"
println(a)
```

## Output

3.2.0
```scala
Unit
```

2.13.10
```scala
Hello
```

## Expectation

Printing Hello

**Comment by odersky** [comment]
There's a change in type inference between Scala 2 and 3. In Scala 3, the type of a one-armed if is `unit`, whereas in Scala 2 it could be any. Since the type of `if (System.nanoTime() != 4) "hello"` is unit, it must be expanded like this:
```scala
if (System.nanoTime() != 4) { "hello"; () }  else ()
```
And that explains the behavior you are seeing. As far as I can remember this fixes some puzzlers in Scala 2, but I can't say which ones without digging further.
