### ISSUE TITLE
Wrong warning on matching union types

### ISSUE THREAD

**Issue by scf37** [lampepfl/dotty#16899]
## Compiler version

3.2.2

## Minimized code

```Scala
sealed trait Unset

def foo(v: Unset|Option[Int]): Unit = v match
  case v: Unset => ()
  case v: Option[Int] => ()
```
## Output

```scala
the type test for Option[Int] cannot be checked at runtime
```

## Expectation
No warning. Unset is sealed trait and therefore this match should be exhaustive. For example, `v: String|Option[Int]` compiles without warning.

**Comment by SethTisue** [comment]
Agree this is a bug.

**Comment by SethTisue** [comment]
Agree this is a bug, and significant enough that I hope to see it get attention.

Partly because it came up on Discord today, so that's a second user who hit it.

I see there was an attempt to fix it which is now abandoned. I also see @dwijnand was interested enough to comment on the PR. Dale, not sure your remaining level of interest.

**Comment by liufengyun** [comment]
Also encountered this one. It's a little annoying. Working on a fix.
