### ISSUE TITLE
a trait that has multiple parameter lists method, object override compile failed, but for anonymous compile succeed.

### ISSUE THREAD

**Issue by gfZeng** [lampepfl/dotty#17010]
## Compiler version
`3.2.2`

## Minimized code

```scala
object OverrideDemo {
  trait Foo {
    def foo(a: String): Unit
    def foo(a: String)(b: String): Unit = foo(a + b)
  }

  object foo1 extends Foo {
    override def foo(a: String): Unit = ()
  }

  val foo2 = new Foo {
    override def foo(a: String): Unit = ()
  }


  foo1.foo("")("")  //  compile failed
  foo2.foo("")("") // compile succeed

}
```

**Comment by som-snytt** [comment]
That is expected, because `foo1.foo(String)` is more specific than `Foo#foo(String)(...)` by virtue of being defined in subclass `foo1` without considering more than one parameter list.

The successful call relies on choosing `Foo#foo(String)(String)` by virtue of applying two arg lists. `foo2` is inferred `Foo`.

**Comment by gfZeng** [comment]
@som-snytt @Kordyjan 
Weird. we must define like below in object that on our case:
```scala 
override def fn = super.fn
```
