### ISSUE TITLE
Missing generic type in JVM signature of public field

### ISSUE THREAD

**Issue by christian-mibex** [lampepfl/dotty#17069]
## Compiler version

3.2.2

## Minimized code

```Scala
//> using scala "3.2.2"
//> using repository "https://maven.atlassian.com/repository/public"
//> using lib "com.atlassian.bitbucket.server:bitbucket-rest-model:7.14.0"

import com.atlassian.bitbucket.rest.repository.RestRepository
import scala.beans.BeanProperty

case class SomeRequest(
    @BeanProperty var repos: java.util.List[RestRepository]
)
```

## Output
Partial output of `scalap -c -p`
```scala
// public class generic_java_type$u002Esc$SomeRequest implements scala.Product,java.io.Serializable {
//   private java.util.List repos;
//   public java.util.List<com.atlassian.bitbucket.rest.repository.RestRepository> repos();
//     Code:
//        0: aload_0
//        1: getfield      #39                 // Field repos:Ljava/util/List;
//        4: areturn```
```
## Expectation
Scala 2 and Java add the generic type of the java.util.List to the repos field. Changing the version `//> scala 2` in the code above produces:

```scala
// public class generic_java_type$u002Esc$SomeRequest implements scala.Product,java.io.Serializable {
//   private java.util.List<com.atlassian.bitbucket.rest.repository.RestRepository> repos;
//   public java.util.List<com.atlassian.bitbucket.rest.repository.RestRepository> repos();
//     Code:
//        0: aload_0
//        1: getfield      #28                 // Field repos:Ljava/util/List;
//        4: areturn
```

We got hit by this when Jackson was unable to deserialize the class correctly because it could not reflect on the type of the list.

**Comment by prolativ** [comment]
The problem seems to be more general and has nothing to do with `@BeanProperty`. The reproduction could be reduced to just
```scala
class Foo {
    val generic: List[String] = ???
}
```
In the bytecode produced byt scala 3 (starting from 3.0.0 up to the newest nightly) we can see
```
  private final scala.collection.immutable.List generic;
  public scala.collection.immutable.List<java.lang.String> generic();
```
So in general result types of getters have type parameters in signatures but  that's not the case for underlying fields

**Comment by He-Pin** [comment]
Will this be scheduled to the next 3.3.1 version?

**Comment by prolativ** [comment]
This doesn't seem to have very high priority for the core compiler team as the problem has existed since 3.0.0 and nobody even noticed that before. However contributions are welcome 🙂. A fix could go in 3.3.1 if it gets implemented before the branch cut-off for 3.3.1 (which should coincide with the release of stable 3.3.0, so probably in like two weeks unless more regressions appear and we don't manage to fix them on time).

I tried to have a quick look at a potential source of the issue and here are my observations:
A public field like
```scala
val generic: List[String]
```
in the example above is transformed to a method with an additional `<accessor>` flag in `Getters` phase, resulting in something like
```scala
<accessor> def generic: List[String]
```
After the type erasure in `Erasure` phase this becomes
```scala
<accessor> def generic: List
```
Then in `Memoize` phase for each accessor (getter or setter) an underlying field definition is generated so after this phase we have
```scala
<accessor> def generic: List
val generic: List
```
Finally, in `GenBCode` phase, the bytecode is generated. For a field like `val generic` this is done inside `def addClassFields()` in `dotty.tools.backend.jvm.BCodeSkelBuilder`, which in turn invokes `getGenericSignature`. This method tries to look back at the type of a definition before the type erasure (at the beginning of `Erasure` phase). In case of `def generic`, `getGenericSignature` correctly returns `List[String]`. However, for `val generic` it returns just `List`.

My assumption is that as `val generic` did not yet exist during `Erasure` the compiler returns the earliest available type for this definition, which is `List` (as taken from `Memoize`). So one would probably have to somehow associate this synthetic definition with the type of the corresponding def before the erasure.

**Comment by SethTisue** [comment]
(an argument for prioritizing could be that Jackson is very widely used)

**Comment by rjdestigter** [comment]
I'm running into this issue as well when using OptaPlanner. It throws the exception defined [here](https://github.com/kiegroup/optaplanner/blob/main/core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/util/ConfigUtils.java#L383)

**Comment by akorneev** [comment]
We encountered this error while trying to migrate a project (from 2.13) that uses JPA (Hibernate).

This bug seems to break interop with many Java libraries which rely on field types for serialization/persistence.

**Comment by hohonuuli** [comment]
I'm having the same issue as @akorneev (i.e. migrating a JPA project from 2.13 to 3.3.1 fails). I'm hitting this bug with [Gson](https://github.com/google/gson). Sample code to reproduce the reflection issue is on [Stackoverflow](https://stackoverflow.com/questions/77247600/extract-the-java-lang-reflect-type-of-the-parameterized-type-from-an-option-in-s)

**Comment by mbovel** [comment]
@sjrd would you have any guidance about this issue? Do you think it's a hard one?

**Comment by mbovel** [comment]
@EugeneFlesselle @entangled90 @AnotherMedo @Motii1: the issue we were assigned for tonight's Spree has been solved. I therefore suggest we switch to this one. Sorry for the late notice!

If it's anybody's first time hacking on Dotty, you can find information on to get started at https://dotty.epfl.ch/docs/contributing/getting-started.html.

**Comment by mbovel** [comment]
Not sure how to test it. Maybe we could have the following `run` test?

```scala
package fieldType

class Foo:
    val generic: List[String] = ???

@main def test =
    val tpe = classOf[Foo].getDeclaredField("generic").getGenericType()
    val tpe2 = classOf[Foo].getDeclaredMethod("generic").getGenericReturnType()
    assert(tpe == tpe2)
```

**Comment by sjrd** [comment]
Your entry point will be https://github.com/lampepfl/dotty/blob/main/compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala
You'll want to see where `def javaSig` is called and follow the chain. It seems to already be transitively called for fields starting from
https://github.com/lampepfl/dotty/blob/7480582f0c539794c42d2c8b5a28384608d4ec16/compiler/src/dotty/tools/backend/jvm/BCodeSkelBuilder.scala#L403

Then figure out what method in the chain does not get applied correctly.
