### ISSUE TITLE
Path-dependent singleton "x.type" is less powerful than quantifying over the type of x

### ISSUE THREAD

**Issue by EvanMcGorty** [lampepfl/dotty#17085]
## Compiler version

3.2.2

## Minimized code

```Scala
type Not[X <: Boolean] <: Boolean = X match
  case false => true
  case true => false

def goodnot[X <: Boolean](x: X): Not[X] = x match
  case _: false => true
  case _: true => false

def badnot(x: Boolean): Not[x.type] = x match
  case _: false => true
  case _: true => false

val x: Boolean = true
val goodnotnotx: Not[Not[x.type]] = goodnot(goodnot(x)) // OK
val badnotnotx: Not[Not[x.type]] = badnot(badnot(x)) // ERROR: found Not[not(x).type]
```

## Output

```
Found:    Playground.Not[(?1 : Playground.Not[(Playground.x : Boolean)])]
Required: Playground.Not[Playground.Not[(Playground.x : Boolean)]]

where:    ?1 is an unknown value of type Playground.Not[(Playground.x : Boolean)]
```

## Expectation

This should compile?

To me, it is not actually entirely clear that this is a bug, though at the very least it makes this style of path dependent functions (which is very widespread as it is arguably nicer and more convenient) much less usable with match types, which is a shame. There are certainly plenty of special cases (like this one) where dotty *could* allow such code to compile, though the generalized rules for this are far from obvious to me.

In this particular case, perhaps dotty could observe from the definition of ```Not``` that ```Not[x.type] <: Singleton```, and that therefore because ```not(x).type <: Not[x.type] <: Singleton```, logically it must hold that ```not(x).type =:= Not[x.type]```. The issue in general is however likely much more nuanced.

I have not managed to find resources or discussion about this problem anywhere online, so I think it would be sensible to reconcile these two styles of dependent functions somewhere in the documentation, as many users naively using ```.type``` may not realize that their code is being unnecessarily made worse in this way (it certainly was not obvious to me).

**Comment by EvanMcGorty** [comment]
To clarify my suggestion on how this particular case could be fixed, the following changes allow the code to typecheck:
```scala
type Not[X <: Boolean] <: Boolean & Singleton = X match
  case false => true
  case true => false

given [A <: Singleton, B <: A]: (A <:< B) = ???
```
So this simple subtyping rule for instance would fix a class of problems like this

**Comment by sjrd** [comment]
Unless I'm mistaken, `(?1 : Playground.Not[(Playground.x : Boolean)])` is what dotc calls a `SkolemType` internally. It is the singleton type (a stable type) of an unknown value whose underlying type is `Playground.Not[(Playground.x : Boolean)]`. I needs to stabilize the argument `badnot(x)` because it is given as argument to `badnot(y)` whose result type depends on `y`. (That's not the case in `goodnot`.) Stabilization requires the skolem type because `Not[(x: Boolean)]` is not a singleton type.

So to me, everything is behaving as specified. This is definitely not a bug.

---

Could we make it work by changing the spec? I see two options.

First, since `Not[X]` is a function, and `(x: Boolean)` is a singleton type, we could in theory consider `Not[X]` as being a singleton. Or at least, as not requiring stabilization through a `SkolemType`.

Alternatively, if creating the skolem is unavoidable for other reasons, it may be possible to consider that a skolem is equiv to its underlying when the underlying is a singleton type. But that may have deeper consequences.

It's unclear whether we want to go that far. This would be a feature request that alters the Scala type system either way.
