### ISSUE TITLE
Nested match types don't reduce via pattern matching

### ISSUE THREAD

**Issue by EvanMcGorty** [lampepfl/dotty#17080]
## Compiler version

3.2.2

## Minimized code

```Scala
type Not[X <: Boolean] <: Boolean = X match
  case false => true
  case true => false

def not[X <: Boolean](x: X): Not[X] = x match
  case _: false => true // Works!
  case _: true => false // Works!

def id[X <: Boolean](x: X): Not[Not[X]] = x match
  case _: false => false // ERROR
  case _: true => true // ERROR
```

## Output

```
Found:    (false : Boolean)
Required: Playground.Not[Playground.Not[X]]

where:    X is a type in method id with bounds <: Boolean
```
and
```
Found:    (true : Boolean)
Required: Playground.Not[Playground.Not[X]]

where:    X is a type in method id with bounds <: Boolean
```

## Expectation

The match type should either reduce, or the exact behavior of match types should be better documented, as nothing in the documentation indicates that this might not reduce.

**Comment by EvanMcGorty** [comment]
Here is an elaboration/analysis of the above-mentioned problem:

https://scastie.scala-lang.org/nmxq7KBYQXC3Eur4eTNP9w
```scala
// Given the definitions:

enum SBool[X <: Boolean]:
  case SFalse extends SBool[false]
  case STrue extends SBool[true]

type Not[X <: Boolean] <: Boolean = X match
  case false => true
  case true => false
  

// The following functions are valid:

def not[X <: Boolean](x: X): Not[X] = x match
  case _: false => true
  case _: true => false

def snot[X <: Boolean](x: SBool[X]): Not[X] = x match
  case SBool.SFalse => true
  case SBool.STrue => false


// But strangely these functions are not:

def id[X <: Boolean](x: X): Not[Not[X]] = x match
  case _: false => false // ERROR
  case _: true => true // ERROR

def sid[X <: Boolean](x: SBool[X]): Not[Not[X]] = x match
    case SBool.SFalse => false // ERROR
    case SBool.STrue => true // ERROR


// The variation with SBool is especially strange considering a more generalized version typechecks:

def elimSBool[X <: Boolean, F[_ <: Boolean]](x: SBool[X], ff: F[false], ft: F[true]): F[X] = x match
  case SBool.SFalse => ff
  case SBool.STrue => ft

// (this can then be used to indirectly construct a version of 'sid' that typechecks)
def sidViaElim[X <: Boolean](x: SBool[X]): Not[Not[X]] = elimSBool[X, [Y] =>> Not[Not[Y]]](x, false, true)


// And it's possible to work around this whole issue with a helper match type for function application

type ApplyBool[F[_ <: Boolean], X <: Boolean] = X match
  case false => F[false]
  case true => F[true]

def idViaApply[X <: Boolean](x: X): ApplyBool[[A] =>> Not[Not[A]], X] = x match
  case _: false => false
  case _: true => true

// Presumably this works because the type variable being refined is no longer in a nested position.

// Sadly this still isn't a complete workaround as it can't be shown that
//     ApplyBool[[A] =>> Not[Not[A]], X] <:< Not[Not[X]]
// Which seems to me to be the same as issue #16058
```

**Comment by sjrd** [comment]
AFAICT, this is all behaving as specified.

First, it's good to understand why `def not` typechecks:
```scala
def not[X <: Boolean](x: X): Not[X] = x match
  case _: false => true // Works!
  case _: true => false // Works!
```
Clearly, `Not[X]` cannot reduce, since `X` is completely unknown. So how come it allows the `true` on the right-hand side to be a valid term when the expected type is `Not[X]`? The typing rule that allows this is [dependent typing](https://docs.scala-lang.org/scala3/reference/new-types/match-types.html#dependent-typing) of `match` terms. There are four criteria for that rule to apply:

> 1. The match expression patterns do not have guards
> 2. The match expression scrutinee's type is a subtype of the match type scrutinee's type
> 3. The match expression and the match type have the same number of cases
> 4. The match expression patterns are all [Typed Patterns](https://scala-lang.org/files/archive/spec/2.13/08-pattern-matching.html#typed-patterns), and these types are =:= to their corresponding type patterns in the match type

All of these criteria are fulfilled in this case. In particular, criteria 2 is satisfied because the scrutinee of the term match, which is `x`, is a subtype of the strutinee of the match type `Not[X]`, which is `X`.

Therefore, dependent typing of the match term/type pair is applied, and `true` is typechecked against the right-hand-side of `case false => true` from the match type.

---

Now, why does it not work with `id`, which I repeat here:
```scala
def id[X <: Boolean](x: X): Not[Not[X]] = x match
  case _: false => false // ERROR
  case _: true => true // ERROR
```
Criteria 2 is not satisfied here. The term scrutinee `x` is *not* a subtype of the match type scrutinee, which is `Not[X]`. We have no evidence that `x <:< Not[X]` (and in fact, it is clearly not a subtype). Therefore, dependent typing of the match term is not applicable at all.

That means that the term `false` must be typechecked against `Not[Not[X]]`, and since that is not reducible, it is a compile error.

---

What could we improve if we did want to enhance the Scala language to support it? I don't think we can enhance it by making the rules of dependent typing less strict. So what's left? Well, in theory we could make `Not[Not[X]]` reducible.

If we look again at the definition of `Not`:
```scala
type Not[X <: Boolean] <: Boolean = X match
  case false => true
  case true => false
```
we can successively expand `Not[Not[X]]` as follows:
```scala
Not[Not[X]]
  =:= // expanding the other `Not` type lambda
Not[X] match
  case false => true
  case true  => false
  =:= // expanding the other `Not[X]`
(
  X match
    case false => true
    case true  => false
) match
  case false => true
  case true  => false
```
That cannot be reduced or expanded any further using the rules of the Scala type system that are specified today.

We *could* imagine to add a rule to the type system that would *distribute* a match on the branches of its scrutinee when the scrutinee is itself a match. If we did that, we would get:
```scala
X match
  case false =>
    true
      case false => true
      case true  => false
  case true =>
     false
      case false => true
      case true  => false
```
Once that is done, we have reached a situation where criteria 2 from above applies, as the top-level `match` type has the scrutinee `X`. Dependent typing would then apply, and `id` would be allowed to typecheck.

I do not think this is something we want to do. At the very least, it would clearly require changes to the specification by adding more ways that match types can be reduced (i.e., by distribution). So that would require a Pre-SIP etc.

**Comment by EvanMcGorty** [comment]
I find the explanation of @sjrd to be very sensible, though I am still not 100% convinced.

Firstly, although this may be an unrelated issue (or non-issue), I would at least expect the GADT variant of this issue to typecheck:

```scala
enum SBool[X <: Boolean]:
  case SFalse extends SBool[false]
  case STrue extends SBool[true]

type Not[X <: Boolean] <: Boolean = X match
  case false => true
  case true => false
  
def id[X <: Boolean](x: SBool[X]): Not[Not[X]] = x match
    case SBool.SFalse => false // ERROR
    case SBool.STrue => true // ERROR
```

With a GADT, we can refine a type parameter within any arbitrary predicate, so it seems strange that a nested match type throws off dotty here, despite that it is possible to write a plainly more powerful function:
```scala
def elimSBool[X <: Boolean, F[_ <: Boolean]](x: SBool[X], ff: F[false], ft: F[true]): F[X] = x match
  case SBool.SFalse => ff
  case SBool.STrue => ft
// now we can just use this function with F[X] = Not[Not[X]] to achieve the same thing
```

It is very imaginable to me that this is too annoying/complicated of a corner case to expect dotty to typecheck properly, however it may indicate that this problem is unrelated to the conditions for dependent typing of match types, as explained by @sjrd .

Other than that, it simply seems unintuitive that this does not work -- if Not[Not[true]] reduces to true, why shouldn't the same thing work with GADTs and dependent pattern matching? In particular, nothing in https://docs.scala-lang.org/scala3/reference/new-types/match-types.html indicates to me that only the outermost match type should be reduced, and it isn't clear to me why dotty doesn't first try to reduce the innermost match type (i.e. reduce Not[X] *first*) -- after all, Not[Not[true]] also is not reduced starting with the outermost match type.

Even if this is intended behavior (which I have a hard time believing), this is quite a large deficiency compared to the impression one gets from reading about match types. In the same link, match types are compared to closed type families from Haskell, which do not have this limitation as far as I understand, and so I would suggest that this at least be documented in some form, if it really cannot be reasonably fixed.
