### ISSUE TITLE
Scaladoc: scaladoc anchor navigation can't handle some same page links

### ISSUE THREAD

**Issue by KacperFKorban** [lampepfl/dotty#17182]
## Compiler version

`main`

## Description

In some cases, scaladoc can't properly scroll to anchors that are on the same page. In those cases, it takes several tries for scaladoc to scroll the entire way.
e.g.

![scaladoc-anchor-same-page-oopsie](https://user-images.githubusercontent.com/39772805/228840350-66356f1b-f50d-4b40-8c04-93764c71235e.gif)

## Expectation

Scaladoc should always be able to scroll to anchors.

**Comment by Dedelweiss** [comment]
From what I noticed during my test, the problem comes from the fact that the anchor does not remain in the URL. After some research, I found this javascript that replaces the anchor with an empty string.
In `scaladoc/resources/dotty_res/scripts/ux.js`:
```
if (lastEntry.isIntersecting) {
  window.location.hash = "";
  removeAllHighlights();
  const id = getIdOfElement(lastEntry);

  getTocListElement(id).parentElement.classList.toggle("active");
}
```
So from what I see, this `if` statement checks if the last entry in entries is intersecting with the window, indicating that it is visible on the screen. If that's the case, the code performs the following actions:

- It resets the window's anchor.

- It calls the removeAllHighlights function to remove any existing highlights from the table of contents elements and put the element clicked in `active`

So I know what the purpose of this `if` is but when I delete it, I don't see any change (and it works better).
### Before:

https://github.com/lampepfl/dotty/assets/44496264/69160bd2-ffe5-4cf0-b9f2-97c859fe185a

### After:

<img width="554" alt="Screenshot 2023-06-06 at 10 14 34" src="https://github.com/lampepfl/dotty/assets/44496264/dd293ee2-c6eb-423e-8e66-4bbba250c68f">

https://github.com/lampepfl/dotty/assets/44496264/72a3544e-155b-4152-81cc-2832c601e7c5

Before doing a PR, I wanted to know if anyone knew the use case for this `if` or if it was used for different pages.

**Comment by julienrf** [comment]
@KacperFKorban Which browser do you use? On my Firefox I can’t reproduce the issue.

**Comment by KacperFKorban** [comment]
@julienrf I use Chrome. I see that the issue is reproducible, based on the previous comment.

@Florian3k Can you take a look at @Dedelweiss suggestion?
