### ISSUE TITLE
Match type not computed if parameter is intersection type involving String or primitive types.

### ISSUE THREAD

**Issue by jilen** [lampepfl/dotty#17312]
## Minimized code
```scala

trait X
trait Y

import scala.compiletime._

type IsInt[A] = A match {
  case Int => true
  case _     => false
}

constValue[IsInt[1]] // true
constValue[IsInt[String]] // false
constValue[IsInt[X & Y]] // false
constValue[IsInt[X & String]] // Won't compile

```

**Comment by jilen** [comment]
Note, this might be the root cause https://github.com/circe/circe/issues/2128

**Comment by sjrd** [comment]
From [the spec](https://docs.scala-lang.org/scala3/reference/new-types/match-types.html#match-type-reduction):

> If the scrutinee type `S` is an empty set of values (such as `Nothing` or `String & Int`), do not reduce.

`X & Y` is not an empty set of values since there could be `class C extends X with Y`. However, `X & String` is an empty set of values because `String` is final and does not extend the trait `X`. Therefore, the last example does not reduced.

So this is as specified.
