### ISSUE TITLE
False positive dead code elimination on pure expressions

### ISSUE THREAD

**Issue by kubukoz** [lampepfl/dotty#17317]
## Compiler version

3.3.0-RC3, 3.2.2

### Sample 1

```scala
//> using scala "3.2.2"

package object foo {

  object HelloGen {
    println("hello world")
  }

  val Hello = HelloGen
}

import foo.Hello

object Main {

  def main(args: Array[String]): Unit = Hello: Unit
}

```

### Sample 2

Instead of a package object, use a top-level definition.

```scala
//> using scala "3.2.2"


object HelloGen {
  println("hello world")
}

val Hello = HelloGen


object Main {

  def main(args: Array[String]): Unit = Hello: Unit
}
```

## Output

```scala
Compiling project (Scala 3.3.0-RC3, JVM)
[warn] ./main.scala:13:5
[warn] A pure expression does nothing in statement position; you may be omitting necessary parentheses
[warn]     Hello: Unit
[warn]     ^^^^^
Compiled project (Scala 3.3.0-RC3, JVM)
```

## Expectation

```scala
Compiling project (Scala 3.3.0-RC3, JVM)
Compiled project (Scala 3.3.0-RC3, JVM)
hello world
```

Notes:

1. Here's javap verbose for `main`:

```
public void main(java.lang.String[]);
    descriptor: ([Ljava/lang/String;)V
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=0, locals=2, args_size=2
         0: return
      LineNumberTable:
        line 16: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       1     0  this   LMain$;
            0       1     1  args   [Ljava/lang/String;
    Signature: #27                          // ([Ljava/lang/String;)V
    MethodParameters:
      Name                           Flags
      args                           final
```

Notably the code is just a `return`, as the call is erased from the output.

2. This doesn't happen in Scala 2.13 or if you fully qualify `foo.Hello`.

**Comment by aherlihy** [comment]
WIP notes:
- the `Hello` gets tagged as a purity level 3, so it's removed
- it is not actually pure, it's a val in an object that is assigned from a lazyval so the expression has the stable flag but not a lazy flag
- adding a path, so `foo.Hello` will fix the issue because it's not tagged as purity level 3
- doesn't matter if object or package object
- potential incoherence in handling: slightly different tree shapes between with path/without path (should be Ident (without the foo.) but ends up being Apply)
- defining Hello as a lazy val will work around the problem for now
