### ISSUE TITLE
Can not get List from Some.

### ISSUE THREAD

**Issue by q1208c** [lampepfl/dotty#17379]
For the first, I am very sorry write this issue. 
I can not found useful information, because "Some" is so normal, any search engine will ignore it. 
I write a little program for learning Scala (version 3). 

```scala 
    @tailrec
    private def getKeyPair(vendor: String, arrayNode: List[Map[String, Object]]): Map[String, Object] =
        println("all: " + arrayNode)
        println("head: " + arrayNode.head)
        println("tail: " + arrayNode.tail)
        if arrayNode.head.get("Vendor").equals(vendor) then
            arrayNode.head
        else
            getKeyPair(vendor, arrayNode.tail)

    def getCloudKeyPair(vendor: String): Unit =
        val map = JsonUtil.toMap[Map[String, Object]](cloudAccess)
        val cloudService = map.get("CloudServices")
        println("map: " + map)
        println("cloudService: " + cloudService)
        println("cloudService get: " + cloudService.get)
        val cloudServices: List[Map[String, Object]] = cloudService.get
        println(cloudServices)
        getKeyPair(vendor, cloudServices)

```

I want get the keypair when match vendor. 

```json
{
  "CloudServices": [
    {
      "vendor": "vendor1",
      "username": "user1",
      "accessKey": "key1",
      "accessSecret": "secret1"
    },
    {
      "vendor": "vendor2",
      "username": "user2",
      "accessKey": "key2",
      "accessSecret": "secret2"
    }
  ]
}
```
The cloudService should be "Some(List...)", so the cloudServices should be "List", 
but the compiler told me 
```
/Users/wangzw/Workspace.Bird/EagleNest/src/main/scala/com/wangzw/EagleNest/CloudService/Aliyun.scala:56:69
Found:    Map[String, Object]
Required: List[Map[String, Object]]
        val cloudServices: List[Map[String, Object]] = cloudService.get
```
I am new guy for Scala, there must be wrong with me.
by the way , the ".tail" return Inteable, can not use as rescue, what should I do? 

Thank for any information. 

Sorry for my pool English.

**Comment by julienrf** [comment]
Hello, you can find the API documentation of `Option` [here](https://www.scala-lang.org/api/current/scala/Option.html). In the list of methods, you can search for “list”, and you will find one of them is `toList` ([here](https://www.scala-lang.org/api/current/scala/Option.html#toList:List[A])). If you write `cloudService.toList` instead of `cloudService.get`, you should get what you want.

However, please note that this issue tracker is for reporting issues with the Scala 3 compiler, not for asking questions about the usage of Scala. Next time, please post your question on the [users forum](https://users.scala-lang.org/).

**Comment by q1208c** [comment]
@julienrf 
I tried ".toList", it return "List(List(...))". 
sorry for use issue as forum, I try forum.
