### ISSUE TITLE
Top Level Definitions are shadowed with no error message

### ISSUE THREAD

**Issue by lolgab** [lampepfl/dotty#17384]
## Compiler version

`3.3.1-RC1-bin-20230428-a89fbf5-NIGHTLY`

## Minimized code

```Scala
// file: build.sbt
ThisBuild / scalaVersion := "3.3.1-RC1-bin-20230428-a89fbf5-NIGHTLY"

lazy val a =
  project
lazy val b =
  project.dependsOn(a)

// file: a/src/main/scala/foo.scala
val a = 1

// file: b/src/main/scala/foo.scala
val b = 2

// file: b/src/main/scala/main.scala
def bar = a + b
```

## Output

```scala
[error] -- [E006] Not Found Error: /Users/lorenzo/scala/repro/b/src/main/scala/main.scala:1:10 
[error] 1 |def foo = a + b
[error]   |          ^
[error]   |          Not found: a
[error]   |
[error]   | longer explanation available when compiling with `-explain`
[error] one error found
```

## Expectation

It should fail to compile as it does when you try to do the same in the same compilation unit moving `foo.scala` in a subdirectory:

```
[error] -- [E161] Naming Error: /Users/lorenzo/scala/repro/b/src/main/scala/other/foo.scala:1:0 
[error] 1 |val a = 1
[error]   |^
[error]   |foo$package is already defined as package object foo$package in /Users/lorenzo/scala/repro/b/src/main/scala/foo.scala
```

**Comment by mbovel** [comment]
Hello! Thanks for reporting this issue.

How do you compile the provided example? With SBT?

My guess is that in the first case, you have two distinct subprojects (`a` and `b`), and therefore no name-clash, while you have a single subproject (`b`) in the second case and therefore a name clash if your declare the same package object twice.

I reproduced 3 scenarios using `scalac`.

### Duplicate `foo$package`

`foo.scala`:

``` scala
val a = 1
```

`other/foo.scala`:

``` scala
val b = 2
```

`main.scala`:

``` scala
def bar = a + b
```

Compile with:

```bash
scalac foo.scala other/foo.scala main.scala
```

Compiler output:

```
-- [E161] Naming Error: other/foo.scala:1:0 ------------------------------------
1 |val b = 2
  |^
  |foo$package is already defined as package object foo$package in foo.scala
1 error found
```

### `foo$package` and `other.foo$package`, missing import

`foo.scala` and `main.scala` same as before.

`other/foo.scala` (added `package other`):

``` scala
package other
val b = 2
```

Compiler output:

```
-- [E006] Not Found Error: main.scala:1:14 -------------------------------------
1 |def bar = a + b
  |              ^
  |              Not found: b
  |
  | longer explanation available when compiling with `-explain`
1 error found
```

### `foo$package` and `other.foo$package`, with correct import

`foo.scala` same as before, and `other/foo.scala` same as before (with `package other`).

`main.scala` with the correct import:

``` scala
import other.b
def bar = a + b
```

Compiler output: no error, works!

---

These all seem like expected behavior to me. But maybe I am missing something?

**Comment by lolgab** [comment]
What I was trying, was to define different top level definitions for the _same package_.
My use case is to define shared definitions in main and some shared definitions in tests as well.
They both live in the same `package app` but are defined in two different compilation units.
Adding `package other` changes the package removing the shadowing. I was using the empty package in my reproduction. but this happens also if the files share the same package and file-name.

**Comment by lolgab** [comment]
@mbovel I updated the reproduction adding the `build.sbt` file since it uses Sbt to create the two modules.

**Comment by mbovel** [comment]
Note that there is generally no warnings when the same class appear several times in the class path. For example, if we define `Bar` both in subprojects `a` and `b` and have a project `c` depending one both (`project.dependsOn(a).dependsOn(b)`), then the version of `Bar` loaded will depend on the order of the `dependsOn` calls.  See [example.zip](https://github.com/lampepfl/dotty/files/11397259/example.zip).

The same happens when your write top-level definitions. A package object is generated automatically to wrap your definitions, in your case:

```scala
final module class foo$package extends Object {
    def a(): Int = 1
}
```

And there is no warnings if `foo$package` appears several times in the classpath.

This behavior, where the order of dependencies determines which class is loaded, is not specific to Scala. When the JVM tries to load a class, it searches for the class file in the classpath, which is an ordered list of directories, JAR files, and other resources. The JVM will use the first class file it encounters with the requested name. The order in which dependencies are specified in your build file determines the order in which they appear in the classpath, which in turn determines the class that is loaded in case of conflicts.

If you want to show such name conflicts your could for example use an SBT plugin like https://github.com/xuwei-k/sbt-conflict-classes which can list conflicts:

```
[info] Listing conflict classes:
[info] Found conflict classes in:
[info]     /Users/mbovel/scala-snippets/17384/a/target/scala-3.2.2/classes
[info]     /Users/mbovel/scala-snippets/17384/b/target/scala-3.2.2/classes
[info]   with classes:
[info]     foo$package$.class
[info]     foo$package.class
[info]     foo$package.tasty
```

I am not sure we would want to show or handle these conflits in Dotty directly.

**Comment by mbovel** [comment]
For your use-case, couldn't you add your additional definitions for tests in a sub-package, object or class?

**Comment by lolgab** [comment]
> For your use-case, couldn't you add your additional definitions for tests in a sub-package, object or class?

Sure, I could! I just didn't notice the problem until I minimized it.
Thank you for the thorough explanation.
I'm closing the issue since it's expected behavior and I don't see how the compiler can change to make it more obvious.
