### ISSUE TITLE
[Scala.js] @JSExportAll should work on enum

### ISSUE THREAD

**Issue by user753** [lampepfl/dotty#17490]
I think It would be great if 
```scala
@JSExportAll
enum FooBar { 
  case Foo(x: Int)
  case Bar(y: Int)
}
```
would work as 
```scala
enum FooBar { 
  @JSExportAll
  case Foo(x: Int)
  @JSExportAll
  case Bar(y: Int)
}
```
Right now I believe `@JSExportAll` on `enum` do nothing.

**Comment by sjrd** [comment]
/cc @gzm0 because this needs spec.

Hum. That is a hard one.

Technically it is behaving as specced, because an `enum`, [by spec](https://docs.scala-lang.org/scala3/reference/enums/desugarEnums.html), are desugared into other concepts. The `case`es are moved to the companion object of `FooBar`, and hence they are *not* members of the *class* `FooBar`, which is the one holding the `@JSExportAll` annotation.

If you define other members in `enum FooBar`, such as `def`s or `val`s, *they* will be exported, because they are true members of the class.

You could define a companion `object FooBar` with `@JSExportAll`, and that would (I believe) export the `case`s as members of the object.

Now that spec may not be what we *want*. It might be more intuitive, due to how scopes *look like*, to take `@JSExportAll` of an `enum` class to also apply to the `case` members moved to the `object`. The problem then is that they would still have to be exported as members of the (implicit) companion `object`. Unless you export the companion object as well (which you can only do if you make it explicit), exporting the `case`s will not help.

How did you actually plan on accessing those things from JS? With your original minimized snippet, you would still not have any access to the enclosing object, so I'm not sure what you were really trying to do.

**Comment by user753** [comment]
Thanks for the answer
>You could define a companion object FooBar with @JSExportAll, and that would (I believe) export the cases as members of the object.

```scala
@JSExportAll
object FooBar {}
```
doesn't work

>How did you actually plan on accessing those things from JS? With your original minimized snippet, you would still not have any access to the enclosing object, so I'm not sure what you were really trying to do.

I have a method `def getFooBar(): FooBar` and use it in js
```js
const fooBar = getFooBar()
if('x' in fooBar) {
  console.log(fooBar.x)
}
``

**Comment by sjrd** [comment]
Oh, you want all the *members* of all the *cases* to be exported? I thought you wanted the cases themselves (their constructors) to be exported.

I'm afraid what you're asking is out of scope. I don't see what would justify `@JSExportAll` to apply two levels deep. For that, you'll still have to annotate every case.

**Comment by user753** [comment]
Would it be possible to add another annotation, that exports everything? Something like `@JSExportEverything`

**Comment by som-snytt** [comment]
![image](https://github.com/lampepfl/dotty/assets/369425/9b61fa7e-18a1-4d9f-9638-d5e0396f6144)

Everything.
