### ISSUE TITLE
Constructor parameters: `(a: Int = 0)(b: Int = 0)` is not equivalent to `()()`

### ISSUE THREAD

**Issue by Sporarum** [lampepfl/dotty#18006]
## Compiler version
Scala 3.3.0

## Minimized code & Output

```Scala
trait Obj1(a: Int = 0)(b: Int = 0)

trait Obj2()()

// Expected:
new Obj1()(){}
new Obj2()(){}

// Unexpected:
new Obj1{}      // missing arguments for constructor Obj1 in trait Obj1
new Obj2{}
```
https://scastie.scala-lang.org/SRf7kAOKQWuUAm8yegbFtg

## Expectation

No error, or a similar error for `Obj2{}` (or better)

**Comment by Sporarum** [comment]
Has impact on trait parameters:
https://github.com/lampepfl/dotty/pull/17988

**Comment by odersky** [comment]
It's because of this test in `Typer.ensureConstrCall`:
```scala
psym.primaryConstructor.info.takesParams
```
The test does not take default parameters into account (it cannot, for reasons given below). For `Obj1`  it returns false, for `Obj2`, true. That is the fork in the treatment. If the primaryConstructor takes parameters, we need to consstruct a constructor application to pass default arguments. But we can insert at most one `()`, which can then expand to default parameters, hence the error.

I don't think it's worth trying to fix this.
