### ISSUE TITLE
Regression in disneystreaming/smithy4s

### ISSUE THREAD

**Issue by WojciechMazur** [lampepfl/dotty#18170]
Regression found in Open Community Build for disneystreaming/smithy4s, build logs: https://github.com/VirtusLab/community-build3/actions/runs/5480083582/jobs/9982804734

## Compiler version
3.3.1-RC3
3.3.2-RC Nightly
Bisect points to f19de96348014505ad3ade9b3ec48822581f85e9

## Minimized code

```Scala
object ShapeTag {
  trait Companion[T]
}

final case class Product()
object Product extends ShapeTag.Companion[Product]

trait Enumeration[E <: Enumeration.Value] extends ShapeTag.Companion[E]
object Enumeration:
  abstract class Value extends scala.Product with scala.Serializable

sealed abstract class FooEnum() extends Enumeration.Value
object FooEnum extends Enumeration[FooEnum] with ShapeTag.Companion[FooEnum]:
  case object FOO extends FooEnum()

@main def Test =
  List(Product, FooEnum.FOO).forall(_ != null)
```

## Output

```scala
[error] ./bisect/main.scala:17:37
[error] Values of types object Product | object FooEnum.FOO and Null cannot be compared with == or !=
[error]   List(Product, FooEnum.FOO).forall(_ != null)
[error]                                     ^^^^^^^^^
Error compiling project (Scala 3.3.1-RC3, JVM)
```

## Expectation
Should compile

**Comment by odersky** [comment]
Why should that compile? It's a union of two objects. They can't possibly be null. The error message helpfully points that out.

**Comment by odersky** [comment]
It's because before the commit https://github.com/lampepfl/dotty/commit/f19de96348014505ad3ade9b3ec48822581f85e9 the type of `List(Product, FooEnum.FOO))` was `List[AnyRef]` and that can be compared with `null`. After the commit,
the type of the expression is now `List(Product | FooEnum.FOO))` and since `Product `and `FooEnum.FOO` are objects, they cannot be null. So the change uncovered an error in smithy4s that was not detected before. smithy4s should be fixed.

**Comment by WojciechMazur** [comment]
@kubukoz You might be intrested in this change when upgrading Scala version used in smithy4s
