### ISSUE TITLE
Missing unchecked warning

### ISSUE THREAD

**Issue by dwijnand** [lampepfl/dotty#18364]
## Compiler version

3.2.1

## Minimized code

```scala
case class Wrapper[A](value: A)
enum Color:
  case Red, Green

def test_wrong(x: Wrapper[Color]): Option[Wrapper[Color.Red.type]] =
  x match
    case x: Wrapper[Color.Red.type] => Some(x)
    case _                          => None
```

## Output

No warnings

## Expectation

Unchecked warnings.

## Notes

This is rereporting #16451, which we reverted the fix for in #18303.

**Comment by SethTisue** [comment]
Is the narrower fix plan sufficient, at least for the time being?

What makes me hesitate the most is the behavior if the user enables fatal warnings. By design — a design that can be questioned, but it's the design we have at present — is that if fatal warnings are enabled, the first fatal warning terminates compilation. So the user will never see the unchecked warning, which means the bug isn't really fixed for those users.

And there is a related issue around testing — we don't currently have a good way to write a test for multiple warnings. Currently in vulpix, as in Scala 2's partest, pos tests cannot have check files, so the way to test for a warning being emitted is to enable fatal warnings and make the test a neg test instead. But as described above, enabling fatal warnings means we'll never see the unchecked warning, so we can't put it in the check file. We might want to fix vulpix to allow pos tests to have an optional check file. If no check file is present, the code would still be allowed to emit warnings, they just wouldn't be checked. So the status quo for existing tests would not be affected. But new pos tests could opt in to including a check file.

**Comment by SethTisue** [comment]
PR with the less ambitious plan: https://github.com/lampepfl/dotty/pull/18377

(But we remain interested in also attempting the more ambitious plan.)
