### ISSUE TITLE
3.3.1-RC4 compiles but 3.3.1-RC5 fails ScalaTest `assertThrows` without a type parameter

### ISSUE THREAD

**Issue by godenji** [lampepfl/dotty#18478]
## Compiler version

3.3.1-RC5 and 3.3.1-RC6

## Minimized code

dummy implementation of [assertThrows](https://github.com/scalatest/scalatest/blob/main/dotty/core/src/main/scala/org/scalatest/Assertions.scala#L818)

```Scala
inline def assertThrows[T <: AnyRef](f: => Any)(implicit classTag: scala.reflect.ClassTag[T]) = f

assertThrows(1)
```

## Output

```scala
No ClassTag available for T
  |
  |               where:    T is a type variable with constraint <: AnyRef
```

## Expectation

Compiles successfully as was the case prior to RC5.

I thought that the offending commit was this [merged PR](https://github.com/lampepfl/dotty/pull/18286) but apparently it's unrelated? At any rate, a commit in RC5 has broken ScalaTest.

**Comment by jchyb** [comment]
Hi, thank you for filing an issue. I tested this once again, and I see what the problem is now. The provided minimization does indeed compile for 3.3.1-RC1 to 3.3.1-RC4, but it fails for every stable version of the compiler. To ensure source compatibility in the LTS (the 3.3.x series) we had to remove some changes in the unstable RC versions.

With that said I still believe this minimization should not be able to compile either way, since compiler has no way of knowing what T should resolve to, and therefore cannot generate the ClassTag (as it has no idea what to generate). Reading the docs of ScalaTest, they ask to explicitly pass the type parameter, like here:
```scala
assertThrows[scala.ArrayIndexOutOfBoundsException](array(10))
```

However, if You have a regression in your repo from 3.3.0 to 3.3.1-RC6 (with perhaps a different minimization), please let us know! We might be able to/need to fix that one.
