### ISSUE TITLE
False positive of "Unreachable case" warning under macro type match

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#18507]
## Compiler version
Fails on 3.3.1-RC7
Fails on latest nightly (`3.4.0-RC1-bin-20230901-89e8dba-NIGHTLY`)
Last good release: `3.3.1-RC1-bin-20230301-0df5ae2-NIGHTLY`
First bad release: `3.3.1-RC1-bin-20230302-8020c77-NIGHTLY`
First bad commit: https://github.com/lampepfl/dotty/commit/6b36cd97bf276b57c392cf63e281f283345610cc

## Minimized code

```scala
//> using options -Xfatal-warnings
import scala.quoted.*

trait DFValOf[T]

def calcWidth(x: List[Type[Any]])(using Quotes): Unit =
  x.collect { case '[DFValOf[t]] => ???}
```

## Output

```scala
7 |  x.collect { case '[DFValOf[t]] => ???}
  |                   ^^^^^^^^^^^^^
  |                   Unreachable case
```

## Expectation
No warning (no error under fatal-warnings).

**Comment by dwijnand** [comment]
The compiler is right here (not a regression) because `Type[DFValOf[t]]` is provably disjoint from `Type[Any]`, seeing as Type is invariant.

However, if I switch to `List[Type[?]]` then the compiler also thinks that `Type[DFValOf[t]]` and `Type[?]` are disjoint...  So I'll submit a fix for that version of the program.
