### ISSUE TITLE
repl output incomplete when entering multiple statements at once

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#1854]
Scala 2:
```scala
scala> class A; 1
defined class A
res0: Int = 1

scala>
```
`dotr`:
```scala
scala> class A; 1 
defined class A
scala>
```

**Comment by bbarker** [comment]
I believe I have a fix for this; will plan to clean up and submit within a day.

**Comment by felixmulder** [comment]
@bbarker - thanks for having a look at this! FYI, the current REPL is being re-written from scratch. This issue still exists since we want to make sure the new REPL supports this.

Cheers and happy weekend!
Felix

**Comment by smarter** [comment]
For what it's worth, Felix's new repl is being developed at https://github.com/dotty-staging/dotty/tree/topic/new-repl. Of course we still accept PRs for the current repl that improve it; but if you want to do more work on the repl it probably makes sense to switch focus to the new one :).

**Comment by bbarker** [comment]
Thanks, I'll ask next time! Anyway, it was interesting. 

Here's what I have so far: https://github.com/bbarker/dotty/tree/testReplMultiStatements

Unfortunately, a test fails (and there are definitely problems) with my fix, since it relies on `Tree.show` giving back a valid Scala (dotty) statement; calling show on the Tree for `def id(x: 4): 4 = x` yields `def id(x: 4.type): 4.type = x`, which is apparently not valid dotty; was hoping to find a way to take a Tree and convert it back to valid dotty/scala.
