### ISSUE TITLE
`catch case` fails to warn in case of unchecked bounded type parameter

### ISSUE THREAD

**Issue by scf37** [lampepfl/dotty#19013]
## Compiler version

3.3.1

## Minimized code

```Scala
def handle[E <: Exception](f: => Unit): Option[E] = 
  try 
    f
    None
  catch case e: E => Some(e)

val r: RuntimeException = handle[RuntimeException](throw new Exception()).get
```

## Output

```scala
java.lang.ClassCastException: class java.lang.Exception cannot be cast to class java.lang.RuntimeException (java.lang.Exception and java.lang.RuntimeException are in module java.base of loader 'bootstrap')
```

## Expectation

Fail compilation because type of E is not known in compile time, allow compilation for inline method (or maybe also by ClassTag in scope?).

**Comment by szymon-rd** [comment]
The `catch case e: E => Some(e)` should not compile. It's even weirder that it tries to cast to RuntimeException, given that erasure should happen and there is no `TypeTest` instance.

**Comment by dwijnand** [comment]
This should either compile and emit an unchecked warning, or it shouldn't compile.  Perhaps compare how Typer and Erasure treats `x match { case e: E => .. }` and mirror that.

**Comment by SethTisue** [comment]
Scala 2.13: "warning: abstract type pattern E is unchecked since it is eliminated by erasure". This is the correct behavior, IMO (compile, but warn). At runtime you get the expected `java.lang.ClassCastException`, not during the execution of the method, but at the time the result is stored in `r`.

**Comment by mbovel** [comment]
@smarter @SethTisue @hamzaremmal @KuceraMartin: if you solve the issue quickly, I suggest you continue with https://github.com/lampepfl/dotty/issues/19201 :)

**Comment by SethTisue** [comment]
Background: sometimes try/catch in user code is rewritten to a pattern match. But not always. `TryCatchPatterns` "compiles the cases that can't be handled by primitive catch cases as a common pattern match", where "primitive" catch cases mean those that can be handled by the JVM's `catch` instruction. If the "common pattern match" route is taken, with a `TypeApply` node in the tree, then we get the unchecked warning. The bug comes in the primitive-catch-case scenario. In that code path, `TypeTestCasts#whyUncheckable` is never called.

So the solution plan we (mostly Guillaume 😅) have in mind is to add a case to `Erasure` that looks for `Bind` nodes, since that's how the primitive catch case is represented, as `CaseDef(Bind(...))`. When it sees one, it should call into `TypeTestCasts`, except we'll need to refactor `TypeTestCasts` a bit because its current entry point, `interceptTypeApply`, is specific to `TypeApply` nodes.
