### ISSUE TITLE
Context function values incorrectly capture outer method parameters

### ISSUE THREAD

**Issue by scf37** [lampepfl/dotty#19021]
## Compiler version

3.3.1

## Minimized code

```Scala
import scala.util.Random

def foo(x: Int = Random.nextInt()): String ?=> Int = x
val t: String ?=> Int = foo()
given s: String = "42"
println(t)
println(t)
```

## Output

```scala
1683052012
-974219606
```

## Expectation
Numbers should be the same 

Additionally, I could not find any way to capture variables within context function:

```Scala
def foo: String ?=> Int = 
  val x: Int = Random.nextInt()
  (s: String) ?=> x // Compilation error: Found:    (String) ?=> Int  Required: Int
```

Additionally, it is really weird compiler behaves differently depending on whether context function type is specified explicitly. Not sure is this a bug or intended:

```Scala
def foo: String ?=> Int = x
val t1 = foo // t1 has type Int, implicit String is required in scope
val t2: String ?=> Int = foo() // t2 has type String ?=> Int, implicit String is not required in scope
```

**Comment by som-snytt** [comment]
https://docs.scala-lang.org/scala3/reference/contextual/context-functions.html

> if the expected type of an expression E is a context function type (T_1, ..., T_n) ?=> U and E is not already an context function literal, E is converted to a context function literal by rewriting it

It's context all the way down!

So you intended to write a "context function literal":
```
def g: String ?=> Int = (s: String) ?=>
  val x: Int = Random.nextInt()
  x
```

The weird part is that syntax and expected type both matter. We're accustomed to just returning an expression of the appropriate type at the end of the block. But a block is not a function literal.

The first question has nothing to do with context functions, but default argument expressions.

```
def bar(x: Int = Random.nextInt()): Int = x  // bar() is different for each invocation because def default = nextInt()
```

I'd suggest asking questions on chat. That is, there is that moment when one realizes that one has unresolved questions, even if the weird behavior turns out to be buggy. Hopefully my answer is approximately correct or elucidating.

**Comment by SethTisue** [comment]
https://scala-lang.org/community/ has links to places to ask questions
