### ISSUE TITLE
Let by-name implicit parameters have lazy semantics

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#1998]
## Motivation

Generic programming often exhibits scenarios where an implicit expansion would diverge, were it not for a lazy implicit value that "ties the knot". Current Shapeless has the `Lazy` pseudo-type to handle this using some tricky macro machinery. Following an idea of @milessabin it seems cleaner to put this in the language and tie it to by-name implicit parameters. 

## Status Quo

By-name implicit parameters are disallowed in Scala-2. They have been introduced recently in dotty, but without attaching special meaning to them. 

## Proposal

Modify implicit search as follows:

When searching for an implicit value of type `T` to provide an argument for a by-name parameter of type `=> T`:

 - Create a new implicit value with a fresh name _lv_, which has the signature of the following definition:

        implicit lazy val lv: T

    The current implementation uses the prefix `$lazy_implicit$` followed by a unique integer for _lv_.

 - This lazy val is not immediately available as candidate for implicit search (making it immediately available would result in a looping implicit computation). But it becomes available in all nested contexts that look again for an implicit argument to a by-name parameter.

 - If this implicit search succeeds with expression `E`, and `E` contains references to the lazy implicit value _lv_, replace `E` by

        { implicit lazy val lv: T = E; lv }

    Otherwise, return `E` unchanged.

## Implementation Status

This proposal has been implemented in #1993. The test cases in that PR starting with

    lazy-implicits-... . scala

show where the feature is useful. All these test cases would have given a diverging implicit expansion before the change.

**Comment by rkuhn** [comment]
This would be awesome, 💯 ! Having an implementation for an inductive type-level computation serves as correctness proof, but allocating all those instances (as is typically done) comes at great runtime cost. This proposal would be highly beneficial wherever the actual implementation is not needed, e.g. because the types are tracking a purely compile-time aspect with no corresponding runtime values.

**Comment by japgolly** [comment]
When declaring the lazy implicit, would it not make more sense to use the `lazy` keyword rather than `=>`? It will introduce inconsistency and I can already see myself having to continually explain over the years that `=>` parameters are by-name unless implicit in which case they're by-need.

```scala
implicit def SumCountable[T, U](implicit ev1: lazy Countable[T]) = ...
// or
implicit def SumCountable[T, U](implicit lazy ev1: Countable[T]) = ...
```
instead of
```scala
implicit def SumCountable[T, U](implicit ev1: => Countable[T]) = ...
```

Going even further maybe there should be a way to declare by-need parameters in general. Then regardless of whether a param is implicit or not, parameters could be by-value, by-name, by-need, and it would be consistent.
```scala
def egByValue[A](a: A)(implicit x: X[A]) = ...

def egByName[A](a: => A)(implicit x: => X[A]) = ...

def egByNeed[A](lazy a: A)(implicit lazy x: X[A]) = ...
```

**Comment by ritschwumm** [comment]
+1 for lazy parameters in general. i know i can express them with a by-name parameter and an additional lazy val, but then i need to be very careful to always access the lazy val, and not by accident the parameter.

**Comment by ritschwumm** [comment]
+1 for lazy parameters in general. i know i can express them with a by-name parameter and an additional lazy val, but then i need to be very careful to always access the lazy val, and not by accident the parameter.

i think this would be much cleaner than having the behaviour of by-name parameters "magically" change depending on whether they are marked implicit or not.

**Comment by odersky** [comment]
@japgolly I think these are good points. I agree it would be consistent to allow `lazy` for all parameters, and if we do then it would make indeed sense to use `lazy` instead of by-name as
our indication for inserting lazy implicit values. Let me check what would be involved in this.

**Comment by retronym** [comment]
Some discussion on general by-need params in the vintage ticket https://issues.scala-lang.org/browse/SI-240

**Comment by odersky** [comment]
@retronym This is an amazing can of worms. Thanks for the pointer!

**Comment by TomasMikula** [comment]
What about instead of annotating implicit parameters as lazy, annotate the rule as recursive?

Now:

```scala
implicit def SumListable[T, U](implicit
  ev1: => Listable[T],
  ev2: => Listable[U]
): Listable[Sum[T, U]]
```

Then:

```scala
@rec implicit def SumListable[T, U](implicit
  ev1: Listable[T],
  ev2: Listable[U]
): Listable[Sum[T, U]]
```

with the meaning being:
With temporarily assuming the result (`Listable[Sum[T, U]]`) if during resolving the arguments (`ev1`, `ev2`) this same rule (`SumListable`) would be applied with compatible types, just use the assumed result.

To me, subjectively, this formulation seems slightly simpler.
Also, there would be no interaction between rules&mdash;a rule can only be recursive with itself. (Whereas in the current proposal two rules can "interact" if they accept lazy argument of the same type.)

**Comment by propensive** [comment]
@japgolly @odersky Is `lazy` the correct terminology? By comparison to `lazy val`s, it implies the parameter is evaluated at most once. I think I suggested `def` as an alternative last time this came up... Either way, I'd be happy to lose `=> T`.

**Comment by odersky** [comment]
On second thought, and as @TomasMikula and @propensive noted, this has nothing to do with call-by-need. The lazy val is local to the implicit block. That means the whole implicit argument _will_ be evaluated every time the implicit method demands it. So it's pure call-by-name and no syntax change to what was proposed is needed.

Aside: I am very averse to using annotations like @rec for something fundamental. Annotations increase language footprint just like specialized syntactic constructs. In fact, annotations are worse in this case, because they hide some fundamental aspect of type checking in a seemingly innocuous little modifier that could mean anything.

**Comment by TomasMikula** [comment]
The syntax I used (`@rec`) is unimportant, notice the difference in meaning: what's recursive is the _result_, not the arguments. If you wish, write it like this:

```scala
implicit def SumListable[T, U](implicit
  ev1: Listable[T],
  ev2: Listable[U]
): => Listable[Sum[T, U]]
```

I find this version easier to reason about (you may think otherwise), because it is more local: the hypothetical `Listable[Sum[T, U]]` will be used to "tie the knot" only if the _same_ rule (`SumListable`) was going to be tried in a nested context.

This is in contrast with the current proposal, where the hypothetical argument "becomes available in all nested contexts that look again for an implicit argument to a by-name parameter," i.e. it becomes available even for _other_ implicit rules (i.e. not local).

**Comment by rec** [comment]
For personal reasons, I vote against using @rec :-D or at least, to wrap it in backticks `@rec` so it doesn't send me email

**Comment by odersky** [comment]
#1993 just was merged, so this is in now.

**Comment by Atry** [comment]
@japgolly I like the `lazy val`'s call-by-need semantics, it would have better performance when the type class is very complicated.

However, a naive implementation would break serializability. This is important when working with Spark or other distributed computing environments.
We will need [@transient lazy val pattern](http://fdahms.com/2015/10/14/scala-and-the-transient-lazy-val-pattern/) in case of the type class being serialized when a closure reference it.

I don't know if Scala support `@transient` on parameter like this:

```
def foo(sparkRdd: RDD[String])(@transient lazy val implicit ev: T) = {
  sparkRdd.map { x =>
     doSomethingWith(ev)
  }
}
```

**Comment by milessabin** [comment]
I've been working on implementing this for Scala 2 and have run into what appears to be a good case for `lazy` (ie. at most once) rather than (or as well as) by name semantics.

Consider the following example,
```scala
trait Foo {
  type Out
  def out: Out
}

object Test {
  implicit def bar(implicit foo: => Foo): foo.Out = foo.out
}
```
This doesn't compile (either on my Scala 2 branch or with Dotty) because the by name argument `foo` is not stable,
```
lazy-implicits-7.scala:12: error: stable identifier required, but foo found.
  implicit def bar(implicit foo: => Foo): foo.Out = foo.out
                                          ^
one error found
```
This pattern is very important in implicit-based type level programming, so this would be an disappointing limitation. By contrast, shapeless's `Lazy` captures the value in a stable context and hence supports the following with vanilla Scala 2,
```scala
implicit def bar(implicit foo: Lazy[Foo]): foo.value.Out = foo.value.out
```
Currently the following is a workaround with by name implicits which compiles both on my branch and with Dotty,
```scala
trait Foo {
  type Out
  def out: Out
}

object Foo {
  type Aux[Out0] = Foo { type Out = Out0 }
}

object Test {
  implicit def bar[T](implicit foo: => Foo.Aux[T]): T = foo.value
}
```
ie. we use the Aux pattern to avoid the need for a stable value. This is clumsy however, and the additional type parameter (which must typically be inferred) can make it hard to express methods which require an explicit type argument.

So, whilst by name implicits get us _close_ be being able to replace shapeless's `Lazy` macro, it's not quite there. The proposals above to use the `lazy` keyword to more or less exactly replicate shapeless's `Lazy` semantics are a relatively minor addition to this proposal from an implementation point of view and would do the whole job.

**Comment by smarter** [comment]
> This doesn't compile (either on my Scala 2 branch or with Dotty) because the by name argument foo is not stable,

I'm not sure if lazy implicits would be considered stable either, for the same reason that lazy vals in general are not stable in Dotty: http://scala-lang.org/blog/2016/02/17/scaling-dot-soundness.html#loopholes-caused-by-scaling-up

**Comment by milessabin** [comment]
Presumably a statically non-null lazy val would be stable?

**Comment by milessabin** [comment]
I would be happy with the restrictions listed in the "Plugging the Loopholes" section of that post.

**Comment by smarter** [comment]
OK, would you mind opening a new issue for this feature? Just reopening this issue might be confusing.

**Comment by milessabin** [comment]
Done: https://github.com/lampepfl/dotty/issues/3005

**Comment by milessabin** [comment]
Scala 2 implementation here: https://github.com/scala/scala/pull/6050.

You might want to take a look at [this test](https://github.com/milessabin/scala/blob/87b912c298228076cad8448b23820b596b961ccd/test/files/run/byname-implicits-6.scala) ... it was one of the original motivating examples for shapeless's `Lazy` (see [this SO question](http://stackoverflow.com/questions/25923974)). It's handled correctly by the Scala 2 implementation (thanks to some finessing of the divergence checker) but not by the Dotty implementation.

**Comment by smarter** [comment]
@milessabin Cool! I think it'd be worth opening an issue for the test you mention, a minimized version reproducing the problem would also be appreciated :).
