### ISSUE TITLE
Named type parameters allow creating object with inaccessible field

### ISSUE THREAD

**Issue by AleksanderBG** [lampepfl/dotty#2038]
The following code results in a `ClassCastException`:
```scala
trait T[type +A]
class C[type +A](val a: A) extends T[A]
object Unsound extends C[Any](0) with T[Boolean]
Unsound.a
// java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
```

This is similar to this old issue:
```scala
trait T[+A]
case class C[+A](val a: A) extends T[A]
def unC[A](c: T[A]): A = c match { case C(a) => a }
object Unsound extends C[Any](0) with T[Boolean]
unC(Unsound)
// java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
```

However, in the new case the field is flat-out inaccessible.

**Comment by AleksanderBG** [comment]
@odersky could you possibly explain if there are currently any plans to solve type errors of this kind? Or is the issue just put on hold until named type parameters have a proper spec?

**Comment by odersky** [comment]
I had written a comment, but somehow that did not get in. Anyway, the issue is that the status of named type parameters is currently unclear, and a possible outcome is that they will not make it in. Their implementation is known to be badly out of date with lots of known problems. So the best thing I can do is put issues raised against them on hold until we have a clearer picture.

**Comment by odersky** [comment]
Named type parameters have been removed from the implementation.
