### ISSUE TITLE
dotty.tools.dotc.core.Types$MissingType: cannot resolve reference to type 

### ISSUE THREAD

**Issue by olafurpg** [lampepfl/dotty#2390]
While upgrading the community build dotty-staging/scalatest fork to the latest dotty (0.1.1-bin-20170507-1014af3-NIGHTLY) and sbt-dotty 0.1.0-RC4 I hit an a MissingType error 
https://travis-ci.org/dotty-staging/scalatest/builds/229925482#L2104
during type erasure https://github.com/lampepfl/dotty/blob/5093126421e333b2329399736e6d7ad327e3bdfa/compiler/src/dotty/tools/dotc/core/TypeErasure.scala#L496

I made some unsuccessful attempts to minimize the error, it seems to boil down to something like this

```scala
package foo
trait TestSuite {
  protected trait NoArgTest extends (() => Int)
}
trait CancelAfterFailure { self: TestSuite => }
```

To reproduce the error:

```
git clone https://github.com/dotty-staging/scalatest.git
cd scalatest
git checkout 1b2ea9013e4f71306f6dfc5f4e1ae0db85a46629
sbt scalatest/compile "last scalatest/compile:compileIncremental"
```

**Comment by olafurpg** [comment]
Any tips/tricks on how to minimize the error? I have tried -Ycheck:all.

**Comment by olafurpg** [comment]
I am still able to reproduce this error with 20170511, see stacktrace https://travis-ci.org/dotty-staging/scalatest/builds/231553300#L1942 I have updated the steps to reproduce in the description.

The error is thrown while transforming this file here: https://github.com/dotty-staging/scalatest/blob/1b2ea9013e4f71306f6dfc5f4e1ae0db85a46629/scalatest/src/main/scala/org/scalatest/CancelAfterFailure.scala

**Comment by smarter** [comment]
I've minimized it to:
```scala
trait TestSuite {
  trait NoArgTest
}

trait TestSuiteMixin { self: TestSuite =>
  def foo(test: self.NoArgTest) = {}
}

trait CancelAfterFailure extends TestSuiteMixin { self: TestSuite =>
  override def foo(test: self.NoArgTest) = {}
}
```
This is caused by https://github.com/lampepfl/dotty/commit/ef6922c1d16de3429b402e103e07b50ef3e75372 which intentionally changed RefChecks to not look at the full self-type but only the class type when checking for overrides.

@odersky It seems that the only logical way forward is to completely disallow self types from appearing in non-private signatures, since the self-type is an implementation detail of the class, but this is likely to break a lot of things, like Scalatest here. What do you think?
