### ISSUE TITLE
Value types are not properly compared in `TypeComparer`

### ISSUE THREAD

**Issue by felixmulder** [lampepfl/dotty#2430]
The following subtyping test fails `Ycheck` after erasure:

```scala
class Test1(val x: Int) extends AnyVal
class Test2(val y: Test1) extends AnyVal
```

In tree checker:

```scala
tree.tpe <:< pt // tree.tpe = ErasedValueType(Test2, ErasedValueType(Test1, Int))($this)
                //       pt = Int
```

This is what causes erasure not to be `Ycheck`able. The next phase, `ElimErasedValueType`, removes the `ErasedValueType`s and casts so that it is again, `Ycheck`able.

ping @odersky

**Comment by felixmulder** [comment]
After this issue is resolved, the work from https://github.com/lampepfl/dotty/pull/2415 makes erasure `Ycheck`able

**Comment by smarter** [comment]
`ErasedValueType(A, B)` is intentionally not a subtype or supertype of either `A` or `B` to trigger boxing/unboxing in Erasure, but Erasure should add the necessary casts (`evt2u` to convert an `ErasedValueType` to its underlying value: https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/transform/Erasure.scala#L251). If after `Erasure` you have a tree with type `ErasedValueType` whose expected type is `Int`, then something is wrong, because the cast should have been inserted.

**Comment by odersky** [comment]
I agree with @smarter. This is intentional, and done so that erasure is forced to insert the proper casts.

**Comment by smarter** [comment]
I talked with @felixmulder and we did find one issue: when a value class underlying type is also a value class, you may need to wrap/unwrap using `evt2u/u2evt` multiple times, but this is apparently not always done, I haven't investigated more but @felixmulder is on it.
