### ISSUE TITLE
Teach Ycheck to spot refernces to Java packages

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#2456]
Ycheck should have complained here: https://github.com/lampepfl/dotty/issues/2396#issuecomment-302088399

but it didn't.

**Comment by abeln** [comment]
@DarkDimius can you add a bit more context here?
1) in which AST nodes can references to Java packages appear/not appear?
2) is the answer to 1) true for all phases, or only after a specific phase?

**Comment by DarkDimius** [comment]
@abeln, 
1) is hard to answer because we use Idents & Selects to represent Imports. So It's not about "in what trees", but instead about "in what context". Eg. packages should be passed as arguments or be assigned to variables.

The nice way to do it would be to introduce a phase after Pickler that gets rid of all references to packages in Select\Ident's. This phase should have a post-conditions that those trees don't re-appear.

**Comment by abeln** [comment]
Thanks. How do we "get rid" of Java packages? What should they be replaced with?

**Comment by DarkDimius** [comment]
@abeln by replacing all verbose references that include packages by Idents.
Eg. `Select(Select(Select(root, scala), Predef) println)` => `Ident(println)`
After this, there should be no references to packages through RefTrees left.

**Comment by abeln** [comment]
Here's my understanding of what needs to be done:
1. Declare a new MiniPhaseTransform, to be run together with Pickler (or after?)
2. override transformSelect in the new mini-phase
3. Within transformSelect, detect whether the `qualifier` stands for a package
4. Simplify the Select node as you wrote above: (p1, p2, ..., pn).Ident(i) => Ident(i)

Is that reasonable?
If yes, then what's a good way to do step 3 (detecting whether a qualifier stands for a package)? The type of the qualifier is a TermRef (because packages are objects, right?), but how do I tell it apart from a "regular" object (otherwise I'll turn x.y.T into T)?

**Comment by DarkDimius** [comment]
> Is that reasonable?

Yes 👍 

1. after Pickler.
2. yes.
3. yes
4. yes. Because the thing you refer to is top-level you can always refer to it through `tpd.ref`

>If yes, then what's a good way to do step 3 (detecting whether a qualifier stands for a package)? 

Take the term symbol of the qualifier. Check if it has both flags Package and JavaDefined set. I fou don't check for JavaDefined you can also get package objects.

**Comment by abeln** [comment]
Thanks. I took a first stab at this in https://github.com/lampepfl/dotty/pull/2528
