### ISSUE TITLE
Implicit keyword should not be allowed on return types

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#2512]
```scala
def foo1(f: Int => implicit Int): Int = ???
def foo2(f: Int => Int): implicit Int = ???
```
Are currently allowed but do nothing, there should be an error.

**Comment by biboudis** [comment]
Good catch! Pair-fix it tomorrow?

**Comment by abeln** [comment]
I think this is a bit trickier than it might seem at first, because of [implicit function types](https://www.scala-lang.org/blog/2016/12/07/implicit-function-types.html):

`implicit Int` is not a valid return type, but `implicit Int => Int` is, and so is `Int => implicit Int => Int`

So would we want to forbid only the return type (but not the (curried) arguments) from having an `implicit`?

**Comment by nicolasstucki** [comment]
Yes. We probably need to check the `finalResultType` of method types.

**Comment by Jasper-M** [comment]
Isn't `implicit` in that context a modifier of the function type as a whole? `implicit Int => Int` meaning `ImplicitFunction[Int,Int]`, and `Int => implicit Int => Int` meaning `Function[Int,ImplicitFunction[Int,Int]]`.
By which I mean to say: shouldn't this restriction be in the grammar/parser?

**Comment by odersky** [comment]
The restriction is already in the grammer. The parser should reflect that.
