### ISSUE TITLE
Document literal singleton types

### ISSUE THREAD

**Issue by OlivierBlanvillain** [lampepfl/dotty#2615]
The current best source of documentation is [SIP-23 - Literal-based singleton types](http://docs.scala-lang.org/sips/pending/42.type.html), it would be nice to have something on dotty.epfl.ch!

**Comment by Varunram** [comment]
@OlivierBlanvillain Maybe a new doc file over at `docs/reference`? What are your suggestions? Thanks!

**Comment by OlivierBlanvillain** [comment]
@Varunram Yes, I was thinking about a new page under Reference / New Types.

**Comment by Varunram** [comment]
@OlivierBlanvillain Sorry for the delay! Was stuck up in a few other things. So I've started working on this and have the doc part almost ready. It would be of immense help if you could point out some code examples so that I may use them in the page (since this is my first time writing a doc page). Thanks for your time!

**Comment by OlivierBlanvillain** [comment]
@Varunram I think the current best source of examples is SIP-23... The main use case IMO would be a shapeless style `LabeledGeneric` type class for enums / case classes / sealed trait, but we are not quite there yet.

**Comment by Varunram** [comment]
Ah, makes sense. I borrowed a couple of examples from folone's talks, which were related to SIP-23. Preliminary PR for your review will be up shortly :)

**Comment by OlivierBlanvillain** [comment]
Awesome! I'll do my best to quickly review it :)

**Comment by SethTisue** [comment]
should this be closed, since #2699 was merged?
