### ISSUE TITLE
dotr wrong classpath under cygwin

### ISSUE THREAD

**Issue by flomebul** [lampepfl/dotty#2644]
Lauching dotr under cygwing result in a java syntax error.
My feeling is that this is due to the use of ';' as path separator for the bootclass path:

Bug look like to be in "dotc" line 69
    jvm_cp_args="-Xbootclasspath/a:$toolchain"
I replaced with
    jvm_cp_args="-Xbootclasspath/a:\"$toolchain\""
so that the ';' path separator does not and the line on cygwin

**Comment by felixmulder** [comment]
Hey @flomebul! Would you mind turning this into a PR? I think @liufengyun would be happy to review :)

Cheers,
Felix

**Comment by flomebul** [comment]
Hello @felixmulder! I'm too new in Git to make it directly and I'm pretty sure that there are other location in the dot[cdr] bin file where the same error is present. Let me check before.
Regards

**Comment by flomebul** [comment]
Ok, here is my current proposal for change...
in dotc
68c68
<     jvm_cp_args="-Xbootclasspath/a:$toolchain"
---
>     jvm_cp_args="-Xbootclasspath/a:\"$toolchain\""
70c70
<     jvm_cp_args="-classpath $toolchain"
---
>     jvm_cp_args="-classpath \"$toolchain\""

in dotd
67c67
< CLASS_PATH="-classpath $DOTTY_LIB$PSEP$DOTTY_COMP$PSEP$DOTTY_DOC_LIB$PSEP$DOTTY_INTF$PSEP$SBT_INTF"
---
> CLASS_PATH="-classpath \"$DOTTY_LIB$PSEP$DOTTY_COMP$PSEP$DOTTY_DOC_LIB$PSEP$DOTTY_INTF$PSEP$SBT_INTF"
76c76
< CLASS_PATH="$CLASS_PATH$PSEP$JSOUP_LIB"
---
> CLASS_PATH="$CLASS_PATH$PSEP$JSOUP_LIB\""

in dotr
32c32
< CLASS_PATH="-classpath .$PSEP$DOTTY_LIB$PSEP$SCALA_LIB"
---
> CLASS_PATH="-classpath \".$PSEP$DOTTY_LIB$PSEP$SCALA_LIB\""

I'm not able to test in other environment than cygwin.

Regards

**Comment by senia-psm** [comment]
@flomebul are you sure you have the latest version? Please note that there is no `jvm_cp_args` variable in the latest version of `dotc`: https://github.com/lampepfl/dotty/blob/master/bin/dotc#L142

You could use `edit` button on the page above to edit `dotc` and create a pull request.

**Comment by felixmulder** [comment]
@senia-psm: he's probably got the `./dist/bin/dot*` which is in the release :)

@flomebul: as Simon suggested - you can edit these files on GitHub itself by just navigating to them and pressing the pen symbol to edit :)

**Comment by liufengyun** [comment]
I've been working on it the whole day -- the problem is with the script in `bin/common`. I'll update once I figure out a fix.

**Comment by flomebul** [comment]
I work withe the "official" dotty 0.1.2.RC1.

**Comment by liufengyun** [comment]
@flomebul I've fixed the bug related to Cygwin and Mingw in #2667 , and tested on Windows Server 2012 on our new regression platform for [windows](https://ci.appveyor.com/project/liufengyun/packtest/build/15). I also test manually on Windows 10.

The easiest way for you to try again is to download the unofficial [zip](https://github.com/liufengyun/packtest/releases/download/v0.2.0/dotty-0.2.0-bin-SNAPSHOT.zip).

As an alternative, you can also just download the latest `bin/` scripts from #2667  and override your local scripts under `bin/`. 

Let me know if you still have problems compile and run Scala code.

Note: REPL still doesn't work due to #2648, which is caused by problems with Ammonite https://github.com/lihaoyi/Ammonite/issues/119#issuecomment-128209044 (thanks @smarter ).

Credits: Thanks a lot Mr. Salvi for preparing me a Windows machine and @nicolasstucki for suggesting the Appveyor service for windows testing.
