### ISSUE TITLE
Windows: launchIDE cannot find "code" despite being in the PATH

### ISSUE THREAD

**Issue by chtefi** [lampepfl/dotty#2653]
Hey,

On Windows, launchIDE fails because Java can't find "code" even if it's in the path.

```
java.io.IOException: Cannot run program "code": CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
```

I've just tested, `ProcessBuilder` should launch "code.cmd" instead to make it work on Windows.

**Comment by smarter** [comment]
Thanks for the report! I'll make sure to fix this soon.

**Comment by smarter** [comment]
Fixed by https://github.com/lampepfl/dotty/pull/2776. You should be able to get `launchIDE` working on Windows  if you use the latest nightly build of dotty (`scalaVersion := "0.2.0-bin-20170620-1d05796-NIGHTLY"` in your build) and the latest version of sbt-dotty (`addSbtPlugin("ch.epfl.lamp" % "sbt-dotty" % "0.1.3")` in `project/plugins.sbt`). Let me know if something is still broken!
