### ISSUE TITLE
Anonymous functions in REPL (and expressions) must be wrapped in parentheses

### ISSUE THREAD

**Issue by Blaisorblade** [lampepfl/dotty#2789]
Dotty's REPL does not wrap the expression to evaluate in parens (like Scala's REPL). But because of #1424, wrapping expressions in parentheses can be needed to preserve behavior.

That bug is still open but confusingly titled, and the actual issue is hidden. Hence the separate one.

TL;DR. Dotty's REPL rejects`(x: Any) => println(1)` but accepts `((x: Any) => println(1))`. Martin suggested a fix in https://github.com/lampepfl/dotty/issues/1424#issuecomment-236449912

> So it seems the REPL has to special case closures in any case.
> So closures have to be put in parentheses by the REPL anyway.

I'm not sure if closures need special casing, or you can just wrap every expression in parentheses. Of course, definitions can't be wrapped :-|.

```scala
scala>  x => println(1)
-- [E080] Syntax Error: <console>:5:1 ------------------------------------------
5 | x => println(1)
  | ^
  | missing parameter type for parameter x, expected = ?

longer explanation available when compiling with `-explain`
scala> (x: Any) => println(1)
-- Error: <console>:1:0 --------------------------------------------------------
1 |(x: Any) => println(1)
  |^^^^^^^^
  |not a legal self type clause
```

**Comment by lihaoyi** [comment]
FWIW, Ammonite breaks up the incoming commands into individual statements, and dealing with them separately. Since definitions can't be wrapped, we could simply not wrap them, while continuing to wrap free-floating expressions. 

Also, I think this isn't a problem with Ammonite even without paren-wrapping, since free-floating expressions get wrapped in `val resN = ...`, which should avoid the self-type confusion.

Also, if all this fuss is over the wrapper class/object being confused by the possibility of self-types, shouldn't adding a `;` to the start of the wrapper class/object body be enough to avoid any such confusion?

**Comment by Blaisorblade** [comment]
> Also, if all this fuss is over the wrapper class/object being confused by the possibility of self-types, shouldn't adding a single ; to the start of the wrapper class/object body be enough to avoid any such confusion?

:+1: sounds good. I can't think  of counterexamples, but I feel like reviewing the grammar would make me more confident. Anybody feel free to go ahead though.
