### ISSUE TITLE
tests/run/bridges.scala cannot be compiled by clean compiler

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#2924]
It can be reproduced with:
`vulpix tests/run/bridges.scala`

but not with
`vulpix`

**Comment by nicolasstucki** [comment]
This has been happening since it was added in 92fe2a50a91b22c3efa0f1b5746378d987966429

**Comment by nicolasstucki** [comment]
There is probably some state left from previous runs in the compiler that allows it to work.

**Comment by smarter** [comment]
No idea why it doesn't break usually, but `bridges.scala` contains a block with 1424 statements which causes `withDefinedSyms` to blow up with a stackoverflow because `foldRightBN` is not tail-recursive. This should be easy to fix by replacing `foldRightBN` by a while loop. But someone should investigate why this doesn't trigger when running all the tests, maybe vulpix forgets to run bridges.scala for some reason?

**Comment by DarkDimius** [comment]
@smarter @nicolasstucki VM needs different amount of stack in JITed and interpreted mode.
You can have code that does not stackoverflow when compiled but does when interpreted.
