### ISSUE TITLE
print deprecation warning for bitshift Int by a Long

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#2968]
The current situation is pretty bad:

2.11/Dotty:
```scala
scala> 1 << 33L
res0: Long = 8589934592

scala> val x = 1
x: Int = 1

scala> x << 33L
res1: Int = 0
```

2.12 (since https://github.com/scala/scala/pull/4238):
```scala
scala> 1 << 33L
res0: Int = 2

scala> val x = 1
x: Int = 1

scala> x << 33L
res1: Int = 2
```

See also the discussion at https://gitter.im/scala/contributors?at=598b4b3eee5c9a4c5fa61568 where @ichoran proposed getting rid of `Int#<<(x: Long)` since it can be so easily misused.

**Comment by Ichoran** [comment]
To clarify, I find it highly implausible that someone would go to the trouble of making the RHS of a shift be `Long` (as a constant) unless they intended a `Long` result.  The right-hand-isn't-a-constant case is less clear.  But if we're not going to widen everything to `Long` as was done in 2.11, then the mixed `Int/Long` case just shouldn't compile because we can't tell whether the RHS was meant to be `Int` or the LHS was meant to be `Long`.  Better for the user to have to specify which it is.

**Comment by som-snytt** [comment]
Just wanted to point out that shifting by constant doesn't have to be explicit or obvious. It could be an inherited constant value, etc, so the expression doesn't necessarily indicate an intention to widen.

```
scala> 1 << 33L
res0: Int = 2

scala> trait T { final val shift = 33L }
defined trait T

scala> 1 << null.asInstanceOf[T].shift
res1: Int = 2

```
Also, if you name an operation shift, then you must expect it to be shifty.

**Comment by Ichoran** [comment]
One should write one's contracts especially carefully when dealing with those who are shifty: spell things out.

**Comment by DarkDimius** [comment]
My opinion on the matter: 

- permit under `-language:Scala2`, but issue deprecation warning. 
- prohibit in Scala3;

**Comment by som-snytt** [comment]
I just proposed a book series of aphorisms and it turns out that roughly-edged APIs are a great resource. ([the gitter](https://gitter.im/scala/scala?at=598b6bad76a757f8088cd1f2))

**Comment by sjrd** [comment]
The differing behavior in the presence of a constant was a plain bug of the constant folder, foxed in the PR you mentioned. There was, independently, the problem of widening, which was inconsistent with Java and which I fixed in https://github.com/scala/scala/pull/5117.

I think it would be reasonable to deprecate and eventually remove the Int shift Long overload, even in 2.x.

**Comment by mdedetrich** [comment]
I agree with @DarkDimius , should be deprecated in Scala2 but removed in Scala3. Implicit number conversions should never happen when doing bitshifts, because they are pretty much never what you want

**Comment by som-snytt** [comment]
Harmonized at https://github.com/lampepfl/dotty/pull/6366
except difference in warning when folded:
```
Welcome to Scala 2.13.2 (OpenJDK 64-Bit Server VM, Java 14).
Type in expressions for evaluation. Or try :help.

scala> 0x01030507 << 36L == 271601776
                  ^
       warning: method << in class Int is deprecated (since 2.12.7): shifting a value by a `Long` argument is deprecated (except when the value is a `Long`).
       Call `toInt` on the argument to maintain the current behavior and avoid the deprecation warning.
val res0: Boolean = true
```
vs
```
Dotty compiler version 0.25.0-RC2 -- Copyright 2002-2020, LAMP/EPFL
scala> 0x01030507 << 36L == 271601776                                                                                  
val res0: Boolean = true
```

**Comment by bishabosha** [comment]
so it seems to be that the issue here is not printing the deprecation warning for `<<(that: Long)`

**Comment by ckipp01** [comment]
> so it seems to be that the issue here is not printing the deprecation warning for `<<(that: Long)`

I just tried this out and it does seem to print out the deprecation warning.

<img width="840" alt="Screenshot 2023-05-11 at 09 47 02" src="https://github.com/lampepfl/dotty/assets/13974112/de00db3c-ed10-409b-bb7b-2e4bd86e2ba8">

```scala
//> using scala 3.nightly
//> using option -deprecation

object example:
  val a = 1 << 33L
```

Am I correct in understanding then that this can be closed?

**Comment by sjrd** [comment]
Yes, looks like it can be closed.
