### ISSUE TITLE
Unsoundness due to missing variance checks for extends clause

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#2973]
This shouldn't compile:
```scala
class Foo[T]
class Bar[-T] extends Foo[T]
```
scalac realises that:
```scala
error: contravariant type T occurs in invariant position in type [-T]Foo[T] {
  def <init>(): Bar[T]
} of class Bar
class Bar[-T] extends Foo[T]
      ^
one error found
````

**Comment by TomasMikula** [comment]
In #3856 I argue that this should compile, and the other way, i.e.

```scala
class Foo[-T]
class Bar[T] extends Foo[T]
```

shouldn't.

**Comment by Blaisorblade** [comment]
@TomasMikula Added some comments on your idea; TLDR I agree with @smarter, for details see in #3856.

**Comment by smarter** [comment]
@odersky I see a fix for this issue authored by you in https://github.com/dotty-staging/dotty/commits/fix-%232973 but no corresponding PR, did you forget to open the PR?

**Comment by Blaisorblade** [comment]
@smarter I already opened https://github.com/lampepfl/dotty/pull/4057 with that fix, but it doesn't work and I couldn't immediately fix it (my comments there explain why): IIRC, if you compute variance by traversing `classParents` of a `ClassInfo`, you don't see the annotations because they're just not there.
