### ISSUE TITLE
SBT alias `repl` references wrong `Main`

### ISSUE THREAD

**Issue by newca12** [lampepfl/dotty#3024]
Usual ways as given in : http://dotty.epfl.ch/docs/contributing/getting-started.html
dotty.tools.dotc.repl.Main is not found anymore when using bin/dotr and repl task in sbt also no longer works
sbt dotty-repl/repl work OK, thanks @smarter for the tip

**Comment by smarter** [comment]
Since the repl sources are currently part of the dotty-compiler project it doesn't really make much sense to have a separate dotty-repl project in the Build.scala. /cc @felixmulder

**Comment by felixmulder** [comment]
I still think that this should be a separate project as much as the language server should. We, however, have the subata integration to worry about - and as such this still needs to be a part of `dotty-compiler` by including sources via `Build.scala`

I'm surprised that `dotty-repl/repl` works, it shouldn't right? What should work is `dotty-repl/run`. If `dotty-repl/repl` works, it should be a bug in sbt since we're using it as an alias to `runMain`. Maybe it short-circuits to the only main there is if there aren't multiple on `runMain`.

**Comment by smarter** [comment]
> I still think that this should be a separate project as much as the language server should. 

For what purpose? Having a `dotty-repl` project is misleading, things like `dotty-repl/publishLocal` will not do anything useful. It also means the repl sources are part of three projects: `dotty-repl` (currently non-bootstrapped), `dotty-compiler`, and `dotty-compiler-bootstrapped`. This is too much.

**Comment by felixmulder** [comment]
Agreed, hence my argument that it should only be a single project - a bootstrapped project `dotty-repl`, but subata got in the way again 🍲

This is too OT for discussion on this issue, write to me on Slack when you wake up :)
