### ISSUE TITLE
Allow website visitors to comment on documentation

### ISSUE THREAD

**Issue by megri** [lampepfl/dotty#3036]
Could we have inline comments on the documentation pages?
Something like https://tsi.github.io/inlineDisqussions/

**Comment by felixmulder** [comment]
Sounds cool, I think we'd be happy to accept a PR on this :)

**Comment by felixmulder** [comment]
The only question is if it can scale. We're using dottydoc to create the web-page. So this has to be general enough that people who don't want it can disallow it and people who do want it can use it for themselves (not getting something we hardcoded).

**Comment by megri** [comment]
Is it possible to sideload a javascript? That should work

**Comment by felixmulder** [comment]
Sure, in [./docs](https://github.com/lampepfl/dotty/tree/master/docs) - you can edit the `_include` or `layouts` to sideload your JavaScript :)

**Comment by felixmulder** [comment]
As seen here: 

https://github.com/lampepfl/dotty/blob/master/docs/index.html#L7-L11

You can include extra JS files in some of our default templates.

**Comment by smarter** [comment]
Seems like there's no easy way to support this, and in general I'm not sure this is a great idea since comments on documentation tend to go stale. On the other hand we now have an "Open Chat" link at the bottom-right of every documentation page which brings up the dotty gitter room where people can discuss, so closing this issue.

**Comment by SethTisue** [comment]
> comments on documentation tend to go stale

yeah, that was our experience with Disqus, and was one of the big reasons we never brought it back on scala-lang.org. instead we try to direct people to Discourse for questions and discussions, and GitHub to report and/or fix mistakes. (I guess suggesting Gitter works for now for Dotty since there aren't a ton of Dotty users yet, you might need to revisit that choice eventually.)
