### ISSUE TITLE
Pattern matching on sealed abstract classes causes spurious warning

### ISSUE THREAD

**Issue by Jacoby6000** [lampepfl/dotty#3145]
In some situations, matching on a sealed abstract class using a type annotation will cause the compiler to warn about unreachable code

```scala
  sealed trait Foo
  class Bar(val s: String) extends Foo
  sealed abstract class Baz(val s: String) extends Foo
  
  val f: Foo => String = { 
    case bar: Bar => bar.s
    case baz: Baz => baz.s
  }
```

This warning does not happen if the case for the sealed abstract class comes first.

**Comment by allanrenucci** [comment]
Can be reproduced with `sealed trait` too:
```scala
sealed trait Foo
class Bar extends Foo
sealed trait Baz extends Foo

class Test {
  def f(x: Foo) = x match { 
    case bar: Bar => 1
    case baz: Baz => 2
  }
}

```

**Comment by liufengyun** [comment]
This seems to be the intended behaviour, because `Baz` cannot be instantiated. Scalac 2.12.3 generates the same warning.

**Comment by allanrenucci** [comment]
What about this example:
```scala
sealed trait Foo
class Bar extends Foo
sealed trait Baz extends Foo

class Test {
  def f = {
    val x = new Baz {}
    x match { 
      case bar: Bar => 1
      case baz: Baz => 2
    }
  }
}
```
scalac emits no warning here.

**Comment by liufengyun** [comment]
The last example above is due to the problem of anonymous class extending sealed class/trait.

@smarter suggested to simply disallow anonymous class extending sealed class/trait long time ago, see below:

https://github.com/lampepfl/dotty/issues/1917#issuecomment-276806954

Currently, the exhaustivity check doesn't have the information to know whether a sealed trait has anonymous children or not.
