### ISSUE TITLE
Add minimal DCE to the inliner

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#3221]
The inliner sometimes leaves dead code behind, e.g. in:

```scala
object Test {
  def computation: Int = 10

  inline val flag = false

  inline def foo(x: => Int) =
    if (flag) println(x)
}
```
`foo(10)` is inlined to `{ () }`, but `foo(computation)` is inlined to:
```scala
{
  def x: Int = Test.computation
  ()
}
```
which eventually ends up as a method in bytecode.

This could be fixed by doing some minimal dead code elimination which wouldn't even require tree traversals: if the inlined body is made only of `def`s and constants, remove everything.

**Comment by Wojtechnology** [comment]
Looks like this particular example is fixed with https://github.com/lampepfl/dotty/commit/f2c09d404bfa9d97d17cf773f297371a8a6d8f7e. It still generates some dead code in a similar case where you pass by value, assuming that the calculating the `val` has no side-effects. Perhaps we should close this issue.

Code for pass-by-value is below:
```
object Test {
  def computation: Int = 10

  inline val flag = false

  inline def foo(x: Int) =
    if (flag) println(x)

  def meth1() = foo(10)
  def meth2() = foo(computation)
}
```
Where the body of `meth1` is `{ () }` and the body of `meth2` is:
```
{
  val x: Int = Test.computation()
  ()
}
```

**Comment by smarter** [comment]
Yeah I think this can be closed indeed.
