### ISSUE TITLE
Dottydoc generation broken on Windows because of illegal filenames

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#3349]
As reported on gitter recently by @DSouzaM:
```scala
[doc info] Generating doc page for: dotty.tools.repl.terminal.LazyList$.~:$                                        
Exception in thread "main" java.nio.file.FileSystemException: /mnt/c/Users/mattd_000/Documents/code/dotty/docs/_sit
e/api/dotty/tools/repl/terminal/LazyList$/~:$.html: Invalid argument
```
The corresponding classfile is called `LazyList$$tilde$colon$.class`, we should use the same encoding (obtained with the method `Name#mangledString`) for the html files. According to @felixmulder the relevant code is at https://github.com/lampepfl/dotty/blob/b7fbb3919ea6a81d170c0f34a1197f525ac964e1/doc-tool/src/dotty/tools/dottydoc/staticsite/Site.scala#L202

**Comment by philwalk** [comment]
Because the `Invalid Argument` path `'/mnt/c/Users/mattd_000/Documents/...'` begins with /mnt/, I'm assuming that this exception occurred in WSL (Windows Subsystem for Linux), which permits colons in filenames of files created by the JVM.     If this did occur under WSL, then #3373  is unrelated. 

To demonstrate the difference, the following scala script fails under cygwin, but passes under WSL:
```
object ColonFilename extends App {
  val file = new java.io.File("1:2:3")
  file.createNewFile
}
```
The relevant difference between the two windows environments is that the cygwin environment depends on a Windows version of the JVM, whereas WSL uses an Ubuntu Linux JVM version.
