### ISSUE TITLE
Meta-issue: REPL Improvements

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#3359]
From @felixmulder comment in #3176's discussion:
- [ ] If a state is thrown away, and a new state used in its stead. That should be enough to reset the REPL. So, some mutability in ReplDriver init as well as Rendering should be moved into the session.
- [ ] Evaluation should be better encapsulated, it'd be so nice if we could get away without the classloading that sort of exists outside of our model.

**Comment by allanrenucci** [comment]
@felixmulder Can you develop the second point, I am not sure to fully understand.

**Comment by felixmulder** [comment]
Evaluation of code is a side-effect of rendering the rhs of values. For instance:

```scala
scala> println("foo")
```

creates an object, which is eventually roughly the equivalent of this java code:

```java
final class rw$l1 {
  public static rw$l1 module = new this()
  public static scala.Unit res0;

  private this() {
    println("foo");
    res0 = new scala.Unit();
  }
}
```

In [rendering#L60](https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/repl/Rendering.scala#L60) we make sure not to render this because when we do the classloading on [rendering#L55](https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/repl/Rendering.scala#L55) the class (which is an object in scala terms) is initialized and the constructor does the println.

It would be great if we could capture this effect in our model of the REPL.

**Comment by OlivierBlanvillain** [comment]
I don't really understand these two points, what has to be done here?

**Comment by felixmulder** [comment]
It needs more types and such.

Seriously though, I don't remember exactly what was going on here. But it was quite hard to reason about what would be evaluated and where.

**Comment by OlivierBlanvillain** [comment]
Hmm OK, then I think I will close it for now...
