### ISSUE TITLE
infinite loop in implicit search when using collection-strawman

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#3396]
The offending code (adapted from the tests in https://github.com/scala/collection-strawman/blob/master/collections-contrib/src/test/scala/strawman/collection/decorators/MapDecoratorTest.scala, which apparently have never been run with Dotty):

```scala
import strawman.collection.decorators._

object Test {
  def foo(map: strawman.collection.Map[Int, Int]): Unit = {
    map.zipByKeyWith(map)((a, b) => a)
  }
}
```

```scala
% dotc -classpath "$(coursier fetch -p ch.epfl.scala:collections-contrib_2.12:0.5.0)" map.scala
```

**Comment by odersky** [comment]
The culprit is this beauty (from `BuildFrom.scala`)

    implicit def buildFromSortedMapOps[CC[X, Y] <: SortedMap[X, Y] with SortedMapOps[X, Y, CC, _], K0, V0, K : Ordering, V]: BuildFrom[CC[K0, V0], (K, V), CC[K, V]] = new BuildFrom[CC[K0, V0], (K, V), CC[K, V]] {
      def newBuilder(from: CC[K0, V0]): Builder[(K, V), CC[K, V]] = from.sortedMapFactory.newBuilder[K, V]()
      def fromSpecificIterable(from: CC[K0, V0])(it: Iterable[(K, V)]): CC[K, V] = from.sortedMapFactory.from(it)
    }

What happens is that gets called without a known instance of the parameter `K`. This means implicit search goes out an enumerates all ways a type (any type) can have an `Ordering`. There are a lot of such types, so it dies with an GC limit exceeded exception after going on for some time.
