### ISSUE TITLE
getClass returns less precise type in Dotty than in Scala 2

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#3495]
Scala 2:
```scala
scala> object A
defined object A

scala> A.getClass
res0: Class[_ <: A.type] = class A$
```

Dotty:
```scala
scala> object A 
// defined object A
scala> A.getClass 
val res0: Class[_] = class rs$line$1$A$
```

**Comment by odersky** [comment]
That's sort of intentional. `getClass` in nsc has an insane amount of specialized logic devoted to it. Seems overkill for something as marginal. So we dropped that in Dotty. But there are saner ways to regain it. I was thinking of making getClass available as a Decorator in Predef.

    implicit class HasGetClass[T <: AnyRef] { 
      def getClass: Class[_ <: T] = ???
    }

Then, translate this to the real `getClass` at erasure. The real `getClass` needs to be hidden in `Object` so that the decorator kicks in. The easiest way to do this is to make it `private` and drop that flag at erasure.
