### ISSUE TITLE
Test infrastructure: add an option to only rerun tests that have failed

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#3798]
scalac partest supports this with --failed.

**Comment by dwijnand** [comment]
This isn't a bug, but I think it's a good candidate for the spree because it doesn't require lots of prior compiler knowledge and having this implemented would help all compiler hackers.

For context scala 2's partest leaves `t1234.log` files and uses that to determine failed tests.  I think Scala 3's test framework uses `i1234.out` files.

**Comment by som-snytt** [comment]
Thanks, I needed this recently because I'm still bad at running dotty tests. The label should be `prio:blocker`!
