### ISSUE TITLE
Interaction between refinement types and named parameters

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#3881]
If a method is redeclared in a refinement with different parameter names, can we use these parameter names when calling the method? Scalac says yes, Dotty says no. Scalac and Dotty agree that the answer is yes when a method is redeclared in a sub-trait however:
```scala
trait Foo {
  def hi(x: Int): Int
}

trait Foo2 extends Foo {
  def hi(y: Int): Int
}

object Test {
  def withTrait(foo2: Foo2): Unit = {
    foo2.hi(x = 1) // error in scalac and Dotty

    foo2.hi(y = 1) // OK in scalac and Dotty
  }

  type Foo3 = Foo { def hi(y: Int): Int }

  def withRefinement(foo3: Foo3): Unit = {
    foo3.hi(x = 1) // error in scalac, OK in Dotty

    foo3.hi(y = 1) // OK in scalac, error in Dotty
  }
}
```

**Comment by odersky** [comment]
There is very little we can do here and I would argue we should not do anything. Named parameters must come from the resolved method symbol. The method type does not work, since there are typically many types that are joined with an `&`. The difference is that `scalac` treats a refinement type as a sort of class and refinements as definitions in the class. `dotc` treats it as a refinement. So that explains the difference. 

Given `dotc`'s approach I believe it would be quite ugly to either spec or implement scalac's behavior.
