### ISSUE TITLE
Running compiler within the REPL

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#3969]
The [documentation](http://dotty.epfl.ch/docs/contributing/workflow.html#inspecting-trees-with-type-stealer) explains how one can inspect trees and types within the REPL. Unfortunately it doesn't work anymore. The issue is that all the Jars in [compiler/test/dotty/Jars.scala](https://github.com/lampepfl/dotty/blob/master/compiler/test/dotty/Jars.scala) are null when accessed from the REPL.

```scala
$ sbt
> dotty-compiler/test:console
...
scala> dotty.Jars.dottyTestDeps
res0: List[String] = List(null, null, null)
```

**Comment by expz** [comment]
I was unable to reproduce the output `List(null, null, null)` using the current master branch. Instead it gives the error:
```
java.io.FileNotFoundException: Unable to locate scala-asm-6.0.0-scala-1 on classpath:
/usr/share/sbt/bin/sbt-launch.jar
...
```
I traced down the problem to a couple bugs and fixed them in this [commit](https://github.com/expz/dotty/tree/expz-i3969), and now the output is `List(null, null, null)`.

But the problem cannot be entirely fixed, because it is due to a [bug](https://github.com/sbt/sbt/issues/1918) in sbt where the `:console` key ignores the `fork` and `javaOptions` settings. So the keys like `-Ddotty.tests.classes.compiler=...` are not getting set.

**Comment by allanrenucci** [comment]
If you make [dottyRunWithCompiler](https://github.com/lampepfl/dotty/blob/master/compiler/test/dotty/Jars.scala#L33) lazy that should fix the `FileNotFoundException`. But yes this an issue with sbt console. Not sure why it used to work

**Comment by expz** [comment]
I fixed the `findJarFromRuntime()` function to work in all contexts, but I understand now that you can just avoid using it (e.g., by `lazy val`) until sbt supports forking the console.

As to why it used to work, perhaps you used to use the `:repl` key instead of `:console`? The directions you link to use `repl`, and `repl` does indeed fork the JVM. I tried it out, and the directions do work if you run the `repl` command with the following arguments:
```
> repl -classpath ./compiler/target/scala-2.12/*:./interfaces/target/*
```
But the line `val t = s._2(0)` fails with the error:
```
java.lang.AssertionError: assertion failed: denotation module class <empty> invalid in run 1. ValidFor: Period(1..2, run = 2)
	at scala.Predef$.assert(Predef.scala:219)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.updateValidity(Denotations.scala:768)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.bringForward(Denotations.scala:791)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:846)
        ...
```
Perhaps that should be an issue? Or is that expected behavior?

**Comment by Blaisorblade** [comment]
@expz IIRC Dotty expects a pretty specific classpath/classloader setup, so I'm not sure that scenario is supported. http://dotty.epfl.ch/docs/internals/classpaths.html has some old information, I'm sure many/all details are different (we'll drop that file) but Dotty might still be picky.

Maybe set -Ddotty.tests.classes.compiler= from inside the same JVM with System.setProperties?

**Comment by expz** [comment]
I do not know enough about classloaders to understand your suggestion, but I mapped out the current [classloader hierarchy](https://gist.github.com/expz/6cf25870e5cbc6f50447b718c088a0e4) for the dotty repl in case it helps you decide. At least that scenario was supported when the [doc](http://dotty.epfl.ch/docs/contributing/workflow.html#inspecting-trees-with-type-stealer) was written.

Back to the Scala 2.12 REPL at `dotty-compiler/test:console`, I set the keys as you suggested with the code,
```scala
val p = System.getProperties()
p.put("dotty.tests.classes.interfaces", "./interfaces/target/classes")
p.put("dotty.tests.classes.library", "./library/target/scala-2.12/classes")
p.put("dotty.tests.classes.compiler", "./compiler/target/scala-2.12/classes")
System.setProperties(p)
```
Then the imports work, but the next line fails with
```scala
scala> val s = stealType("class O { type X }", "O#X")
creating stub for Boolean, owner = module class scala#24, file = null
decls = class Enum#28
  module Enum#29
  module class Enum$#30
  ...
exception occurred while typechecking  class O { type X }
 object Ax_x_x {val x_x_x0: O#X = ???}
java.lang.ClassCastException: dotty.tools.dotc.core.Symbols$$anon$3 cannot be cast to dotty.tools.dotc.core.Symbols$ClassSymbol
  at dotty.tools.dotc.core.Symbols$Symbol.asClass(Symbols.scala:491)
  at dotty.tools.dotc.core.Definitions.UnitClass(Definitions.scala:434)
  at dotty.tools.dotc.typer.ProtoTypes$Compatibility.disregardProto(ProtoTypes.scala:50)
  at dotty.tools.dotc.typer.ProtoTypes$Compatibility.constrainResult(ProtoTypes.scala:64)
  at dotty.tools.dotc.typer.ProtoTypes$Compatibility.constrainResult$(ProtoTypes.scala:56)
  ...
```
On the other hand, that line works in the dotty repl.

**Comment by bishabosha** [comment]
not really clear if anyone needs this

**Comment by bishabosha** [comment]
also, if someone wants to use the compiler classes from the repl, they are available:
```scala
scala> dotty.tools.dotc.Main
val res0: dotty.tools.dotc.Main.type = dotty.tools.dotc.Main$@1e6e29d6
```
