### ISSUE TITLE
implicit with singleton type works around explicit result type for implicits

### ISSUE THREAD

**Issue by olafurpg** [lampepfl/dotty#3996]
```scala
object singleton {
  val x = "Hello!"
  implicit val y: x.type = x
  implicitly[String].length
}
```
I expected the program to be rejected because the type of `x` is inferred and Dotty requires an explicit result type for implicits.

**Comment by Blaisorblade** [comment]
Explicit result types are requested for implicits because of potential cycles in inference—the details are here, though I haven't decoded that yet:
https://github.com/scala/bug/issues/8697#issuecomment-292432445

To triage this one could turn the described issue into problematic code, adapt the problematic code using the above trick, and see what happens. I might get to try this.

**Comment by odersky** [comment]
No, that one counts as explicit result type.
