### ISSUE TITLE
Make enums interop with Java enums

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#4088]
There are two directions:

 1. Interpret Java enums as Scala enums
 2. Have Scala enums map to Java enums, so that they can be seen as native enums in Java code

See #1970 for comments about how this might be achieved.

**Comment by nicolasstucki** [comment]
@anatoliykmetyuk what is the current status of Java enums interop?

**Comment by anatoliykmetyuk** [comment]
The current status is best described by [this test](https://github.com/lampepfl/dotty/pull/6629/files#diff-cda65b21cf195bde563e10e6d634f17f). Basically, everything that you can do with Java enums can be done with Scala enums from Java. The only known incompatibility is #6663 which will be solved while solving #6620 (which implies that Scala enums require Scala library on classpath).

I'm closing this issue since the interop works in general and all the minor issues are discussed in separate tickets.
