### ISSUE TITLE
Private types leaking in public signatures should be reported as errors even under -language:Scala2

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#4154]
https://travis-ci.org/lampepfl/dotty-community-build/jobs/355301166

Regression introduced in #4013

**Comment by smarter** [comment]
The problem comes from a private type leaking into a public signature in scalatest, private leaks are errors on Dotty unless `-language:Scala2` is set, then they're only warning. I'll try to patch scalatest to fix this. On the Dotty side, we probably need to make private leaks errors even under `-language:Scala2`.

**Comment by smarter** [comment]
Fix pushed: https://github.com/dotty-staging/scalatest/commit/39c1f74fb7b8c0994d3f2f134353158284866af7

**Comment by liufengyun** [comment]
If we implement this check in Scala2, then we can close https://github.com/lampepfl/dotty/issues/5831.
