### ISSUE TITLE
Infinite loop apparent in dotty script using implicit conversions

### ISSUE THREAD

**Issue by bbarker** [lampepfl/dotty#4274]
Specifically it happens on [revision 11 here](https://gist.github.com/bbarker/ffe33dfb229778b02472c0b80dae3b98/2dfdf7e7fc1e3231522fa6ba3724ad6b88f37456)

Changes of all revisions in gist [shown here](https://gist.github.com/bbarker/ffe33dfb229778b02472c0b80dae3b98/revisions)

To reproduce, `:load Maybe.sc` in `dotr`.

I was using version 0.6.0-RC1 on Linux x86-64.

**Comment by Blaisorblade** [comment]
I think `maybe2Option` is calling itself recursively and the loop is in the program:
```scala
implicit def maybe2Option[A](maybe: Maybe[A]): Option[A] = maybe match {
    case unit: Unit => None
    case value => value
  }
```

Can you make `dotc` loop? If so, can you give a minimized example?

**Comment by bbarker** [comment]
I'll try to work on that in the next few days

**Comment by bbarker** [comment]
I see your point (and my typo) though. Should an implicit conversion be allowed to call itself? Seems like a likely disaster every time.

**Comment by bbarker** [comment]
If a recursive call is explicitly needed, it could be defined as an inner or otherwise separate function.

**Comment by Blaisorblade** [comment]
> Should an implicit conversion be allowed to call itself?

Oh I agree it's a trap.
There are use cases when you call the conversion on smaller arguments, and there are _more_ use cases when implicits can pass themselves to other code — but since it's in Scalac as well and used in lots of code, we can't just forbid it on a whim. Feel free to search for ideas elsewhere — let's keep this tracker to actionable bugs.
