### ISSUE TITLE
Run CI tests on Windows?

### ISSUE THREAD

**Issue by Blaisorblade** [lampepfl/dotty#4588]
That could be necessary to support Windows, which seems a blocker for a Scala 3 release.
Conceivably we could use Appveyor for that — right now Lightbend uses instead Jenkins (since it does support Windows): https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-windows/.

**Comment by liufengyun** [comment]
For the binary release, we do have some basic CI for windows (as well as for OS X and Linux): https://github.com/lampepfl/packtest/blob/master/windows .

**Comment by SethTisue** [comment]
> right now Lightbend uses instead Jenkins

it's historical, we probably ought to be on Appveyor, just like we're moving all the non-Windows things off Jenkins and onto Travis-CI.

**Comment by sjrd** [comment]
This was set up in #9647. However, only a small subset of tests are currently run. Basically just compiling a hello world with the bootstrapped dotc, and running the Scala.js JUnit tests. The full `test`s don't work on Windows at the moment, because all "neg" tests fail due to paths using `\` instead of `/`, and hence the outputs don't match the check files.

**Comment by liufengyun** [comment]
Now `sbt test` and `sbt dotty-bootstrapped/test` are green in #9666, except for a few disabled tests that fail (search `scala.util.Properties.isWin`).

We still need to figure out the infrastructure to run the tests, as Appveyor has a [one-hour limit][1] and the free version only supports _one concurrent job_.

[1]: https://www.appveyor.com/docs/build-configuration/#time-limitations

**Comment by liufengyun** [comment]
Fixed in #9934 and #9973 .
