### ISSUE TITLE
Sidebar of the document page should not be automatically collapsed

### ISSUE THREAD

**Issue by Glavo** [lampepfl/dotty#4713]
Now that we have clicked on any of the links in the sidebar, the sidebar will be collapsed and this behavior will seriously affect our reading of the document.
![image](https://user-images.githubusercontent.com/20694662/41816905-14e52eb2-77c3-11e8-8a91-00d88f4ad1b0.png)

**Comment by Blaisorblade** [comment]
It's not even consistent. That happens for http://dotty.epfl.ch/docs/reference/intersection-types.html doesn't happen for http://dotty.epfl.ch/docs/reference/enums/adts.html, and it seems that's simply because one is in `reference/enums` while the other is just in `reference`. Maybe moving files into subfolders would fix this?
