### ISSUE TITLE
Overriding field breaks modular reasoning of code

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#4756]
The following code causes run-time exception:

```Scala
class Foo {
  val x = 6
  val y = x + 5         // <== culprit: this.x translated into a virtual accessor call !!
  assert(y == 11)       // oops, y is `5`!
}

class Bar extends Foo {
  override val x = 10
}

object Test {
  def main(args: Array[String]): Unit = new Bar
}
```

The problem is that in `Foo`, `this.x` doesn't refer to the final field `Foo.x`, but is translated to a virtual call `this.x()`. This is counter-intuitive, it has the following drawbacks:

- it breaks modular reasoning of code (including reasoning about initialization)
- the semantics about overriding/shadowing immutable/final field is different from Java

Can we somehow change the semantics, so that field accesses like `C.this.x` are only translated into virtual calls if `x` is a delayed field?

ping @odersky

**Comment by Blaisorblade** [comment]
I agree the semantics is problematic and worth reconsidering, but this particular fix seems to have a bunch of bigger problems. Like, it has more problems requiring non-lazy-vals to be final (which we already did for classes): I don't believe that can be changed either, but since we have non-threadsafe lazy vals now, I suspect we should look at it again — alternatively, we could make linting tools warn about that.

Or, in fact, maybe we should first look at the state of the art that @odersky pointed at — "Freedom before commitment".

> Can we somehow change the semantics, so that field accesses like C.this.x are only translated into virtual calls if x is a delayed field?

I'd expect changing semantics for existing code would lead to major breakage.

Moreover, client calls to `x` must translate to virtual calls, so you're proposing giving different semantics to `this.x`. Worse, now `this.x` has one value in `Foo` and a different value in `Bar`. That's indeed Java's semantics in this case, except that Java would reject `override val`, and that Java's semantics are also confusing.

While we're looking at this, it's also disappointing that `override val` creates a new field in the object, tho I'm not sure how to fix that either if the new field has a narrower type; either the user or the compiler can give the field an abstract type, but after erasure that requires casts on each access with the new field.

**Comment by liufengyun** [comment]
> Moreover, client calls to `x` must translate to virtual calls, so you're proposing giving different semantics to `this.x`.

Client code will be `o.x`, which is different from `this.x`.  For Java, the client code `o.x` behaves the same as `this.x`:

```Java
class Foo {
  final int x;
  final int y;

  Foo() {
    x = 6;
    y = x + 5;

    assert(y == 11);
  }
}

class Bar extends Foo {
  final int x;
  Bar() {
    super();
    x = 10;
  }
}

class Test {
  public static void main(String[] args) {
    Bar b = new Bar();
    Foo f = b;
    System.out.println(b.x); // print 10
    System.out.println(f.x); // print 6
  }
}
```

**Comment by Blaisorblade** [comment]
> Moreover, client calls to x must translate to virtual calls, so you're proposing giving different semantics to this.x.

Right, I meant "different semantics to `this.x` and `o.x`"; again, I regard field shadowing as a confusing misfeature.

**Comment by liufengyun** [comment]
Close this now, semantic change will cause back-compatibility problems.

For safe initialization, the analysis should add an annotation to fields used during initialization, and limit overriding/implementation of those fields to primary constructors.
