### ISSUE TITLE
Type parameter inference is too eager to widen union types

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#4867]
From https://stackoverflow.com/questions/51575183/dotty-seq-mapping-to-union:
```scala
object UnionMapping {
  private def parse(string: String): Int | Double = {
    if(string.contains("."))
      string.toDouble
    else
      string.toInt
  }

  def test_number = {
    val strings: Seq[String] = Seq("123", "2.0", "42")
    // Works
    val asdf: Seq[AnyVal] = strings.map(parse(_))
    // Fails to compile
    val union: Seq[Int | Double] = strings.map(parse(_))
  }
}
```
There's enough hints here that type inference should be able to do the right thing and not widen `Int | Double` to `AnyVal`.

**Comment by abeln** [comment]
@smarter I'd be interested in learning a bit about the type parameter inference. If this bug seems somewhat accessible, can you point me to where in the code I should be looking at for this change? Thanks!

**Comment by smarter** [comment]
The current logic is here: https://github.com/lampepfl/dotty/blob/34baac4b69ef9bc764c8a6d0d4c8cd458759a5e4/compiler/src/dotty/tools/dotc/core/ConstraintHandling.scala#L297-L301

To give some context: we avoid inferring union types for the same reason we avoid inferring singleton types, because sometimes they're "too precise". E.g.:
```scala
scala> List(1, "")
val res0: List[Any] = List(1, )

scala> List(if (true) 1 else "")
val res1: List[Any] = List(1)
```
The problem is that we do not distinguish between an inferred union type and a union type actually written down by the user:
```scala
scala> val x: Int | String = 1
val x: Int | String = 1

scala> List(x)                                                                                                                                                                                                                               
val res2: List[Any] = List(1)
```

This is tricky to fix since we'd need to have a way to distinguish `|` written down by the user from `|` made up by the compiler (maybe using an annotation?).

(If you're looking for issues related to type inference, I've left a sketch of how to fix things in https://github.com/lampepfl/dotty/issues/4742, but it's not super easy either)

**Comment by abeln** [comment]
Thanks! I'll take a look at https://github.com/lampepfl/dotty/issues/4742

**Comment by nicolasstucki** [comment]
I fell into a similar case with `quoted.Expr`

```scala
class Expr[+T]
def foo(): Char | String = bar/*[Char | String]*/(impl())
def bar[T](expr: Expr[T]): T = ???
def impl(): Expr[Char | String] = ???
```

Which fails with

```scala
8 |  def foo(): Char | String = bar/*[Char | String]*/(impl())
  |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |                             Found:    Any
  |                             Required: Char | String
```

**Comment by Baccata** [comment]
I'm encountering this issue as well : https://scastie.scala-lang.org/GW8xTsFARp22lzpTI7nb5Q

**Comment by landerlo** [comment]
This inference enhancement for union inference follows @smarter 's suggested approach of preserving the union if there is an explicit union ascription. Otherwise the union is joined.

Uses the very naive but effective approach of lexically checking the untyped tree for Or operators.

The fix only touches the OrType joining point where this lexical check is introduced. If the Or operator is the type tree of the term, this is seen as a hint of an explicit union ascription. This heuristic works well for the case in @Baccata 's code and other union type inference issues in my own exploration.

IMO the non-rigorous approach is justified as this is a very targeted check that simply defers the joining of the union type, in the worst case, the union would be joined at a later time. I couldn't foresee any negative impacts by not joining as when this check is only performed when the typer has detected the union. For the case when the heuristic misses an ascription this would only mean the join is performed eagerly as per the current semantics.

We get the a more expressive union type inference with no cost, as the untyped tree check won't impact performance or require code changes that could interact with the typer in unexpected ways.
The current checks on whether there is an Or operator on the tpt of ValDef or the tpt of a DefDef is a TypedSplice covers the explicit union ascriptions of terms and functions signatures.

**Comment by landerlo** [comment]
https://github.com/lampepfl/dotty/pull/7829

**Comment by odersky** [comment]
This works by now.
