### ISSUE TITLE
Inconsistent name resolution

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#5210]
```scala
package foo {
  object A {
    val x = 5
  }
}

package foo.bar {
  object A {
    val x = "foo"
  }
}

package foo {
  import foo.bar._

  object B {
    val y: Int = A.x // should resolve to `foo.A.x` or `foo.bar.A.x`?
  }
}
```
In the above example, in object `foo.B`, `A.x` resolves to `foo.A.x`. But if put in different files, it resolves to `foo.bar.A.x`.

My expectation is that the behaviour should be consistent whether or not the source is split into multiple files.

**Comment by odersky** [comment]
> My expectation is that the behaviour should be consistent whether or not the source is split into multiple files.

That's actually the way it is specified and (I would argue) the way it should be. Definitions take precedence over imports, that's why A.x resolves to foo.A.x. But definitions count as such only if they are declared in the same file. Otherwise, a member of a package could shadow an import, which makes compilation vulnerable to what is on your classpath.
