### ISSUE TITLE
Requirements for type bounds stricter than scalac

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#525]
Not sure if this is something that we want to change or not, but:
```scala
class Foo[T] {
  def foo[A, B >: T <: A] = {}
}
```
fails with:
```scala
try/tv.scala:2: error: lower bound Foo$$T does not conform to upper bound A
  def foo[A, B >: T <: A] = {}
               ^
one error found
```
But it compiles with `scalac`.

The code can easily be changed to also compile with dotty:
```scala
def foo[A >: T, B >: T <: A] = {}
```
Do we want to be compatible with `scalac` here? I came across this because `./tests/pending/pos/strip-tvars-for-lubbasetypes.scala` relies on it, but we could modify that test.

**Comment by odersky** [comment]
I'd like to leave that open for a while. It would be good to get input from theory (DOT) on that question.

**Comment by samuelgruetter** [comment]
From a soundness point of view, this shouldn't matter, because at use site, bounds conformance is checked anyways, and if a function is never used, nothing can go wrong.

But from a language design point of view, I find it more consistent to reject this example, because if you do "the same" with type members, it's also rejected:

```scala
class Foo[T] {
  type A
  type B >: T <: A
}
```

**Comment by odersky** [comment]
@samuelgruetter Good point. So I think we can leave it as it is.

**Comment by odersky** [comment]
I agree now that soundness is not the issue. The problems I was thinking of before all had to do with null being handled specially or with lazy values. In short, we manufactured an empty type plus a value that had that type. The value was either null or a lazy val. Without this trick I do not see how empty bounds could cause us a problem.

**Comment by samuelgruetter** [comment]
Turns out it's not a soundness issue, but an expressiveness issue: The test in `tests/pending/pos/t4853.scala` seems to do something "useful":

```
object Animal {
  def main(args: Array[String]): Unit = { new Animal[Awake].goToSleep }
}

class Animal[A <: AwakeOrAsleep] {
  def goToSleep[B >: A <: Awake]: Animal[Asleep] = new Animal[Asleep]
  def wakeUp[B >: A <: Asleep]: Animal[Awake] = new Animal[Awake]
}

sealed trait AwakeOrAsleep
trait Awake extends AwakeOrAsleep
trait Asleep extends AwakeOrAsleep
```

but it's rejected with the error `lower bound Animal$$A does not conform to upper bound Awake`.
One could rewrite this example to use a parameter `(implicit evidence: A <:< Awake)`, though.
