### ISSUE TITLE
Tasty version bumping

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#5308]
_Originally posted by @odersky in https://github.com/lampepfl/dotty/pull/5307#issuecomment-431881772_

> @odersky: I don't know what the policy wrt bumbing the Tasty version is. Say you have two PR's and they each bump the version from 11 to 12. Then what is the right version? Alternatively, could we bump the TASTY version only for each release if there is a change in TASTY? That would limit the bumping speed to at most one every 6 weeks or so. I am not sure what scheme is preferable. What do others think?

**Comment by smarter** [comment]
> Say you have two PR's and they each bump the version from 11 to 12. Then what is the right version?

Once once of the PR has landed, the other should be rebased to bump to 13.

> Alternatively, could we bump the TASTY version only for each release if there is a change in TASTY? 

Bumping tasty when we notice that we break it is good practice for when we'll start getting serious about stabilizing it I think. Additionally, because of incremental compilation, we sometimes end up mixing up tasty from different compiler instances, this can lead to weird errors if we don't bump the tasty version to get a hard failure on unpickling.
