### ISSUE TITLE
Syntax Error with new match types

### ISSUE THREAD

**Issue by flomebul** [lampepfl/dotty#5349]
I have an issue with Dotty 0.10.0-RC1.

Using dotr, the first line
`type FOk[T] = Int`
compile fine, But
`type FKo[T] <: AnyVal = Int;`
results to an error (a [E040] Syntax Error using dotc)
`type FKo[T] <: AnyVal = Int;
                           ^^^
                           'match' expected, but ';' found`
Is it a bug on dotty or on my side ?

**Comment by allanrenucci** [comment]
I am not sure what you want to express but this is not valid syntax with `scalac` either

**Comment by AleksanderBG** [comment]
@flomebul There's no bug, the error message is just confusing - you can only write `type X <: Y = Z` with match types, so the compiler was expecting a `match` in place of the semicolon. If you think about it, in `type IntAlias <: AnyVal = Int` the `<: AnyVal` part is meaningless and doesn't really change anything.

@allanrenucci I'd say the problem here is simply the error message being confusing. It's not unreasonable for a user to expect that they can write the `<: T` part for a non-match type, especially if they saw match types previously. Perhaps we should issue a special-case warning for code like this?

**Comment by flomebul** [comment]
Ok, I understand now.
For the case I posted, I think that a coment like "'match expected due to upperbound but ..." would be more understandable. I will goback on my initial and more complex case to review it with these clarifications.

**Comment by flomebul** [comment]
Hello. I'm back after a long time :-)
I rework my initial issue and this is the new case I can propose:
With the folowing definition

trait N
trait Z extends N
trait S[P <: N] extends N

I try this

type T[X <: N] <: N = X match {
 case Z => Z
 case S[p] => T[p]
 }

Wand obtain the following error:
3 case S[p] => T[p]
                      ^^^^
            found:    T[p]
            required: N

            where:    p is a type in type T with bounds <: N

I expected that "T[p] <: N" can be deduced by the compiler.

**Comment by AleksanderBG** [comment]
@flomebul please open a separate issue. I'm closing this issue - we've discussed it and decided that for the time being we won't be emitting special error messages for parse errors like the one in the original message.
