### ISSUE TITLE
IDE: Statements in top-level objects in a worksheet should be executed and their output displayed on the side

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#5400]
In the Eclipse worksheet, wrapping a statement in an object does not change the fact that it gets executed when the worksheet is run, but in our current worksheet support, the only output we see is `// defined object Foo`

**Comment by Duhemm** [comment]
I think I don't understand this issue.

This is what happens in Eclipse when I create an object in the worksheet:
```scala
object myworksheet {
  println("Hello, world!")                        //> Hello, world!
  object O {
    println("Hello from O")
  }
  println("Goodbye!")                             //> Goodbye!
}
```

This is running Scala IDE 4.7.0 with Scala 2.12.3.

The "equivalent" worksheet in Dotty IDE would be:
```scala
println("Hello, world!")                        //> Hello, world!
object O {
  println("Hello from O")
}                                               //> defined object O
println("Goodbye!")                             //> Goodbye!
```

In Dotty IDE, the worksheet is implicitly wrapped in an object. It is done implicitly, because unlike Scala IDE, we don't have a wizard that will create the structure of the worksheet for the user.

Are you suggesting that we should detect whether the user is doing the wrapping by himself?

**Comment by smarter** [comment]
Ah I see, I got confused by the top-level object in the Eclipse worksheet. I guess it's not worth the extra complexity to handle more.
