### ISSUE TITLE
Assertion failure when compiling volatile.scala + .java file using volatile

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#5610]
In a file `Test.scala`:
```scala
package scala {
  @scala.annotation.meta.field
  class volatile extends scala.annotation.StaticAnnotation
}

class Test {
  def test(x: TestJava): Unit = {
    x.vol = 1
  }
}
```
In a file `TestJava.java`:
```
class TestJava {
  public volatile int vol = 0;
}
```
```
dotc -Ycheck:all Test.scala TestJava.java
...
checking Test.scala after phase genSJSIR
java.lang.AssertionError: assertion failed: class defined twice class volatile 321 2866
	at scala.Predef$.assert(Predef.scala:223)
	at dotty.tools.dotc.transform.TreeChecker.testDuplicate(TreeChecker.scala:54)
	... 
```

**Comment by smarter** [comment]
It works if you use `-sourcepath x` and put the redefinition of `volatile` in `x/scala/volatile.scala`. In general, whenever part of the stdlib is recompiled, it needs to be on the sourcepath, because some symbols are forced very early on before we've entered the symbols from the sources we're compiling. Using -sourcepath avoids the issue because symbols will always be looked up from the sources in the sourcepath as well as the classpath.
