### ISSUE TITLE
Error while handling unicode characters in REPL

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#5755]
Writing 
```scala
scala> class 😃
```

and then backspace 3 times confuses the repl

```scala
scala> cclas
```

There is probably a wrong computation of the current cursor in presence of unicode characters.

**Comment by smarter** [comment]
is this a JLine bug ?

**Comment by liufengyun** [comment]
Cannot be reproduced.

**Comment by nicolasstucki** [comment]
Copy paste `class 😃` into the REPL and then delete 3 characters. It still happens.

**Comment by philwalk** [comment]
I'm able to reproduce this FWIW

**Comment by smarter** [comment]
Can you reproduce this using the Scala 2.13.3 repl too? If so, it's a JLine bug and should be filed at https://github.com/jline/jline3/

**Comment by philwalk** [comment]
Running on WSL ubuntu, I can't reproduce the problem in either the dotty REPL or the scala 2.13.3 REPL.
Running in the sbt scala console under Intellij IDE, unable to reproduce the problem.

Running on the Windows jdk, there are problems in both dotty and scala 2.13.3, although they differ.   Below is a discription of what I think I'm getting, but I need to thoroughly verify the specifics of my Windows environment, since I'm having other problems with sbt.

Running dotty REPL in mintty/bash on Windows 10. the problem occurs exactly as described by @nicolasstucki.
Running the Scala 2.13.3 REPL in mintty/bash, there is an issue where all but the initial character can be deleted, but the initial 'c' remains. 

Interestingly, if I enter the REPL from SBT,  the problems go away, it only occurs when running the `dotr` script from the console.

**Comment by smarter** [comment]
Does it work when using the new Windows Terminal (https://github.com/microsoft/terminal) ?

**Comment by philwalk** [comment]
Here's my experiment, performed on Windows 10 x64

1. cd to a dotty project
2. sbt console
3. paste "class 😃"
4. hit "backspace" 3 times

Here's what remains:

`scala> cclas`

**Comment by philwalk** [comment]
Unable to reproduce this problem using sbt 1.4.7 in any of several Windows shell environments"

- cygwin
- mingw64
- mingw32
- msys-64
- WSL-Linux

and across 4 terminals:

- mintty
- conemu
- windows terminal
- CMD.EXE

Perhaps this was fixed as a side-effect of recent changes.

**Comment by nicolasstucki** [comment]
Now if I paste `class 😃` in Mac I get
```scala
scala> class 
```
Does not misalign anymore but it is a different regression with usicode characters.

Same happens if we paste the usicode character `'😃'` in a string

```
scala> ""
val res0: String = 
```

**Comment by SethTisue** [comment]
The weird/incorrect backspacing before reproduces for me on 3.3.1 and 3.4.1-RC1-bin-20240212-c529a48-NIGHTLY on MacOS. (I don't get the thing Nico mentions with the box — I see the smiley face.)

The problem doesn't happen in Scala 2.13.12 or 2.13.13. So it's possible it's a JLine bug and perhaps it would go away if Dotty were to upgrade to a newer JLine version — that's the first thing to try. 2.13.13 is on JLine 3.24.1, whereas here in this repo you're still on 3.19.

**Comment by hamzaremmal** [comment]
If we add a new line between the class and the emojis and backspace, it does work correctly.
```scala
scala> class
     | 😃
```
