### ISSUE TITLE
Casting to Unit

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#5791]
With Scala 2:
```scala
scala> "Hello".asInstanceOf[Unit]
// OK, nothing happens
```
With Dotty:
```scala
scala> "Hello".asInstanceOf[Unit]                                                                                                                                                                               
java.lang.ClassCastException: java.lang.String cannot be cast to scala.runtime.BoxedUnit
```
What is the right behavior?

**Comment by sjrd** [comment]
FWIW, the behavior of Scala 2 is, let's say, convenient for Scala.js. ;)

**Comment by smarter** [comment]
@sjrd can you elaborate ? This seems pretty wrong to me, and the scala spec doesn't mention it.

**Comment by sjrd** [comment]
Scala.js specifies that the result of any call to a JS method is explicitly cast to the declared result type of the method. We need this because JS can return anything, really, so the cast is necessary for soundness.

Now for methods that are declared as returning `Unit`, we want to tolerate the fact that JS might return something else than `undefined`, and we don't to spend code and time checking that it's actually `undefined`. The fact that `.asInstanceOf[Unit]` works as it does in Scala 2 means we don't need to special-case that (both in spec and in the implementation).

**Comment by smarter** [comment]
Sounds like Scala.js should use an ascription `: Unit` here really :).

**Comment by sjrd** [comment]
That wouldn't be consistent with the other types, which must be cast.

**Comment by LPTK** [comment]
@AleksanderBG `asInstanceOf` is just an unsafe escape hatch from the type system. It's not meant to be sound and never will be, because of erasure. For example consider `List(1).asInstanceOf[String]`, or `def f[A](x:Any):A=x.asInstanceOf[A]; f["b"]("a")`.

**Comment by sjrd** [comment]
To go a bit further than what @LPTK says, `x.asInstanceOf[A]` is basically specified as "do something implementation-dependent that convinces the runtime to let me use `x` as an `A`". So `"b".asInstanceOf["a"]` succeeding is OK, because the runtime was convinced.

Similarly, in Scala.js, we are looking at soundness from the point of view of the erased type system of the IR. As such `"b".asInstanceOf["a"]` would also succeed and be just as sound, because the IR deals with `string`s, not with singleton types.
