### ISSUE TITLE
RepeatedParamType should not be a subtype of anything (until ElimRepeated)

### ISSUE THREAD

**Issue by adriaanm** [lampepfl/dotty#5792]
While looking at scala/bug#4775, scala/bug#8344, scala/bug#11015, I was thinking that `T*` should not be a subtype of `Seq[T]` (nor even `Any`, as it's not an expression type) until we've eliminated repeated params. This is important for overloading resolution (see referenced bugs).

Right? 🤔

**Comment by AleksanderBG** [comment]
compat:scala2, since we reintroduce behaviour that was removed in https://github.com/scala/bug/issues/8344.

Some notes from me trying to fix this:
- overload selection sees `Seq[X] @Repeated`, which suggests to me that it happens post-ElimRepeated
- we cannot really special-case subtyping for `Y @Repeated`, since this is also the type of the argument inside the body of a function
