### ISSUE TITLE
Remove -Xmax-classfile-name; hard-code to 240, like Scala 2.13.0-RC1

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#5812]
See https://github.com/scala/scala/pull/7497

**Comment by IDoCodingStuffs** [comment]
Working on this, will create PR

**Comment by Blaisorblade** [comment]
Status: `-Xmax-classfile-name` seems to not work yet, and `dotc -Xmax-classfile-name 240 tests/pending/run/t8199.scala` seems to confirm it (retesting with latest master).
https://github.com/lampepfl/dotty/pull/5872#issuecomment-462008994

**Comment by nigredo-tori** [comment]
I've just found https://github.com/scala/scala/pull/7497 and this MR. These don't take into account one use case: in one of my work projects we had to enable `-Xmax-classfile-name` since our project failed to compile or work (can't remember which) on Windows otherwise. The thing is, WinAPI has a [path length limit of 260](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation), which means that a 240-character file in an average SBT project would pretty much always go over.
To circumvent this there is a `\\?\` hack, and Windows 10 [allows changing this limit](https://mspoweruser.com/ntfs-260-character-windows-10/). Also, newer Scala versions are less likely to produce huge class names like this. Still, IMO, 240 character limit should be lowered.

**Comment by smarter** [comment]
@nigredo-tori Making this flag work correctly is really non-trivial (as demonstrated by the fact that that both the Scala 2 and Dotty implementation were always broken). If Windows has an option to change the path limit, then we should just tell people who get an error to go set that option instead of telling them about -Xmax-classfile-name.

**Comment by smarter** [comment]
`-Xmax-classfile-name` was removed in https://github.com/lampepfl/dotty/pull/5872 but the limit is still not respected: https://github.com/lampepfl/dotty/pull/5872#issuecomment-462008994, we should figure this out before 3.0 since it's an ABI issue.
