### ISSUE TITLE
dotc requires `override` to implement abstract java method

### ISSUE THREAD

**Issue by lrytz** [lampepfl/dotty#6152]
A.java

```java
public abstract class A {
  public abstract Object f();

  public static abstract class B extends A {
    @Override
    public abstract String f();
  }
}
```

Test.scala
```scala
class C extends A.B {
  def f() = ""
}
```

gives

```
-- Error: Test.scala:2:6 -------------------------------------------------------
2 |  def f() = ""
  |      ^
  |      error overriding method f in class B of type (): Object;
  |        method f of type (): String needs `override' modifier
one error found
```

**Comment by odersky** [comment]
Looks like it sees the Java-emitted bridge. I did not know that Java emits bridges for abstract methods.

**Comment by anatoliykmetyuk** [comment]
I cannot reproduce it at commit `5f28215ac` via `dotc A.java Test.scala` command from the SBT console.

**Comment by newca12** [comment]
I manage to reproduce it with -language:Scala2

**Comment by anatoliykmetyuk** [comment]
Hm, strange, `dotc -language:Scala2 A.java Test.scala` doesn't reproduce it either. What commit are you on @newca12?

**Comment by newca12** [comment]
Try with 2 steps :
javac A.java
dotc Test.scala

**Comment by smarter** [comment]
To understand why there's a difference here, it's helpful to know that:
- Under joint compilation of .java and .scala sources, the compiler will parse the .java source files and generate symbols for them (https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/parsing/JavaParsers.scala)
- Under separate compilation, the compiler will parse the classfiles generated by javac and generate symbols for them (https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala)

Both of these approaches should be equivalent and if they're not it's probably a bug. In both cases the parsing code was adapted from scalac years ago (https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/nsc/javac/JavaParsers.scala, https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala) and there might have been improvements done on the scalac side that haven't been ported to dotty (e.g. https://github.com/lampepfl/dotty/issues/6136)

**Comment by smarter** [comment]
Also various parts of the compiler check the `JavaDefined` flag which is set on symbols coming from java source files and classfiles.

**Comment by smarter** [comment]
Some more observations: it's interesting to note that [`member` in Scala 2 excludes members with the bridge flag by default](https://github.com/scala/scala/blob/8f3a05a802aa3cc28212fc5501db31e6f1d499d6/src/reflect/scala/reflect/internal/Types.scala#L630-L631), where as [`member` in Dotty doesn't do that](https://github.com/lampepfl/dotty/blob/5f28215ac5938e58091cf766afe65d99409a289a/compiler/src/dotty/tools/dotc/core/Types.scala#L529-L531). Exclusion also works differently in both compiler, in Scala 2 if a symbol with an excluded flag overrides a symbol without the flag, the overridden symbol is returned, whereas no symbol is returned in Dotty. Aligning ourselves with Scala 2's behavior here might be enough to fix this issue. Alternatively we could also simply skip bridge methods found by the ClassfileParser since they shouldn't influence compilation anyway.
