### ISSUE TITLE
Colour leakage in error report

### ISSUE THREAD

**Issue by Glavo** [lampepfl/dotty#6559]
![image](https://user-images.githubusercontent.com/20694662/58275115-e1fd9600-7dc6-11e9-9b0f-049106f96404.png)

**Comment by smarter** [comment]
That's not a leak, that's intentional: the red/green colors highlight the diff between two lines, here it looks a bit weird since `2` is replaced by `1) | Int(0`, but it's correct. Perhaps someone can come up with a better way to highlight the differences between the found and required types, but meanwhile I'll close this.
