### ISSUE TITLE
Overloaded copy method with default arguments error

### ISSUE THREAD

**Issue by andreaTP** [lampepfl/dotty#6670]
Error message:
```
two or more overloaded variants of method copy have default arguments
```

Reproduction:
```scala
case class X[A](
  foo: A,
  bar: String = ""
) {
  def copy(
    foo: A = foo,
    bar: String = bar
  ) = ???
}

val x = X(1)
x.copy(bar = "BAZ")
```
Note that without the type parameter `A` the error is not triggered and this code happily compile with scalac 2.12

**Comment by OlivierBlanvillain** [comment]
This is due to the fact that the copy method is added as a desugaring even in the presence of a user define copy:

https://github.com/lampepfl/dotty/blob/47c126a93a88545b872c47b3004639092b85b9c9/compiler/src/dotty/tools/dotc/ast/Desugar.scala#L549-L564

I'm going to put this at low priority given that there is a simple workaround: fallback to a class

**Comment by odersky** [comment]
The `copy` method can be given explicitly, but it must in this case match the type of the method that would otherwise be generated. For the example above we need:
```scala
def copy[A](
    foo: A = foo,
    bar: String = bar
  ): X[A] = ???
```
In that case no `copy` method is synthesized and no clash occurs.
