### ISSUE TITLE
CI has been failing to publish nightly

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#7066]
CI has been failing to publish nightly. See
* https://dotty-ci.epfl.ch/lampepfl/dotty/771/1/8
* http://repo1.maven.org/maven2/ch/epfl/lamp/dotty-compiler_0.18/

**Comment by smarter** [comment]
> [error] Failed: RepositoryWritePolicy, failureMessage:Artifact updating: Repository ='releases:Releases' does not allow updating artifact='/ch/epfl/lamp/dotty_0.18/0.18.0-bin-20190817-848a1cd-NIGHTLY/dotty_0.18-0.18.0-bin-20190817-848a1cd-NIGHTLY-javadoc.jar' 

It's failing because it's trying to publish a nightly that already exists (http://repo1.maven.org/maven2/ch/epfl/lamp/dotty-compiler_0.18/0.18.0-bin-20190817-848a1cd-NIGHTLY/) this happens everytime the nightly job is run and there has been no new commits on master since the previous one, so this is a known, low-priority problem. Fixing it would require making the nightly publishing scripts detect this situation and exit gracefully.

**Comment by allanrenucci** [comment]
For reference #3243
