### ISSUE TITLE
Documentation on implicit specificity is out of sync with implementation

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#7075]
http://dotty.epfl.ch/docs/reference/changed-features/implicit-resolution.html says:
> All else being equal, an alternative that takes more inferable parameters is taken to be more specific than an alternative that takes fewer. 

And the documentation in the code says https://github.com/lampepfl/dotty/blob/6f6751d5eb7f4b667f499f6326970d55b0ae62af/compiler/src/dotty/tools/dotc/typer/Applications.scala#L1261-L1263

But actually the implementation does the exact reverse: https://github.com/lampepfl/dotty/blob/6f6751d5eb7f4b667f499f6326970d55b0ae62af/compiler/src/dotty/tools/dotc/typer/Applications.scala#L1434-L1436

As far as I remember, the current implementation is the intended behavior that was implemented after experimenting with the documented behavior. @milessabin: do you confirm ? Also in your experience, is the current behavior helpful/neutral/harmful for the stuff you want to do ?

**Comment by milessabin** [comment]
I can confirm that that was the decision, although I still feel that we should have explored options which would have allowed us to keep the original (ie. more arguments win, as documented) semantics.

Most of the work I've done in shapeless 3 has used specializing inline rather than implicits, so the implicit selection rules have been backgrounded somewhat. If we're revisiting inlining then these rules might become more important again, but it's hard to say whether we've done the right thing here or not without more experience.
