### ISSUE TITLE
Allow calling splices in the same project

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#7138]
Staging is hampered by the requirement that code called in a splice has to be in an upstream project. We should try to avoid that restriction.

**Comment by liufengyun** [comment]
This may potentially kill incremental compilation for a project if it executes code defined in the same project (see #7042).

Just a reminder, not a reason to stop from doing it --- programmers just need to do a clean build when they run/package, the same as they do for macros today (there two projects are involved instead of one project).

**Comment by nicolasstucki** [comment]
The problematic part for incremental compilation with macros is that any call to a macro needs to be recompiled if the code of the macro (or whitebox inline) or any method it calls has changed. This is clearly more complex that keeping track of signatures for for normal calls. This is the same as in Scala 2 macros.

To support macros expanding in the same project we will need to first check that all the code that a macro needs to execute does not use the macro itself. This would require some some kind of abstract interpreter or call graph analysis. The information that we would get from that analysis could fix (or improve) the incremental compilation issues as well.

**Comment by odersky** [comment]
This is implemented now, right? Can we close the issue?
