### ISSUE TITLE
Decide on final replacement for `implicitly`.

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#7152]
We currently use `the` as a replacement of `implicitly`. This works well if there is an explicit type argument, i.e. 
```scala
the[Ordering[String]]
```
but it looks positively strange when the argument is omitted, i.e
```scala
val ord: Ordering[String] = the
```
One alternative would be to use `theGiven` instead. I.e.
```scala
theGiven[Ordering[String]]

val ord: Ordering[String] = theGiven
```
`theGiven` is a bit longer but works adequately in both scenarios.

This change is elaborated in #7150 (docs only, no implementation).

**Comment by smarter** [comment]
`the` is also hard to search for (in fact, I tried to search for previous discussions on using the name `the` and couldn't find them). I think `summon` could work. A wilder alternative would be to just use brackets: `[Ordering[String]]` instead of `the[Ordering[String]]`, and simply `[]` instead of `the`. This might be too confusing, but google deals with symbols pretty well these days: https://www.google.com/search?client=firefox-b-1-d&q=c+%5B%5D

**Comment by milessabin** [comment]
Could we make plain `given` work here too?

```scala
given[Ordering[String]]

val ord: Ordering[String] = given
```

**Comment by neko-kai** [comment]
`infer` could work for all of these, but especially instead of `implicitly`

**Comment by odersky** [comment]
Using just `given` would work, but would make it syntax where none is needed. I am OK with `summon`, too.

**Comment by smarter** [comment]
`given` would be a bit awkward, e.g.: `foo(given given[Int])`

**Comment by milessabin** [comment]
@smarter that's your punishment for not just writing `foo` ;-)

**Comment by SethTisue** [comment]
2 cents: I love `summon`, it is vivid, it is charming without being cute, and it is searchable. but `theGiven` isn't bad

**Comment by odersky** [comment]
I changed the docs in #7150 to use `summon`. I also think it has a nice sparkle. Not as dry as `theGiven`.

**Comment by odersky** [comment]
We settled on `summon`, in the end.
