### ISSUE TITLE
Incorrectly constructed trees when inlining with bound type parameters

### ISSUE THREAD

**Issue by anatoliykmetyuk** [lampepfl/dotty#7293]
## minimized code

```Scala
trait Foo { def f(x: Int): Any }

inline def f[T <: Foo]: T = (??? match {
  case t: T => t.f(10)
}).asInstanceOf[T]

@main def Test = f
```

Says:

```scala
-- Error: ../pg/i3.scala:4:18 --------------------------------------------------
4 |  case t: T => t.f(10)
  |               ^^^^^^^
  |     undefined: t.f # 1201: TermRef(TermRef(NoPrefix,val t),f) at frontend
one error found
```

## expectation
It should compile.

**Comment by odersky** [comment]
The problem is that the type parameter to `Test` is instantiated to `Nothing`, which means the body of `f` can no longer be typed since it contains a selection `t.f` where `t` has type `Nothing`.

It's not quite clear what's the best remedy here: 

 - disallow all instantiations of type params of inline methods with a bottom type? This could make useful programs illegal.

 - or try to improve the error message. But in light of all the situations where a `Nothing` type could creep in and mess things up it looks hard to do a complete job. And not sure it's worth it in complexity.

**Comment by odersky** [comment]
On hold until someone has figured out what to do here.

**Comment by odersky** [comment]
We now get:
```scala
  |               value f is not a member of Nothing
```
which is correct since the scrutinee `???` is of type `Nothing`.

If we fix the program to
```scala
rait Foo { def f(x: Int): Any }

inline def f[T <: Foo]: T = ((??? : Foo) match {
  case t: T => t.f(10)
}).asInstanceOf[T]

@main def Test = f
```
we get:
```
- Error: ../new/test.scala:7:17 -----------------------------------------------
7 |@main def Test = f
  |                 ^
  |f cannot be accessed as a member of (t : Nothing) from module class test$package$.
  |-----------------------------------------------------------------------------
  |Inline stack trace
  |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  |This location contains code that was inlined from test.scala:4
4 |  case t: T => t.f(10)
  |               ^^^
   -----------------------------------------------------------------------------
1 error found
```
This looks also correct to me.
