### ISSUE TITLE
Use integers versus English words for warnings and errors

### ISSUE THREAD

**Issue by ekrich** [lampepfl/dotty#7355]
I just noticed that warning and error numbers are not integers for low numbers. This seems like this could affect tools that may need to parse the output and is more difficult for non English readers as well.

Example:
```Scala
[warn] three warnings found
[error] four errors found
```

**Comment by som-snytt** [comment]
This is standard orthography. "Three days ago" and not "3 days ago" unless you're texting or composing a pop song.

Tools from the 1980s that don't understand "three" should be retired.

Build tools should use `reporter.errorCount` or equivalent.

Formatting is normally contextual, such as the output of `ls -l`, which is a time of day for recent files and year otherwise.

If localization is a goal, `drei Fehler gefunden`, then maybe there is a convention for a numeric locale that prefers all numbers be expressed in digits, in a preferred radix.

**Comment by OlivierBlanvillain** [comment]
Consistently using numbers is just so much easier to parse for humans. As a person with dyslexia, I can tell you that kind of detail actually goes beyond aesthetic, I find it genuinely annoying.

I don't buy the standard orthography argument, if the standard is stupid we shouldn't follow it. Also, this is a compiler, not a poetry emiter...

**Comment by som-snytt** [comment]
@OlivierBlanvillain emitter

I have a certain way of understanding words, but I would stand by my assertion that localization is a thing.

I don't insist that absent a compiler option 3 or three must be preferred.

I do think it's crazy that my daughter can ask her device to set her alarm for seven in the morning, but we need discussions whether tools can understand "three".

Full disclosure: when someone came to my company in 1999 to discuss infrastructure for what he described as a star trek universal translator, I thought he was playing us. OTOH, a Chinese speaking acquaintance tried to use google translate for some simple but important communication recently and failed.

**Comment by som-snytt** [comment]
Actually, after just reading that China TV won't broadcast NBA games because they have a narrow understanding of "free speech", I apologize for using an argument from orthography as such.

I prefer to emphasize my argument about localization and respecting efficiencies of communication which are contextual.

**Comment by BluePat** [comment]
Is help still wanted? If it is, I would love to contribute. Seems like a good first issue.

**Comment by BluePat** [comment]
Sorry, it took so long. I was quite busy. Please review [my pull request](https://github.com/lampepfl/dotty/pull/7527).  
Hope I haven't missed anything.

**Comment by OlivierBlanvillain** [comment]
#7527
