### ISSUE TITLE
Infinfite loop when returning anonymous higher kinded type

### ISSUE THREAD

**Issue by mwisnicki** [lampepfl/dotty#7602]
## minimized code

```Scala
type X[T] = ({ type F[_]; type R = F[T]})#R
```

## expectation

This compiles in Scala 2.13 but fail in latest dotty with `Recursion limit exceeded.`

## context

While it doesn't matter for this bug what I'm actually trying to define is

```Scala
trait Monad[F[_]]
type of[M[_[_]], T] = ({ type F[_]; type R = (given M[F]) => F[T]})#R
def foo(a: Monad of String) = ???
```

**Comment by odersky** [comment]
The problem is that structural types with type members are allowed only as an afterthought. I believe neither scalac nor dotc implements them properly, and, furthermore, the implementation schemes are completely different. If I lift out the type members into a base class, the code compiles:
```
class C[T] {
  type F[_]; type R
}

type X[T] = (C[T] { type F[_]; type R = F[T]})#R
```
Would such a lifting be acceptable?
