### ISSUE TITLE
Inconsistent type widening between conditional extension methods and extension methods of given instances

### ISSUE THREAD

**Issue by julienrf** [lampepfl/dotty#7886]
## minimized code

```Scala
// --- Extension method implemented as a member of a given instance ---
trait Bar[F[_]] {
  def [A](fa: F[A]) bar = ()
}
implicit def barOption: Bar[Option]
  
Some(42).bar // OK

// --- Conditional extension method ---
trait Baz[F[_]]
def [A, F[_] : Baz](fa: F[A]) baz = ()
implicit def bazOption: Baz[Option]
  
(Some(42): Option[Int]).baz // OK
Some(42).baz                // Error
```

Try it here: https://scastie.scala-lang.org/DrR9tpk5Q1SckrVKcvAl8A

If `F` is contravariant in `Baz`, the type error disappears.

## expectation

Both forms should either type check or produce a type error.

**Comment by odersky** [comment]
I don't see why both should behave the same. There is no meta principle that would require this. The second example is clearly harder since it requires to widen Some to Option before trying the unification with F. 

I am closing this now since I don't see a clear road to a solution. If someone disagrees & wants to pick this up and do a PR with a solution great!
