### ISSUE TITLE
Comment examples in class OverridingPairs don't make it clear as to what is overriding and what is not.

### ISSUE THREAD

**Issue by ashwinbhaskar** [lampepfl/dotty#7908]
```
/*The current candidate symbol for overriding*/
var overriding: Symbol = _
/** If not null: The symbol overridden by overriding*/
var overridden: Symbol = _
```

The comment uses the same term to describe what it means. Would be more informative and useful to add an example in the comment for `overriding` and `overridden` to actually demonstrate what they mean.

I had trouble understanding what they mean when debugging an issue until it was made clear to me by @Blaisorblade on gitter with this example 
`take class Foo extends (Int => Int) { override def apply(x: Int) = x }. There, Foo.apply overrides Function1.apply? `

**Comment by ashwinbhaskar** [comment]
Can add this example given by @Blaisorblade on gitter
` take class Foo extends (Int => Int) { override def apply(x: Int) = x }. There, Foo.apply overrides Function1.apply — agreed?`

**Comment by Blaisorblade** [comment]
Also looking at your commit, there seems to be some misunderstanding. Those terms are taken for granted because they are being used in their standard meaning, as in e.g. https://en.m.wikipedia.org/wiki/Method_overriding. Which one is the confusing part?
That example is indeed nontrivial, as it involves the interaction of overriding and generics, but it’s still an instance of the general concept.

Or is your question about Scala-specific details, such as those specified in
https://scala-lang.org/files/archive/spec/2.13/05-classes-and-objects.html#overriding?

**Comment by ashwinbhaskar** [comment]
no, my confusion came from when I was debugging an issue (the abstract error one which you were helping me out with). I didn't know it was standard. Thought it would help others when debugging. If you feel it is redundant, I will delete this issue and the PR.

**Comment by ashwinbhaskar** [comment]
@Blaisorblade I guess it is redundant. I will close the PR.
