### ISSUE TITLE
No Labels found when Summoning Mirror and Passing to a Splice

### ISSUE THREAD

**Issue by deusaquilus** [lampepfl/dotty#8007]
## minimized code

```Scala
  // Summon a mirror for a particular type 
  inline def summonMirror[T]: Option[Mirror.Of[T]] =
    summonFrom {
      case given m: Mirror.Of[T] => Some(m)
      case _ => None
    }

  // Get fields from a mirror:
  inline def mirrorFields[Fields <: Tuple]: List[String] = 
    inline erasedValue[Fields] match {
      case _: (field *: fields) => constValue[field].toString :: mirrorFields[fields]
      case _ => Nil
    }

  inline def usingSummonFrom[T](value: =>T): String = 
    ${ usingSummonFromImpl('value, summonMirror[T]) }

  def usingSummonFromImpl[T: Type](value: Expr[T], m: Option[Mirror.Of[T]])(given qctx: QuoteContext): Expr[String] = {
    import qctx.tasty.{_, given}
    val theMirror = m match { case Some(mirror) => mirror }

    theMirror match {
      case m: Mirror.ProductOf[T] => println("it's a product: " + mirrorFields[m.MirroredElemLabels])
    }

    '{ "Doesn't matter" }
  }

```

## expectation
Say we have a `case class Person(name: String, age :Int)`, the fields `List("name", "age")` should be returned. Instead, the mirror contains no fields.

**Comment by deusaquilus** [comment]
I am trying to minimize this code but if I try to just returned the summoned mirror like this:
```scala
  def usingSummonFromImpl[T: Type](value: Expr[T], m: Option[Mirror.Of[T]])(given qctx: QuoteContext): Expr[Mirror.Of[T]] = {
    import qctx.tasty.{_, given}
    val theMirror = m match { case Some(mirror) => mirror }
    Expr(theMirror)
  }
```

I run into the following error:
```
[error] -- Error: /home/alexander/git/dotty/dotty_test/src/main/scala/derivation/SummonJsonEncoderTest.scala:26:19 
[error] 26 |    Expr(theMirror)
[error]    |                   ^
[error]    |no implicit argument of type quoted.Liftable[
[error]    |  scala.deriving.Mirror{
[error]    |    MirroredType = T; MirroredMonoType = T; MirroredElemTypes <: Tuple
[error]    |  }
[error]    |] was found for an implicit parameter of method apply in object Expr.
[error]    |I found:
[error]    |
[error]    |    quoted.Liftable.DoubleIsLiftable[Nothing]
[error]    |
[error]    |But method DoubleIsLiftable in object Liftable does not match type quoted.Liftable[
[error]    |  scala.deriving.Mirror{
[error]    |    MirroredType = T; MirroredMonoType = T; MirroredElemTypes <: Tuple
[error]    |  }
[error]    |].
```
Is there a way to wrap this mirror into an Expr and return it directly?

**Comment by biboudis** [comment]
Thanks for reporting this (these are super useful reports, keep them coming because they combine features). Just a small note: apart from minimisation it is super useful if we also get the imports, the enclosing objects and the `main` method code. We can quickly identity and turn this into either a pos, neg, or run test.

Regarding the error I didn't solve it but I have some observations: 

Initially, my reaction was that `List()` would be the right answer due to `case _ => Nil` in `mirrorFields`. After changing it to `case _: Unit => Nil` I started getting an irreducible match. 

```scala
cannot reduce inline match with
   |                            scrutinee:  scala.compiletime.erasedValue[m.MirroredElemTypes] : m.MirroredElemTypes
   |                            patterns :  case _:*:[field @ _, fields @ _]
   |                                        case _:Unit
```

The documented way to summon a given is with `summonExpr` inside macros. I don't know how this _pattern_ with `summonMirror` inside the top-level splice is intended to work (@nicolasstucki will provide insight here) so I proceeded with trying to reach to a workaround with `summonExpr`. Consequently, I used this structure (as we discussed here: https://github.com/lampepfl/dotty/issues/7974#issuecomment-574229592) but unfortunately I couldn't splice the mirror successfully. I wanted to effectively achieve this:

```scala
case '{$m: Mirror.ProductOf[T]} => "it's a product: " + mirrorFields[$m.MirroredElemLabels]
```

I added the test and will continue the investigation https://github.com/lampepfl/dotty/pull/8011

**Comment by deusaquilus** [comment]
@biboudis I'm assuming that `m` and not `$m` in `mirrorFields[$m.MirroredElemLabels]`. My main point is that I need *some* way to effectively summon mirrors inside of macros. If your approach above worked I could use that instead of my approach with `summonMirror` (I actually like it more since I can get any mirror I want in the macro as opposed to being forced to pass them in).

**Comment by biboudis** [comment]
https://github.com/lampepfl/dotty/pull/8011/commits/315071cc46e6424ecd3ed79a67a3d759df4b6874 demonstrates the workaround/solution to this problem
