### ISSUE TITLE
Primitive type operations pickling test fail

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#8287]
## minimized code

```Scala
import scala.compiletime.ops.int._
import scala.annotation.infix

object Test {
  class Vec[S <: Int] {
    @infix def concat [RS <: Int](that : Vec[RS]) : Vec[S + RS] = new Vec[S + RS]
  }

  val v1 = new Vec[1]
  val v2 = new Vec[2]
  val v3 : Vec[3] = v1 concat v2
  val v3a = v1 concat v2
  val v3b : Vec[3] = v3a
}
```

## Compilation output
This is the diff result between `before-pickling.txt` and `after-pickling.txt`
```scala
169c169
<         [(2 : scala.Int)]:((that: Test.Vec[(2 : scala.Int)]): Test.Vec[(1 : scala.Int) + (2 : scala.Int)])>@
---
>         [(2 : scala.Int)]:((that: Test.Vec[(2 : scala.Int)]): Test.Vec[(3 : scala.Int)])>@
172c172
<         Test.Vec[(1 : scala.Int) + (2 : scala.Int)]
---
>         Test.Vec[(3 : scala.Int)]
183c183
<         [(2 : scala.Int)]:((that: Test.Vec[(2 : scala.Int)]): Test.Vec[(1 : scala.Int) + (2 : scala.Int)])>@
---
>         [(2 : scala.Int)]:((that: Test.Vec[(2 : scala.Int)]): Test.Vec[(3 : scala.Int)])>@
186c186
<         Test.Vec[(1 : scala.Int) + (2 : scala.Int)]
---
>         Test.Vec[(3 : scala.Int)]
```
## expectation
Test should succeed. 

cc @OlivierBlanvillain @MaximeKjaer

**Comment by soronpo** [comment]
Evidently this issue also happens for `compiletime.S`, so this has nothing to do directly with @MaximeKjaer's changes. Here is a more minimized example.
```
import scala.compiletime.S
import scala.annotation.infix

object Test {
  class Vec[T <: Int] {
    @infix def foo (that : Int) = new Vec[S[T]]
  }

  val v2 : Vec[2] = new Vec[1] foo 1
}
```

**Comment by smarter** [comment]
To reproduce the error, run the compiler with `-Xprint-types -Ytest-pickler `

**Comment by smarter** [comment]
So the problem is we pickle the type `Vec[S[1]]` but we unpickle the type `Vec[2]`. To get -Ytest-pickler to pass, we could either always simplify the type before pickling (any reason not to do that ?), or change the pretty-printer to simplify the printed types so that both the type before and after pickling are printed in the same way. We already have a mechanism for doing this stuff, it's `homogenize` in `PlainPrinter`: https://github.com/lampepfl/dotty/blob/a29178ce4ac848e773423f57f45186373f410970/compiler/src/dotty/tools/dotc/printing/PlainPrinter.scala#L45-L69

**Comment by soronpo** [comment]
Thanks for the tip! Fixed it. Submitting a PR now.
