### ISSUE TITLE
Possibly Nonterminating Compilation

### ISSUE THREAD

**Issue by adamgfraser** [lampepfl/dotty#8463]
I apologize in advance I don't have a minimized example here.

I am observing that attempts to compile the code in [this](https://app.circleci.com/jobs/github/zio/zio/61432) PR does not appear to terminate. It times out after 10 minutes multiple times in CI and I am observing no output after more than 15 minutes locally. So it seems like it is not terminating or at least taking an extremely long time. The code compiles correctly on all Scala 2 versions in our build matrix.

The code at issue just adds higher order variants up to arity 22 for several different methods. The methods have implicit parameters which might be contributing to the issue but seem relatively innocuous (just class tags).

Any help you could provide in pointing to what I am doing wrong here or if there is indeed a compiler issue would be greatly appreciated. Thanks again and apologies for the lack of a minimized example.

**Comment by neko-kai** [comment]
Direct link to PR - https://github.com/zio/zio/pull/3054

**Comment by adamgfraser** [comment]
Update: the compilation did eventually complete. Unfortunately I closed my laptop during this process so I do not have an accurate time for compilation at this point but it does fit in the takes an extremely long time to compile category versus the nontermination category. Compiling again to time.

**Comment by smarter** [comment]
The problem comes from the definition of NotExtends: https://github.com/zio/zio/blob/c9cb6ec0fa793728f217694b335544d0a9aa1488/core/shared/src/main/scala-2.12%2B/zio/NotExtends.scala#L22-L27
This trick of relying on implicit ambiguity stopping implicit search to implement negation is **intentionally not supported by dotty**, see part 4 of http://dotty.epfl.ch/docs/reference/changed-features/implicit-resolution.html for details. Instead, one must use [`scala.implicits.Not`](https://github.com/lampepfl/dotty/blob/master/library/src/scala/implicits/Not.scala), and indeed if I change the definition of `MustNotHave` in https://github.com/zio/zio/blob/c9cb6ec0fa793728f217694b335544d0a9aa1488/core/shared/src/main/scala/zio/Has.scala#L52 to:
```scala
  type MustNotHave[A, B] = scala.implicits.Not[A <:< B]
```
then `coreJVM/compile` succeeds. (all the other definitions in https://github.com/zio/zio/tree/master/core/shared/src/main/scala-2.12+/zio use the same trick and will also need a dotty-specific version).

(BTW, I have no idea what you're using this type for but be careful: finding an implicit of type `A <:< B` means "I have proved that A is a subtype of B", but the negation of that is "I have _not_ proved that A is a subtype of B" which is not the same thing as "I have proved that A is _not_ a subtype of B" which is not something that can be done in general).

**Comment by adamgfraser** [comment]
@smarter Thank you for the detailed answer! Will follow up on my end.

**Comment by smarter** [comment]
Actually that should be:
```scala
  type MustNotHave[A, B] = scala.implicits.Not[A <:< Has[B]]
```
But that fails compilation in the definition of update:
```scala
[error] -- Error: /home/smarter/opt/zio/core/shared/src/main/scala/zio/Has.scala:131:25 
[error] 131 |      self.add(f(get[B]))
[error]     |                         ^
[error]     |no implicit argument of type zio.Has.MustNotHave[Self, B] was found for parameter ev of method add in class HasSyntax
```
Which makes perfect sense since update takes a `implicit ev: Self MustHave B` parameter, so there's a contradiction.

**Comment by smarter** [comment]
(you probably need to refactor the code to have both add and update call some private addUnchecked method which does not require implicit evidence one way or another)

**Comment by adamgfraser** [comment]
@smarter Thanks again for the detailed thoughts! Will work on this today.
