### ISSUE TITLE
Match typing with trait types doesn't work

### ISSUE THREAD

**Issue by travisbrown** [lampepfl/dotty#8493]
## minimized code

```Scala
trait Foo; trait Bar

type Res[X] = X match {
  case Foo => String
  case Bar => Int
}

0: Res[Bar]
```

## Compilation output

```scala
1 |0: Res[Bar]
  |^
  |Found:    (0 : Int)
  |Required: Res[Bar]
```

## expectation

It works as expected if you change the traits to classes, or if you reverse the order of the cases.

**Comment by OlivierBlanvillain** [comment]
That's working as intended. Reducing `Res[Bar]` to `Int` would be unsound, and once we merge #8024 it's going to be trivial to make a counter example. Given the `Res` type you defined above, the following should typecheck (after #8024):

```scala
def res[X](x: X): Res[X] = x match {
  case _: Foo => String
  case _: Bar => Int
}
```

However, if `Res[Bar]` reduces to `Int` we can use multiple inheritence to get a class cast exception:

```scala
class Boom extend Foo with Bar
val i: Int = res[Boom](new Boom())
println(i + 1) // java.lang.ClassCastException: class String cannot be cast to Integer
```

**Comment by travisbrown** [comment]
@OlivierBlanvillain Hmm, makes sense, thanks. This means I can't ever expect matching on function types to be useful, right, since `FunctionX` is a trait? My original use case looked like this:

```scala
scala> type Res[F] = F match {
     |   case ((a, b) => t) => String
     |   case ( a     => t) => Int
     | }

scala> 0: Res[Int => Int]
1 |0: Res[Int => Int]
  |^
  |Found:    (0 : Int)
  |Required: Res[Int => Int]
```

**Comment by OlivierBlanvillain** [comment]
Yes, matching on fonction types isn't going to lead to anywhere. I don't think it's because they are defined as traints, but rather because of variance. `Any => Int` is a subtype of both `Int => Int` and `((a, b) => t)`, so it would be wrong to reduce past the first case in your last example.

I know it's currently really hard to understand why certain match types don't reduce... I plan to invest time into better error messages for match types, in the worse case something à la `-Xlog-implicits` should be relatively easy to implement.

**Comment by travisbrown** [comment]
@OlivierBlanvillain Just to clarify for the record, I don't need to distinguish `Function1[Tuple2[a, b], t]` and `Function1[a, t]`, only `Function1` and `Function2`, so I don't think variance is the issue.
