### ISSUE TITLE
Allow custom copy method in case classes

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#874]
This currently fails:
```scala
case class Foo(elem: Int) {
  def copy(elem: Int): Foo = ???
}
```
```scala
cc.scala:2: error: method copy is already defined as method copy: (elem: Int)Foo
 (the definitions have matching type signatures)
  def copy(elem: Int): Foo = ???
        ^
```
I don't see why we couldn't let the user define his own `copy` method like in Scala 2, this is used in https://github.com/molecule-labs/molecule/blob/master/molecule-core/src/main/scala/molecule/seg/VSeg.scala#L134 to create a copy method with a more general type than the default one for case classes.

**Comment by odersky** [comment]
It's a tradeoff. copy needs to be executed at desugar, which means we do
not know the types of the other copy methods. So we either

 - always create a copy, and can't have a user defined one with the same
type signature (that's what dotty does)

 - never create a copy if there is another method named copy in the class,
but then we cannot automatically implement abstract copy methods in
superclasses and we cannot have overloaded variants.

Always is cleaner because it corresponds to what we do with `apply` in case
classes, which is also unconditionally generated. Note that `copy` and
`apply` are generated at the same time.



On Tue, Oct 27, 2015 at 3:28 AM, Guillaume Martres <notifications@github.com
> wrote:

> This currently fails:
>
> case class Foo(elem: Int) {
>   def copy(elem: Int): Foo = ???
> }
>
> cc.scala:2: error: method copy is already defined as method copy: (elem: Int)Foo
>  (the definitions have matching type signatures)
>   def copy(elem: Int): Foo = ???
>         ^
>
> I don't see why we couldn't let the user define his own copy method like
> in Scala 2, this is used in
> https://github.com/molecule-labs/molecule/blob/master/molecule-core/src/main/scala/molecule/seg/VSeg.scala#L134
> to create a copy method with a more general type than the default one for
> case classes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/issues/874>.
>



-- 
Martin Odersky
EPFL
