### ISSUE TITLE
Implicit conversion is not applied when the compiler has to also infer a type parameter

### ISSUE THREAD

**Issue by julienrf** [lampepfl/dotty#8803]
## Minimized code

```Scala
trait Foo
trait Bar
trait Qux[A]

object Test {
  implicit def fooToBar(x: Foo): Bar = ???

  def f(bar: Bar): Unit = {}

  def qux: Qux[Foo] = ???

  def g[A](qux: Qux[A]): A = ???

  f(g(qux))
}
```

## Output

```
-- [E007] Type Mismatch Error: try/i8803.scala:14:6 ----------------------------
14 |  f(g(qux))
   |      ^^^
   |      Found:    Qux[Foo]
   |      Required: Qux[A]
   |
   |      where:    A is a type variable with constraint <: Bar
```

## Expectation

The implicit conversion is applied.

## Workarounds

- Explicitly instantiate the type parameters:

~~~ diff
- f(g(qux)(baz))
+ f(g[Foo](qux)(baz))
~~~

**Comment by smarter** [comment]
I've simplified the example in the issue description and I don't think there's anything we can change here. In:
```scala
f(g(qux))
```
We make up a type variable `?A` for `g` and typecheck  `g[?A](qux)` with an expected type of `Bar`, from this we infer that the type variable `?A <: Bar`. Then we typecheck the argument `qux` and we're stuck because `Qux[Foo]` is not a subtype of `Qux[?A]`. Somehow scalac doesn't run into this issue because it doesn't add the constraint `?A <: Bar` before typechecking `qux`. But that means that it has the opposite problem, if I write:
```scala
trait Foo
trait Bar
trait Qux[A]

object Test {
  implicit def quxFooToQuxBar(x: Qux[Foo]): Qux[Bar] = ???

  def f(bar: Bar): Unit = {}

  def qux: Qux[Foo] = ???

  def g[A](qux: Qux[A]): A = ???

  f(g(qux))
}
```
then dotty is able to apply the implicit conversion when typechecking `qux`, but scalac fails with:
```scala
try/i8803.scala:15: error: type mismatch;
 found   : Foo
 required: Bar
  f(g(qux))
     ^
```

Dotty's behavior makes more sense to me because I know that inference proceeds first from top to bottom (propagate the expected type), then from bottom to top as expressions get typechecked, but I guess there isn't a canonical answer here. So in conclusion implicit conversions are bad and should be avoided :).

**Comment by julienrf** [comment]
Thanks for the detailed explanation!
