### ISSUE TITLE
Can't select correct overloaded method with varargs and Seq

### ISSUE THREAD

**Issue by Arthurm1** [lampepfl/dotty#9050]
Using Scastie - this compiles on Scala 2.13.2 but not Dotty (0.24.0-RC1)

## Minimized code

```Scala
object Foo {
  val foo = scala.collection.mutable.ArrayBuffer.empty[Seq[Double]]
  val bar = Seq.empty[Double]
  foo.append(bar)
}
```

## Output

```scala
cannot merge
  method append in trait Buffer of type (elems: A*): (Buffer.this : scala.collection.mutable.Buffer[A])  and
  method append in trait Buffer of type (elem: A): (Buffer.this : scala.collection.mutable.Buffer[A])
they are both defined in trait Buffer but have matching signatures
  (elems: Seq[Double]*): 
  (Foo.foo : scala.collection.mutable.ArrayBuffer[Seq[Double]]) and
  (elem: Seq[Double]): 
  (Foo.foo : scala.collection.mutable.ArrayBuffer[Seq[Double]])
as members of value foo
```

## Expectation
For Dotty to pick the non-varargs method.

**Comment by smarter** [comment]
@odersky This looks like a non-trivial limitation of the usage of signatures for overload resolution, the signature of the Buffer#append methods are:
```scala
def append(elem: A): this.type
def append(elems: A*): this.type
```
As seen from a preifx of type `ArrayBuffer[Seq[A]]` we get:
```scala
def append(elem: Seq[A]): this.type
def append(elems: Seq[A]*): this.type
```
Those have the same signatures, but are otherwise unrelated. It would be good to figure out how to deal with this sooner rather than later since tasty critically relies on signatures for overload resolution.

This is the inverse of the problem detailed in https://github.com/lampepfl/dotty/issues/8929

**Comment by odersky** [comment]
I'd argue it's the wrong design. `Buffer.append` should have these signatures:
```
def append(elem: A): this.type
def append(elem: A, elems: A*): this.type
```
But it's true we will need to see how we can deal with it.
