### ISSUE TITLE
No eta-expansion of nilary method when SAM type is expected

### ISSUE THREAD

**Issue by lrytz** [lampepfl/dotty#9135]
The folowing doesn't compile, @odersky is this by design?

```Scala
@FunctionalInterface trait Sam { def f(): Int }
object T {
  def f(): Int = ???
  val x: Sam = f
}
```

The error is:

```scala
4 |  val x: Sam = f
  |               ^
  |               method f must be called with () argument

```

https://dotty.epfl.ch/docs/reference/changed-features/eta-expansion-spec.html doesn't mention SAM types, it just says

> an unapplied method with an empty argument list is only converted to a function when a function type is expected

**Comment by odersky** [comment]
Yes, that's by design. The clause you cite rules out SAM types. I believe converting unapplied functions to SAM types is dicey anyway, in the sense that it can easily give something unexpected. I personally would have preferred to only convert lambdas to SAMs, not method handles. That ship has sailed, but I am against introducing even more flexibility here.

**Comment by lrytz** [comment]
OK, so we have to adjust what scalac does under `-Xsource:3`.
