### ISSUE TITLE
Val is not stable unless path requested by use site

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#9276]
it seems that a val is not stable in TASTy unless a stable path is requested for it:
## Minimized code
```scala
// before
object Consts {
  val msg = "Hello World" // not stable
}
object TestConsts {
  def foo = Consts.msg
}
```

```scala
// after
object Consts {
  val msg = "Hello World" // now it is stable because of a use site
}
object TestConsts {
  def foo: Consts.msg.type = Consts.msg
}
```

## Output

before:
```scala
80:       VALDEF(7) 26 [msg]
83:         TYPEREF 27 [String]
85:           SHAREDtype 35
87:         STRINGconst 28 [Hello World]
```
after:
```scala
80:       VALDEF(8) 26 [msg]
83:         TYPEREF 27 [String]
85:           SHAREDtype 35
87:         STRINGconst 28 [Hello World]
89:         STABLE
```

**Comment by smarter** [comment]
@anatoliykmetyuk I don't have time to take on more issues currently.

**Comment by odersky** [comment]
STABLE can be either user-declared, or structural, in which case it is a hint only. Absence of STABLE when it is a hint is no problem, since it will be re-generated when tested. But maybe the declared and computed versions should be different flags.

**Comment by odersky** [comment]
I had a look. It does not seem possible to fix this, unless we spend a flag, and we have very few left. So, what is the problem here exactly? StableRealizable is an assertion that a value is stable and relializable. It is sometimes an assertion, and at other times a cache, meaning that it simply avoids a recomputation of the property. Can't we leave that as it is?

**Comment by smarter** [comment]
>  So, what is the problem here exactly?

One problem I can think of is it breaks reproducible builds: depending on whether two files are compiled together or one after another, the STABLE flag will be present in tasty or not. Quite a lot of work went into achieve deterministic compilation in Scala 2 to avoid this sort of things, in particular because it's important for build systems that rely heavily on caching compiler artifacts: https://github.com/scala/scala-dev/issues/405

**Comment by smarter** [comment]
Could we explicitly compute if something is StableRealizable at Pickler to emit STABLE even if the cache hasn't been set yet?

**Comment by odersky** [comment]
> Could we explicitly compute if something is StableRealizable at Pickler to emit STABLE even if the cache hasn't been set yet?

Not really, since the check is expensive and risks creating cycles. The check is performed only in specific cases right now, which are relatively rare (essentially when we have to ensure that something is a path).

**Comment by smarter** [comment]
I assume it can create cycles in Typer, but can it also create cycles in Pickler? The expensiveness might be an issue, though I hoped having it always stored in tasty means we wouldn't have to either recompute it on unpickled symbols, which would amortize it somewhat since we
