### ISSUE TITLE
Inconsistent results between Scope.decl and Scope.find (corrupted hash table?)

### ISSUE THREAD

**Issue by sjrd** [lampepfl/dotty#9390]
This is an internal issue. In #8652 I had to introduce [in `Constructors.scala`](https://github.com/lampepfl/dotty/pull/8652/files#diff-ae54f2f3a43992e856656c8617efe524) a workaround for what appears to be a corrupted `Scope` data structure. At least I clearly observe an inconsistency between
```scala
info.decl(setterName)
```
which does *not* find anything, and
```scala
info.decls.find(d => d.name == setterName)
```
which *does* find what I'm looking for.

## Reproduction

Remove the workaround (i.e., always use `val symSetter = sym.setter`) and run `testCompilation`. Observe that several tests do not pass. At the time of writing, the following tests are failing:
```
    tests/run/i744.scala failed
    tests/run/t8087.scala failed
    tests/pos/t5508.scala failed
    tests/pos/getset.scala failed
    tests/pos/traits.scala failed
    tests/pos/scala2traits failed
    dotty1 from tastyBootstrap/dotty1 failed
```

**Comment by smarter** [comment]
Tracing the issue in tests/run/i744.scala, I get to:
https://github.com/lampepfl/dotty/blob/eb3b0ac87b65f68fc7403c446a63b0cd31540255/compiler/src/dotty/tools/dotc/core/Scopes.scala#L368

The check `e.name != name` is failing because `e.name` is `s` whereas `name` is `A$$s`. The correct name for the entry is in `e.sym.name`. So the problem is that the name we use for table lookup will always be the name at which the symbol was entered in the scope, which might not match its current name. Not sure how to fix that except by enforcing that lookups  should always go through `origin.name` /cc @odersky

**Comment by odersky** [comment]
I think there's nothing we can do here in the short term. Any attempts to work around this run into problems.
