### ISSUE TITLE
Issue with type inference?

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#961]
The following code does not compile with dotc but does with scalac.
```scala
object Test {
  abstract class A {
    class B
    def apply: B = new B
  }

  object C extends A

  def foo: C.B = {
    val a = C
    a.apply
  }
}
```
```
error: type mismatch:
 found   : a.B
 required: Test.C.B
    a.apply
      ^
one error found
```

It does compile if I explicitly give the type of `a`: `val a: C.type = C`

**Comment by odersky** [comment]
The difference is intentional. Both Scala and Dotty infer singleton types only on demand. But Dotty and Scala 2 differ in what concerns the treatment of objects. In Dotty an object is just a lazy val, whereas in Scala 2 it has a different (and rather muddled) character. A particular effect of the Scala 2 treatment was that the object class and its singleton value were conflated, which led to the code you wrote being accepted by scalac. The Dotty characterization is much better IMO, since it is both simple and precise. But it means you have to give the type ascription.
