### ISSUE TITLE
-rewrite -new-syntax must be executed before -rewrite -indent

### ISSUE THREAD

**Issue by etorreborre** [lampepfl/dotty#9661]
Otherwise indent-aware code cannot be compiled with `-rewrite -new-syntax` only. And adding both options with `-rewrite -new-syntax -indent` leads to 
```
illegal combination of -rewrite targets: -new-syntax and -indent
```

## Expectation

That it should be possible to compile a Scala2 code base with:
```
-rewrite -indent
-rewrite -new-syntax
```
Or to specify the proper order in the documentation

**Comment by odersky** [comment]
I think that's beyond what we intend to provide. In fact, I am not even sure anymore that rewriting to indentation syntax is such a great idea at all. Since indentation and braces syntax can be arbitrarily mixed, there's little point in convering programs wholesale. I simply convert to indented any statement in our codebase that I touch. That way git history is not destroyed and I can see at a glance whether a change is new or old.

**Comment by etorreborre** [comment]
Feel free to close if you want. This has nevertheless be very useful for me to be able to convert my library all at once. I don't intend to revisit every line very often and I still wanted to use the indented style everywhere. As long as there is at least one way to convert Scala 2 codebases to Scala 3 you might want to put your efforts somewhere else.

**Comment by odersky** [comment]
Actually, the docs already specify this. Here it is, in `indentation.md`:

> The `-indent` option only works on [new-style syntax](./control-syntax.html). So to go from old-style syntax to new-style indented code one has to invoke the compiler twice, first with options `-rewrite -new-syntax`, then again with options
`-rewrite -indent`. To go in the opposite direction, from indented code to old-style syntax, it's `-rewrite -noindent`, followed by `-rewrite -old-syntax`.
