### ISSUE TITLE
-Ycheck-init promoting value to fully initialised when passed to array

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#9664]
## Minimized code

```Scala
// compile with -Ycheck-init
object Wrap1 {                                                                              
  class E
  object E {
    final val A = E()
    val $values = Array(A)
  }
}
object Wrap2 {                                                                              
  class E
  object E {
    final val A = E()
    val ref = A
  }
}
```

## Output

```scala
-- Warning: initcheck.scala:5:23 ----------------------------------
5 |    val $values = Array(A)
  |                        ^
  |Promoting the value under initialization to fully-initialized. Calling trace:
  | -> val $values = Array(A)	[ initcheck.scala:5 ]
1 warning found
```

## Expectation

I thought that directly referencing the value should have the same behaviour as passing it to an array constructor

**Comment by liufengyun** [comment]
This is a bug, because `E()` returns a fully constructed object in the context of initializing `object E`. Now it is fixed in #9665 .

> I thought that directly referencing the value should have the same behaviour as passing it to an array constructor


There is a subtle difference here. Use a partially constructed value to initialize another field is OK, the fields of the object are not used. In contrast, using a partially constructed object as method argument is dangerous (as non-initialized fields might be accessed elsewhere). As it's not a good initialization practice, the checker issue a warning for such cases.
