### ISSUE TITLE
ValDef name is not normalised

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#9772]
## Minimized code

```Scala
class Foo { var extension_bar = 23 }
```

## Output

```scala
scala> class Foo { var extension_bar = 23 }
// defined class Foo
```

## Expectation

names should not begin with `extension_`. I see that in Desugar `normalizeName` is not called for ValDef

my small motivation being here that var accessors are represented as methods in semanticDB

**Comment by tudorv91** [comment]
Hi all, I would like to provide a fix for this issue. Since I am new to this project, I would like to make sure that the desired outcome is clear to me:
- We can print an error for value defs starting with `extension_` when they impose automatic generation of setter methods (e.g. when they are non-private). This would replicate the restriction of method names.
- Although the first solution is trivial and would follow a current practice, I am wondering if it is ideal to restrict member names because of the compiler's inner workings.

**Comment by tudorv91** [comment]
Hi all, I would like to provide a fix for this issue. Since I am new to this project, I would like to make sure that the desired outcome is clear to me:
- We can print an error for value defs starting with `extension_` when they impose automatic generation of setter methods (e.g. when they are non-private). This would replicate the restriction of method names.
- Although the first solution is trivial and would follow a current practice, I am wondering if it is ideal to restrict member names because of the compiler's inner workings.

**Comment by smarter** [comment]
> I am wondering if it is ideal to restrict member names because of the compiler's inner workings.

This isn't really compiler internals: the fact that extension methods desugar into something that starts with `extension_` that users can also call directly is part of their specification: http://dotty.epfl.ch/docs/reference/contextual/extension-methods.html

**Comment by tudorv91** [comment]
> > I am wondering if it is ideal to restrict member names because of the compiler's inner workings.
> 
> This isn't really compiler internals: the fact that extension methods desugar into something that starts with `extension_` that users can also call directly is part of their specification: http://dotty.epfl.ch/docs/reference/contextual/extension-methods.html

I see, thanks for clarifying, @smarter . I've created a small pull request for this one https://github.com/lampepfl/dotty/pull/9836.
