### ISSUE TITLE
None of the overloaded alternatives of method ... match arguments 

### ISSUE THREAD

**Issue by Sciss** [lampepfl/dotty#9819]
## Minimized code

```Scala
import scala.collection.immutable.{IndexedSeq => Vec}

object UGenSource {
  abstract class ZeroOut   extends UGenSource[Unit]
  abstract class SingleOut extends SomeOut
  abstract class MultiOut  extends SomeOut

  sealed abstract class SomeOut extends UGenSource[UGenInLike] with GE

  def unwrap(source: UGenSource.ZeroOut, args: Vec[UGenInLike]): Unit       = ()
  def unwrap(source: UGenSource.SomeOut, args: Vec[UGenInLike]): UGenInLike = ???
}
sealed abstract class UGenSource[U] {
  protected def makeUGens: U
}

case class Constant(value: Float) extends UGenIn

object GE {
  implicit def intIsConst(i: Int): Constant = Constant(i.toFloat)
}
trait GE {
  def expand: UGenInLike
}

trait UGenInLike extends GE {
  def expand: UGenInLike = this
}

sealed trait UGenIn extends UGenInLike 

final case class MFCC(chain: GE, numCoeffs: Int = 13)
  extends UGenSource.MultiOut {
    
  import UGenSource.unwrap
    
  def expand: UGenInLike = makeUGens

  protected def makeUGens: UGenInLike = unwrap(this, Vector(chain.expand, numCoeffs)) // !
}
```

## Output

does not compile because

```scala
None of the overloaded alternatives of method unwrap in object UGenSource with types
 (source: UGenSource.SomeOut, args: IndexedSeq[UGenInLike]): UGenInLike
 (source: UGenSource.ZeroOut, args: IndexedSeq[UGenInLike]): Unit
match arguments ((MFCC.this : MFCC), Vector[Any])
```

https://scastie.scala-lang.org/NtdP6snnRBK0SbSXZHqhtA

## Expectation

should work - see Scala 2.13: https://scastie.scala-lang.org/ZYLZIPGTTdaOc6spOi2dzA

**Comment by smarter** [comment]
Thiis is quite a bit of code, can this be simplified further or is this really minimal? Of the two overloads of unwrap only one is actually used, does the problem go away if the other one is removed? Is the implicit conversion also needed to trigger the problem?

**Comment by Sciss** [comment]
Yes and yes. The overload is needed and the implicit conversion is needed, to trigger the problem (early inference of `Vector[Any]`).

**Comment by Sciss** [comment]
Slightly less noisy, same problem:

```scala
import scala.collection.immutable.{IndexedSeq => Vec}

object UGenSource {
  abstract class ZeroOut
  abstract class MultiOut

  def unwrap(source: ZeroOut , args: Vec[GE]): Unit  = ()
  def unwrap(source: MultiOut, args: Vec[GE]): GE    = ???
}

object GE {
  implicit def intIsConst(i: Int): GE = ???
}
trait GE {
  def expand: GE
}

final case class MFCC(chain: GE, numCoeffs: Int = 13)
  extends UGenSource.MultiOut {
    
  import UGenSource.unwrap
    
  def expand: GE =unwrap(this, Vector(chain.expand, numCoeffs))
}
```

**Comment by som-snytt** [comment]
Scala 2 seems to work by excluding the Unit version because there is no conversion `Unit => GE` (per the expected type in expand). I didn't think it was specified that way.

If both methods return GE, and remain candidates, the types of args aligns and is used as expected type for the Vector.apply. I think that is part of improved inference and is specified. Then only one alternative is applicable.

If `MultiOut extends ZeroOut`, it chooses the more specific alternative. (yay)

If one of the alt args param is Vector[Any], that is used to infer Vector[Any]. The result is neither applies, as for Scala 3. The common intuition is that it ought to infer Vector[GE] (using the narrower param type) because one of the alternatives applies. (It could then use the wider type and try again if no alts were viable.)

**Comment by Sciss** [comment]
Note that `MultiOut` _does not_  expand `ZeroOut`. When calling `wrap(this, ...)` there is no ambiguity at this point. Either the caller is a `ZeroOut` or a `MultiOut`. And the same goes for the return type, there is no connection between `GE` and `Unit`.

**Comment by som-snytt** [comment]
To clarify my previous comment, args to an overloaded method used to be typechecked without an expected type. So I expected scala 2 to infer `Vector[Any]`, unless improved typechecking kicked in, and I wasn't actually sure that happens if the parameters are not functions.

To recap, scala 2 excludes one alternative based on result type, and does not do "special typechecking of args to overloaded application". That is, "there is no ambiguity when calling `unwrap(x, y): GE`" because there is only one possible alternative.

If it couldn't exclude one alternative (for example because both returned GE), it notices that the types align and uses `Vector[GE]` as an expected type for the second arg to `unwrap`. Only one of the alternatives is applicable to `unwrap(this: GE, y)`.

If, in addition, one of the formal params was changed to `Vector[Any]`, then `Vector[Any]` is inferred, even though inferring `Vector[GE]` is a possible solution. At that point, neither alternative would apply.

As a sanity check, which I needed, I verified that it takes the most specific if both alternatives apply (for instance if MultiOut is changed to extend ZeroOut).

Please consider this a "note to self" if nothing else.

**Comment by odersky** [comment]
This looks like a very tricky corner case. I cannot find spec language that specifies why this should work, and I cannot find a handle in the resolution algorithm that would permit it. As @som-snytt has mentioned, there are two possible avenues to make this example compile

 1. Notice that the expected type is the same for all alternatives and typecheck arguments with that expected type. This is in general quite complex and expensive to detect, in particular if there are type parameters involved. I noted that's actually not what scalac does here; the example compiles even if the second parameter types are different.
 2. Rule out alternatives beforehand if they cannot be made to correspond to the expected result type. But that fails again if the function's result type contains type parameters. And it seems to be backwards: We do overloading resolution first and then ry to make the result fit, which could mean inserting an implicit conversion. 

The whole problem would be fixed if we do not have implicit conversions to deal with, since then we could constrain alternatives by typechecking result types instead. So in a future where the ability to do implicit conversions has to be explicitly imported we could make this work (but then of course, the Vector argument would not typecheck either, since it relies on an implicit conversion. 

Overall, I believe there's nothing we can do here, so I am closing this for now.
