### ISSUE TITLE
Ambiguous reference yields wrong error message

### ISSUE THREAD

**Issue by rjolly** [lampepfl/dotty#9882]
```Scala
trait SemiGroup[T]:
  def combine(x: T, y: T): T

trait Monoid[T] extends SemiGroup[T]:
  def unit: T

class A

given Monoid[A]:
  def combine(x: A, y: A) = ???
  def unit = ???

class B

given Monoid[B]:
  def combine(x: B, y: B) = ???
  def unit = ???

import given_Monoid_A.combine
import given_Monoid_B.combine
val a = new A
val b = new B
println(combine(b, b))
        ^^^^^^^
      Reference to combine is ambiguous,
      it is both imported by name by import dotty.DottyPredef.{...}
      and imported by name subsequently by import given_Monoid_B.combine
```

**Comment by som-snytt** [comment]
Duplicates https://github.com/lampepfl/dotty/issues/9803

**Comment by rjolly** [comment]
Closing the issue then. For the record, I don't understand why this has to be ambiguous, whereas the code below is not.
```
class A
class B

object C:
  def combine(x: A, y: A) = ???
  def combine(x: B, y: B) = ???

import C._
val a = new A
println(combine(a, a))
```

**Comment by som-snytt** [comment]
The latter is an overloaded symbol `C.combine`, where an alternative is picked by overload resolution.

The former is an ambiguity in name binding, because there is no basis for preferring one binding over the other.

This comes up periodically, where the expectation is that a multiple-binding could be treated like an overloaded symbol, much as multiple candidates in an implicit search are resolved using the same procedure as overload resolution.

I think the expectation is that intertwining name resolution and typechecking more than the minimum would invite cycles.
