### ISSUE TITLE
Cannot translate usage of wildcard type from Scala 2

### ISSUE THREAD

**Issue by oyvindberg** [lampepfl/dotty#9897]
## Minimized code

```Scala
type WatchHandler[T] = Function2[/* val */ T, /* oldVal */ T, scala.Unit]
val handlers: Seq[WatchHandler[_]] = Nil
```

## Output

```
unreducible application of higher-kinded type [T] =>> (T, T) => Unit to wildcard arguments
```

## Expectation
In Scala 2 this compiles. I tried replacing with `?` instead, but got the same error.

**Comment by smarter** [comment]
This is intentionally not supported: we only allow wildcards on class types (because anything else would be equivalent to existential types which we don't support), some alternatives you could use:
- wrap the type in a class: `class WatchHandler[T](f: Function2[T, T, scala.Unit]`
- extend Function2: `trait WatchHandler[T] extends Function2[T, T, scala.Unit]`
- not sure if it would make sense here, but one could use the new-in-dotty polymorphic function types: `val handlers: Seq[[T] => () => WatchHandler[T]] = Nil`, cf https://github.com/lampepfl/dotty/pull/4672
