### ISSUE TITLE
Dotty snapshots

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#992]
I've set up the EPFL jenkins to publish Snapshots of dotty every night.

They are currently published to http://oss.jfrog.org/artifactory/oss-snapshot-local/me/d-d/
I am waiting for bintray to allow publishing under either ch.epfl.lamp or org.scala-lang.

The same artifactory could be one day used to promote a release to both JCenter and Maven Central.

Additionally, all historical artifacts will be available here: https://d-d.me/dotty/artifacts if we ever want to do a bisect with binaries.

**Comment by DarkDimius** [comment]
In order to depend on Dotty SNAPSHOT in sbt, one needs to add

```
resolvers +=
  "JFrog OSS Artifactory" at "http://oss.jfrog.org/artifactory/oss-snapshot-local/"
```
to sbt config in order to be able to get snapshots from JFrog\Bintray.

after that adding either `"me.d-d" % "dotty_2.11" % "0.1-SNAPSHOT"` or `"me.d-d" % "dotty-bootstrapped" % "0.1-SNAPSHOT"` should work. 
Note that currently running bootstrapped dotty requires a bit of dark classloader magic.

**Comment by smarter** [comment]
@DarkDimius : How do you create and publish `dotty-bootstrapped`? I think I finally found a good solution for SBT support but I have only tested it with `dotty_2.11` so far. (Also, I think that instead of calling it `dotty-boostrapped` we should call it `dotty_0.1`, this way SBT should be able to get it if I just specify `scalaBinaryVersion := 0.1`.)

**Comment by DarkDimius** [comment]
@smarter it's a jar created by `dotc.build`. It is published by Jenkins just before running nightly benchmarks.
